import Foundation

enum AppLocalization {
    static func text(_ english: String, languageRaw: String) -> String {
        let language = AppLanguage(rawValue: languageRaw) ?? .english
        guard language != .english else { return english }
        return translations(for: language)[english] ?? english
    }

    private static func translations(for language: AppLanguage) -> [String: String] {
        switch language {
        case .english:
            return [:]
        case .german:
            return german.merging(germanExtras) { _, new in new }
        case .italian:
            return italian.merging(italianExtras) { _, new in new }
        case .spanish:
            return spanish.merging(spanishExtras) { _, new in new }
        case .french:
            return french.merging(frenchExtras) { _, new in new }
        }
    }

    private static let german: [String: String] = [
        "Settings": "Einstellungen",
        "Language": "Sprache",
        "Privacy Policy": "Datenschutzerklärung",
        "How your data is used": "Wie deine Daten verwendet werden",
        "Sign out": "Abmelden",
        "Delete profile permanently": "Profil dauerhaft löschen",
        "Deleting account...": "Konto wird gelöscht...",
        "Delete profile permanently?": "Profil dauerhaft löschen?",
        "Delete everything": "Alles löschen",
        "Cancel": "Abbrechen",
        "This deletes your account, profile, drafts, published issues, friend connections and groups you own.": "Das löscht dein Konto, Profil, Entwürfe, veröffentlichte Ausgaben, Freundschaften und Gruppen, die dir gehören.",
        "Confirm Password": "Passwort bestätigen",
        "Delete account permanently": "Konto dauerhaft löschen",
        "Incorrect password.": "Falsches Passwort.",
        "Profile": "Profil",
        "Edit profile": "Profil bearbeiten",
        "Change profile photo": "Profilfoto ändern",
        "Display name": "Anzeigename",
        "Save profile": "Profil speichern",
        "Your name": "Dein Name",
        "Username": "Benutzername",
        "Password": "Passwort",
        "Confirm password": "Passwort bestätigen",
        "Create Profile": "Profil erstellen",
        "Please enter your email.": "Bitte gib deine E-Mail ein.",
        "Password reset email sent.": "E-Mail zum Zurücksetzen wurde gesendet.",
        "Profile saved.": "Profil gespeichert.",
        "Friends": "Freunde",
        "My friends": "Meine Freunde",
        "No friends yet.": "Noch keine Freunde.",
        "Remove": "Entfernen",
        "Remove friend?": "Freund entfernen?",
        "You will no longer be connected.": "Ihr seid danach nicht mehr verbunden.",
        "Friend Requests": "Freundschaftsanfragen",
        "Friend requests": "Freundschaftsanfragen",
        "pending": "ausstehend",
        "friends": "Freunde",
        "Accept": "Annehmen",
        "Decline": "Ablehnen",
        "PenPal archive": "PenPal-Archiv",
        "Stay in each other's chapters.": "Bleib Teil der Geschichten deiner Freunde.",
        "New Issue": "Neue Ausgabe",
        "Start creating": "Erstellen starten",
        "Drafts": "Entwürfe",
        "Continue your unfinished issues": "Bearbeite deine unfertigen Ausgaben weiter",
        "Sign up": "Registrieren",
        "Log in": "Einloggen",
        "Forgot password?": "Passwort vergessen?",
        "Reset password": "Passwort zurücksetzen",
        "Enter your email and we’ll send you a link to set a new password.": "Gib deine E-Mail ein und wir senden dir einen Link zum Zurücksetzen.",
        "Send reset email": "Reset-E-Mail senden",
        "Please enter a username.": "Bitte gib einen Benutzernamen ein.",
        "Passwords do not match.": "Die Passwörter stimmen nicht überein.",
        "Username must be at least 3 characters.": "Der Benutzername muss mindestens 3 Zeichen haben.",
        "Username too long.": "Der Benutzername ist zu lang.",
        "This username is already taken.": "Dieser Benutzername ist bereits vergeben.",
        "No throwbacks yet — published issues will appear here.": "Noch keine Rückblicke — veröffentlichte Ausgaben erscheinen hier.",
        "Throwback": "Rückblick",
        "Delete": "Löschen",
        "Delete issue?": "Ausgabe löschen?",
        "This issue will be permanently removed.": "Diese Ausgabe wird dauerhaft entfernt.",
        "Group": "Gruppe",
        "Group magazines": "Gruppenmagazine",
        "Year": "Jahr",
        "Add group picture": "Gruppenbild hinzufügen",
        "Leave group": "Gruppe verlassen",
        "Delete group": "Gruppe löschen",
        "Leave group?": "Gruppe verlassen?",
        "Leave": "Verlassen",
        "You will no longer receive magazines from this group.": "Du erhältst keine Magazine mehr aus dieser Gruppe.",
        "Delete group?": "Gruppe löschen?",
        "This permanently deletes the group for all members.": "Das löscht die Gruppe dauerhaft für alle Mitglieder.",
        "Members": "Mitglieder",
        "No members yet": "Noch keine Mitglieder",
        "Create group": "Gruppe erstellen",
        "Creating...": "Wird erstellt...",
        "Group name": "Gruppenname",
        "people · add or view members": "Personen · Mitglieder hinzufügen oder ansehen",
        "Member added.": "Mitglied hinzugefügt.",
        "Please enter a group name.": "Bitte gib einen Gruppennamen ein.",
        "You already have a group with this name.": "Du hast bereits eine Gruppe mit diesem Namen.",
        "User not found.": "Benutzer nicht gefunden.",
        "Already in group.": "Bereits in der Gruppe.",
        "Saved Drafts": "Gespeicherte Entwürfe",
        "No drafts yet — start your first issue and save it here.": "Noch keine Entwürfe — starte deine erste Ausgabe und speichere sie hier.",
        "Delete draft?": "Entwurf löschen?",
        "This draft will be permanently removed.": "Dieser Entwurf wird dauerhaft entfernt.",
        "Draft": "Entwurf",
        "Publish to": "Veröffentlichen in",
        "Continue editing": "Weiter bearbeiten",
        "Preview draft": "Entwurf ansehen",
        "Publish draft": "Entwurf veröffentlichen",
        "This draft has no pages to publish.": "Dieser Entwurf hat keine Seiten zum Veröffentlichen.",
        "Loading draft...": "Entwurf wird geladen...",
        "This draft has no editable pages.": "Dieser Entwurf hat keine bearbeitbaren Seiten.",
        "This draft is still loading or has no editable pages.": "Dieser Entwurf lädt noch oder hat keine bearbeitbaren Seiten.",
        "No pages saved.": "Keine Seiten gespeichert.",
        "Page": "Seite",
        "of": "von",
        "Edit": "Bearbeiten",
        "No magazines published this month yet.": "Diesen Monat wurden noch keine Magazine veröffentlicht.",
        "Preprint review": "Vorabprüfung",
        "Delete any pages you don't want to include. Magazines can contain up to 30 pages.": "Lösche alle Seiten, die du nicht einschließen willst. Magazine können bis zu 30 Seiten enthalten.",
        "Delete any page you do not want. The layout is locked to the PowerPoint template. Text boxes can be written in; photo boxes keep their size and only the photo inside can be zoomed or moved.": "Lösche alle Seiten, die du nicht möchtest. Das Layout ist an die PowerPoint-Vorlage gebunden. Textfelder können beschrieben werden; Fotoboxen behalten ihre Größe, nur das Foto darin kann gezoomt oder verschoben werden.",
        "Edit selected pages": "Ausgewählte Seiten bearbeiten",
        "Generated issue": "Erstellte Ausgabe",
        "No pages to edit.": "Keine Seiten zum Bearbeiten.",
        "Preview finished magazine": "Fertiges Magazin ansehen",
        "Edit magazine": "Magazin bearbeiten",
        "Finished magazine preview": "Vorschau des fertigen Magazins",
        "Edit this page": "Diese Seite bearbeiten",
        "Delete page": "Seite löschen",
        "No pages to preview.": "Keine Seiten für die Vorschau.",
        "Preview": "Vorschau",
        "Add sections or pages": "Kapitel oder Seiten hinzufügen",
        "All sections are already in this issue.": "Alle Kapitel sind bereits in dieser Ausgabe.",
        "Add selected": "Auswahl hinzufügen",
        "Finish issue": "Ausgabe fertigstellen",
        "Publish to groups": "In Gruppen veröffentlichen",
        "You are not in any groups yet.": "Du bist noch in keiner Gruppe.",
        "Sections added. Save the draft to keep these changes.": "Kapitel hinzugefügt. Speichere den Entwurf, um diese Änderungen zu behalten.",
        "Page deleted. Save the draft to keep this change.": "Seite gelöscht. Speichere den Entwurf, um diese Änderung zu behalten.",
        "Create at least one page first.": "Erstelle zuerst mindestens eine Seite.",
        "Draft could not be prepared for saving.": "Der Entwurf konnte nicht zum Speichern vorbereitet werden.",
        "Draft could not be saved:": "Entwurf konnte nicht gespeichert werden:",
        "Draft saved. You can find it in Drafts.": "Entwurf gespeichert. Du findest ihn unter Entwürfe.",
        "Select at least one group.": "Wähle mindestens eine Gruppe aus.",
        "An issue can contain up to 30 pages.": "Eine Ausgabe kann bis zu 30 Seiten enthalten.",
        "Your magazine has more than 30 pages. Delete pages before publishing.": "Dein Magazin hat mehr als 30 Seiten. Lösche Seiten, bevor du veröffentlichst.",
        "Your issue has too many photos. Please keep it under 50 photos.": "Deine Ausgabe hat zu viele Fotos. Bitte bleibe unter 50 Fotos.",
        "Issue published. You can find it in old magazines.": "Ausgabe veröffentlicht. Du findest sie in alten Magazinen.",
        "Issue could not be published:": "Ausgabe konnte nicht veröffentlicht werden:",
        "Saving...": "Wird gespeichert...",
        "Save for later": "Für später speichern",
        "Save Draft": "Entwurf speichern",
        "Continue Draft": "Entwurf fortsetzen",
        "Load Draft": "Entwurf laden",
        "Local Draft": "Lokaler Entwurf",
        "Draft saved locally.": "Entwurf lokal gespeichert.",
        "Continue editing your saved local draft": "Bearbeite deinen lokal gespeicherten Entwurf weiter",
        "Local draft could not be loaded:": "Lokaler Entwurf konnte nicht geladen werden:",
        "Publishing...": "Wird veröffentlicht...",
        "Publish selected groups": "In ausgewählten Gruppen veröffentlichen",
        "slide to track progress": "schieben, um Fortschritt zu markieren",
        "swipe to review": "wischen zum Bewerten"
    ]

    private static let italian: [String: String] = german.mapValues { _ in "" }.merging([
        "Settings": "Impostazioni", "Language": "Lingua", "Privacy Policy": "Informativa privacy", "How your data is used": "Come vengono usati i tuoi dati", "Sign out": "Esci", "Delete profile permanently": "Elimina profilo definitivamente", "Deleting account...": "Eliminazione account...", "Delete profile permanently?": "Eliminare il profilo definitivamente?", "Delete everything": "Elimina tutto", "Cancel": "Annulla", "This deletes your account, profile, drafts, published issues, friend connections and groups you own.": "Questo elimina account, profilo, bozze, numeri pubblicati, amicizie e gruppi che possiedi.", "Confirm Password": "Conferma password", "Delete account permanently": "Elimina account definitivamente", "Incorrect password.": "Password errata.", "Profile": "Profilo", "Edit profile": "Modifica profilo", "Change profile photo": "Cambia foto profilo", "Display name": "Nome visualizzato", "Save profile": "Salva profilo", "Your name": "Il tuo nome", "Username": "Username", "Password": "Password", "Confirm password": "Conferma password", "Create Profile": "Crea profilo", "Please enter your email.": "Inserisci la tua email.", "Password reset email sent.": "Email di reset inviata.", "Profile saved.": "Profilo salvato.", "Friends": "Amici", "My friends": "I miei amici", "No friends yet.": "Ancora nessun amico.", "Remove": "Rimuovi", "Remove friend?": "Rimuovere amico?", "You will no longer be connected.": "Non sarete più collegati.", "Friend Requests": "Richieste di amicizia", "Friend requests": "Richieste di amicizia", "pending": "in sospeso", "friends": "amici", "Accept": "Accetta", "Decline": "Rifiuta", "PenPal archive": "Archivio PenPal", "Stay in each other's chapters.": "Restate nei capitoli l’uno dell’altra.", "New Issue": "Nuovo numero", "Start creating": "Inizia a creare", "Drafts": "Bozze", "Continue your unfinished issues": "Continua i numeri non finiti", "Sign up": "Registrati", "Log in": "Accedi", "Forgot password?": "Password dimenticata?", "Reset password": "Reimposta password", "Enter your email and we’ll send you a link to set a new password.": "Inserisci la tua email e ti invieremo un link per impostare una nuova password.", "Send reset email": "Invia email di reset", "Please enter a username.": "Inserisci un username.", "Passwords do not match.": "Le password non coincidono.", "Username must be at least 3 characters.": "L’username deve avere almeno 3 caratteri.", "Username too long.": "Username troppo lungo.", "This username is already taken.": "Questo username è già occupato.", "Delete": "Elimina", "Group": "Gruppo", "Group magazines": "Magazine del gruppo", "Year": "Anno", "Add group picture": "Aggiungi foto gruppo", "Leave group": "Lascia gruppo", "Delete group": "Elimina gruppo", "Leave group?": "Lasciare il gruppo?", "Leave": "Lascia", "You will no longer receive magazines from this group.": "Non riceverai più magazine da questo gruppo.", "Delete group?": "Eliminare gruppo?", "This permanently deletes the group for all members.": "Questo elimina definitivamente il gruppo per tutti i membri.", "Members": "Membri", "No members yet": "Ancora nessun membro", "Create group": "Crea gruppo", "Creating...": "Creazione...", "Group name": "Nome gruppo", "people · add or view members": "persone · aggiungi o vedi membri", "Member added.": "Membro aggiunto.", "Please enter a group name.": "Inserisci un nome gruppo.", "You already have a group with this name.": "Hai già un gruppo con questo nome.", "User not found.": "Utente non trovato.", "Already in group.": "Già nel gruppo.", "Saved Drafts": "Bozze salvate", "Draft": "Bozza", "Publish to": "Pubblica in", "Continue editing": "Continua a modificare", "Preview draft": "Anteprima bozza", "Publish draft": "Pubblica bozza", "No pages saved.": "Nessuna pagina salvata.", "Edit": "Modifica", "Preprint review": "Revisione anteprima", "Edit selected pages": "Modifica pagine selezionate", "Generated issue": "Numero generato", "No pages to edit.": "Nessuna pagina da modificare.", "Preview finished magazine": "Anteprima magazine finito", "Edit magazine": "Modifica magazine", "Finished magazine preview": "Anteprima magazine finito", "Edit this page": "Modifica questa pagina", "Delete page": "Elimina pagina", "Preview": "Anteprima", "Add sections or pages": "Aggiungi sezioni o pagine", "Add selected": "Aggiungi selezionati", "Finish issue": "Completa numero", "Publish to groups": "Pubblica nei gruppi", "Page": "Pagina", "of": "di"
    ]) { new, _ in new }.filter { !$0.value.isEmpty }

    private static let spanish: [String: String] = german.mapValues { _ in "" }.merging([
        "Settings": "Ajustes", "Language": "Idioma", "Privacy Policy": "Política de privacidad", "How your data is used": "Cómo se usan tus datos", "Sign out": "Cerrar sesión", "Delete profile permanently": "Eliminar perfil permanentemente", "Deleting account...": "Eliminando cuenta...", "Delete profile permanently?": "¿Eliminar perfil permanentemente?", "Delete everything": "Eliminar todo", "Cancel": "Cancelar", "This deletes your account, profile, drafts, published issues, friend connections and groups you own.": "Esto elimina tu cuenta, perfil, borradores, ediciones publicadas, amistades y grupos que posees.", "Confirm Password": "Confirmar contraseña", "Delete account permanently": "Eliminar cuenta permanentemente", "Incorrect password.": "Contraseña incorrecta.", "Profile": "Perfil", "Edit profile": "Editar perfil", "Change profile photo": "Cambiar foto de perfil", "Display name": "Nombre visible", "Save profile": "Guardar perfil", "Your name": "Tu nombre", "Username": "Usuario", "Password": "Contraseña", "Confirm password": "Confirmar contraseña", "Create Profile": "Crear perfil", "Please enter your email.": "Introduce tu email.", "Password reset email sent.": "Email de restablecimiento enviado.", "Profile saved.": "Perfil guardado.", "Friends": "Amigos", "My friends": "Mis amigos", "No friends yet.": "Aún no hay amigos.", "Remove": "Eliminar", "Remove friend?": "¿Eliminar amigo?", "You will no longer be connected.": "Ya no estarán conectados.", "Friend Requests": "Solicitudes de amistad", "Friend requests": "Solicitudes de amistad", "pending": "pendientes", "friends": "amigos", "Accept": "Aceptar", "Decline": "Rechazar", "PenPal archive": "Archivo PenPal", "Stay in each other's chapters.": "Permanezcan en sus capítulos.", "New Issue": "Nueva edición", "Start creating": "Empezar a crear", "Drafts": "Borradores", "Continue your unfinished issues": "Continúa tus ediciones sin terminar", "Sign up": "Registrarse", "Log in": "Iniciar sesión", "Forgot password?": "¿Olvidaste tu contraseña?", "Reset password": "Restablecer contraseña", "Enter your email and we’ll send you a link to set a new password.": "Introduce tu email y te enviaremos un enlace para crear una nueva contraseña.", "Send reset email": "Enviar email de restablecimiento", "Please enter a username.": "Introduce un usuario.", "Passwords do not match.": "Las contraseñas no coinciden.", "Username must be at least 3 characters.": "El usuario debe tener al menos 3 caracteres.", "Username too long.": "Usuario demasiado largo.", "This username is already taken.": "Este usuario ya está en uso.", "Delete": "Eliminar", "Group": "Grupo", "Group magazines": "Revistas del grupo", "Year": "Año", "Add group picture": "Añadir foto del grupo", "Leave group": "Salir del grupo", "Delete group": "Eliminar grupo", "Leave group?": "¿Salir del grupo?", "Leave": "Salir", "You will no longer receive magazines from this group.": "Ya no recibirás revistas de este grupo.", "Delete group?": "¿Eliminar grupo?", "This permanently deletes the group for all members.": "Esto elimina el grupo permanentemente para todos los miembros.", "Members": "Miembros", "No members yet": "Aún no hay miembros", "Create group": "Crear grupo", "Creating...": "Creando...", "Group name": "Nombre del grupo", "people · add or view members": "personas · añadir o ver miembros", "Member added.": "Miembro añadido.", "Please enter a group name.": "Introduce un nombre de grupo.", "You already have a group with this name.": "Ya tienes un grupo con este nombre.", "User not found.": "Usuario no encontrado.", "Already in group.": "Ya está en el grupo.", "Saved Drafts": "Borradores guardados", "Draft": "Borrador", "Publish to": "Publicar en", "Continue editing": "Seguir editando", "Preview draft": "Vista previa", "Publish draft": "Publicar borrador", "No pages saved.": "No hay páginas guardadas.", "Edit": "Editar", "Preprint review": "Revisión previa", "Edit selected pages": "Editar páginas seleccionadas", "Generated issue": "Edición generada", "No pages to edit.": "No hay páginas para editar.", "Preview finished magazine": "Vista previa de la revista", "Edit magazine": "Editar revista", "Finished magazine preview": "Vista previa final", "Edit this page": "Editar esta página", "Delete page": "Eliminar página", "Preview": "Vista previa", "Add sections or pages": "Añadir secciones o páginas", "Add selected": "Añadir selección", "Finish issue": "Finalizar edición", "Publish to groups": "Publicar en grupos", "Page": "Página", "of": "de"
    ]) { new, _ in new }.filter { !$0.value.isEmpty }

    private static let french: [String: String] = german.mapValues { _ in "" }.merging([
        "Settings": "Réglages", "Language": "Langue", "Privacy Policy": "Politique de confidentialité", "How your data is used": "Comment tes données sont utilisées", "Sign out": "Se déconnecter", "Delete profile permanently": "Supprimer le profil définitivement", "Deleting account...": "Suppression du compte...", "Delete profile permanently?": "Supprimer le profil définitivement ?", "Delete everything": "Tout supprimer", "Cancel": "Annuler", "This deletes your account, profile, drafts, published issues, friend connections and groups you own.": "Cela supprime ton compte, ton profil, tes brouillons, tes numéros publiés, tes amitiés et les groupes que tu possèdes.", "Confirm Password": "Confirmer le mot de passe", "Delete account permanently": "Supprimer le compte définitivement", "Incorrect password.": "Mot de passe incorrect.", "Profile": "Profil", "Edit profile": "Modifier le profil", "Change profile photo": "Changer la photo de profil", "Display name": "Nom affiché", "Save profile": "Enregistrer le profil", "Your name": "Ton nom", "Username": "Nom d’utilisateur", "Password": "Mot de passe", "Confirm password": "Confirmer le mot de passe", "Create Profile": "Créer le profil", "Please enter your email.": "Entre ton e-mail.", "Password reset email sent.": "E-mail de réinitialisation envoyé.", "Profile saved.": "Profil enregistré.", "Friends": "Amis", "My friends": "Mes amis", "No friends yet.": "Pas encore d’amis.", "Remove": "Retirer", "Remove friend?": "Retirer cet ami ?", "You will no longer be connected.": "Vous ne serez plus connectés.", "Friend Requests": "Demandes d’amis", "Friend requests": "Demandes d’amis", "pending": "en attente", "friends": "amis", "Accept": "Accepter", "Decline": "Refuser", "PenPal archive": "Archive PenPal", "Stay in each other's chapters.": "Restez dans les chapitres l’un de l’autre.", "New Issue": "Nouveau numéro", "Start creating": "Commencer", "Drafts": "Brouillons", "Continue your unfinished issues": "Continue tes numéros inachevés", "Sign up": "S’inscrire", "Log in": "Se connecter", "Forgot password?": "Mot de passe oublié ?", "Reset password": "Réinitialiser le mot de passe", "Enter your email and we’ll send you a link to set a new password.": "Entre ton e-mail et nous t’enverrons un lien pour créer un nouveau mot de passe.", "Send reset email": "Envoyer l’e-mail", "Please enter a username.": "Entre un nom d’utilisateur.", "Passwords do not match.": "Les mots de passe ne correspondent pas.", "Username must be at least 3 characters.": "Le nom d’utilisateur doit avoir au moins 3 caractères.", "Username too long.": "Nom d’utilisateur trop long.", "This username is already taken.": "Ce nom d’utilisateur est déjà pris.", "Delete": "Supprimer", "Group": "Groupe", "Group magazines": "Magazines du groupe", "Year": "Année", "Add group picture": "Ajouter une photo de groupe", "Leave group": "Quitter le groupe", "Delete group": "Supprimer le groupe", "Leave group?": "Quitter le groupe ?", "Leave": "Quitter", "You will no longer receive magazines from this group.": "Tu ne recevras plus les magazines de ce groupe.", "Delete group?": "Supprimer le groupe ?", "This permanently deletes the group for all members.": "Cela supprime définitivement le groupe pour tous les membres.", "Members": "Membres", "No members yet": "Aucun membre pour l’instant", "Create group": "Créer un groupe", "Creating...": "Création...", "Group name": "Nom du groupe", "people · add or view members": "personnes · ajouter ou voir les membres", "Member added.": "Membre ajouté.", "Please enter a group name.": "Entre un nom de groupe.", "You already have a group with this name.": "Tu as déjà un groupe avec ce nom.", "User not found.": "Utilisateur introuvable.", "Already in group.": "Déjà dans le groupe.", "Saved Drafts": "Brouillons enregistrés", "Draft": "Brouillon", "Publish to": "Publier dans", "Continue editing": "Continuer l’édition", "Preview draft": "Aperçu du brouillon", "Publish draft": "Publier le brouillon", "No pages saved.": "Aucune page enregistrée.", "Edit": "Modifier", "Preprint review": "Révision avant impression", "Edit selected pages": "Modifier les pages choisies", "Generated issue": "Numéro généré", "No pages to edit.": "Aucune page à modifier.", "Preview finished magazine": "Aperçu du magazine final", "Edit magazine": "Modifier le magazine", "Finished magazine preview": "Aperçu final", "Edit this page": "Modifier cette page", "Delete page": "Supprimer la page", "Preview": "Aperçu", "Add sections or pages": "Ajouter des sections ou pages", "Add selected": "Ajouter la sélection", "Finish issue": "Terminer le numéro", "Publish to groups": "Publier dans les groupes", "Page": "Page", "of": "sur"
    ]) { new, _ in new }.filter { !$0.value.isEmpty }

    private static let germanExtras = [
        "Privacy": "Datenschutz",
        "PenPal user": "PenPal-Nutzer",
        "Back": "Zurück",
        "Enabled": "Aktiviert",
        "Disabled": "Deaktiviert",
        "Not Determined": "Noch nicht festgelegt",
        "Margin note notifications": "Randnotiz-Benachrichtigungen",
        "Notify me when someone leaves a note.": "Benachrichtige mich, wenn jemand eine Notiz hinterlässt.",
        "PenPal Lab": "PenPal Lab",
        "Help shape the future of PenPal": "Gestalte die Zukunft von PenPal mit",
        "Development Preview": "Entwicklungsvorschau",
        "Suggest an idea": "Idee vorschlagen",
        "What should PenPal do next?": "Was soll PenPal als Nächstes können?",
        "Suggestions may be visible to other Founder Supporters.": "Vorschläge können für andere Founder Supporter sichtbar sein.",
        "Submit suggestion": "Vorschlag einreichen",
        "Submitting...": "Wird eingereicht...",
        "Most supported": "Meist unterstützt",
        "Newest": "Neueste",
        "Sort suggestions": "Vorschläge sortieren",
        "Under review": "In Prüfung",
        "Planned": "Geplant",
        "In progress": "In Arbeit",
        "Released": "Veröffentlicht",
        "Not planned": "Nicht geplant",
        "I want this too": "Das möchte ich auch",
        "Vote removed": "Stimme entfernt",
        "Thanks for helping shape PenPal": "Danke, dass du PenPal mitgestaltest",
        "Roadmap": "Roadmap",
        "No roadmap items yet.": "Noch keine Roadmap-Einträge.",
        "Suggestions": "Vorschläge",
        "No suggestions yet.": "Noch keine Vorschläge.",
        "PenPal Lab is only available to Founder Supporters.": "PenPal Lab ist nur für Founder Supporter verfügbar.",
        "This area is not available for your account right now.": "Dieser Bereich ist für dein Konto gerade nicht verfügbar.",
        "Title": "Titel",
        "Description": "Beschreibung",
        "Category": "Kategorie",
        "Feature": "Funktion",
        "Design": "Design",
        "Magazine page": "Magazinseite",
        "Bug": "Fehler",
        "Other": "Sonstiges",
        "Founder": "Founder",
        "Founder Supporter": "Founder Supporter",
        "Choose what PenPal can notify you about.": "Wähle aus, worüber PenPal dich benachrichtigen darf.",
        "iPhone notifications": "iPhone-Benachrichtigungen",
        "Notifications are disabled in iPhone Settings.": "Benachrichtigungen sind in den iPhone-Einstellungen deaktiviert.",
        "Open iPhone Settings": "iPhone-Einstellungen öffnen",
        "Open Settings": "Einstellungen öffnen",
        "Allow PenPal notifications": "PenPal-Benachrichtigungen erlauben",
        "Tap to allow iPhone notifications for PenPal.": "Tippe, um iPhone-Benachrichtigungen für PenPal zu erlauben.",
        "Manage iPhone notification delivery in Settings.": "Verwalte die Zustellung von iPhone-Benachrichtigungen in den Einstellungen.",
        "Covers friend requests, groups, magazines, activity, margin notes and PenPal announcements.": "Gilt für Freundschaftsanfragen, Gruppen, Magazine, Aktivitäten, Randnotizen und PenPal-Ankündigungen.",
        "Enable notifications in iPhone Settings to receive PenPal notifications.": "Aktiviere Benachrichtigungen in den iPhone-Einstellungen, um PenPal-Benachrichtigungen zu erhalten.",
        "Friend requests and new friends": "Freundschaftsanfragen und neue Freunde",
        "Group invitations and group updates": "Gruppeneinladungen und Gruppenupdates",
        "New magazines": "Neue Magazine",
        "Magazine activity": "Magazinaktivität",
        "Margin notes": "Randnotizen",
        "Replies and reactions": "Antworten und Reaktionen",
        "PenPal announcements": "PenPal-Ankündigungen",
        "Notification preferences saved.": "Benachrichtigungseinstellungen gespeichert.",
        "Saving...": "Wird gespeichert...",
        "Your PenPal Plan": "Dein PenPal-Plan",
        "Upgrade or change plan": "Plan upgraden oder ändern",
        "Compare plans": "Pläne vergleichen",
        "Restore purchases": "Käufe wiederherstellen",
        "About PenPal": "Über PenPal",
        "More PenPal options": "Weitere PenPal-Optionen",
        "Free": "Kostenlos",
        "Pro": "Pro",
        "Premium": "Premium",
        "Included features": "Enthaltene Funktionen",
        "Create magazines, save drafts, publish to groups and collect your memories in PenPal.": "Erstelle Magazine, speichere Entwürfe, veröffentliche in Gruppen und sammle deine Erinnerungen in PenPal.",
        "Renewal information": "Verlängerungsinformationen",
        "No renewal information is available yet.": "Noch keine Verlängerungsinformationen verfügbar.",
        "Manage subscription": "Abo verwalten",
        "A quieter place for shared monthly magazines.": "Ein ruhigerer Ort für gemeinsame Monatsmagazine.",
        "Founder Supporter Hub": "Founder Supporter Hub",
        "Submit feedback": "Feedback senden",
        "Voting and roadmap": "Abstimmung und Roadmap",
        "Founder benefits": "Founder-Vorteile",
        "Founder badge": "Founder-Abzeichen",
        "Current plan": "Aktueller Plan",
        "Continue": "Weiter",
        "Purchases restored.": "Käufe wiederhergestellt.",
        "Purchases could not be restored right now.": "Käufe können gerade nicht wiederhergestellt werden.",
        "Subscriptions are not available in this development build yet.": "Abos sind in diesem Entwicklungsbuild noch nicht verfügbar.",
        "Create magazines, save drafts and share with your groups.": "Erstelle Magazine, speichere Entwürfe und teile sie mit deinen Gruppen.",
        "Extra creative tools and more room to shape each issue.": "Zusätzliche Kreativwerkzeuge und mehr Raum, jede Ausgabe zu gestalten.",
        "The fullest PenPal experience for frequent magazine makers.": "Das umfassendste PenPal-Erlebnis für alle, die regelmäßig Magazine erstellen.",
        "Includes PenPal Lab, voting, roadmap previews and the Founder badge.": "Enthält PenPal Lab, Abstimmungen, Roadmap-Vorschauen und das Founder-Abzeichen.",
        "Ideas and voting": "Ideen und Abstimmung",
        "Early access to PenPal Lab experiments.": "Früher Zugang zu PenPal-Lab-Experimenten.",
        "Vote on ideas and help shape the roadmap.": "Stimme über Ideen ab und gestalte die Roadmap mit.",
        "A subtle Founder badge inside PenPal Lab.": "Ein dezentes Founder-Abzeichen im PenPal Lab.",
        "PenPal Lab is included with Founder Supporter.": "PenPal Lab ist in Founder Supporter enthalten.",
        "Upgrade to unlock ideas, voting, feedback and the roadmap.": "Upgrade, um Ideen, Abstimmungen, Feedback und die Roadmap freizuschalten.",
        "Shape upcoming ideas, vote on suggestions and follow what is planned.": "Gestalte kommende Ideen mit, stimme über Vorschläge ab und verfolge, was geplant ist.",
        "Share thoughtful product ideas with the PenPal team.": "Teile durchdachte Produktideen mit dem PenPal-Team.",
        "Support ideas and see what is planned, in progress or released.": "Unterstütze Ideen und sieh, was geplant, in Arbeit oder veröffentlicht ist.",
        "See what Founder Supporter unlocks as PenPal grows.": "Sieh, was Founder Supporter freischaltet, während PenPal wächst.",
        "A subtle mark for early supporters inside PenPal Lab.": "Ein dezentes Zeichen für frühe Unterstützer im PenPal Lab.",
        "You need to be logged in.": "Du musst angemeldet sein.",
        "Please add a title.": "Bitte füge einen Titel hinzu.",
        "Please add a description.": "Bitte füge eine Beschreibung hinzu.",
        "Please keep your suggestion a little shorter.": "Bitte halte deinen Vorschlag etwas kürzer.",
        "1 issue": "1 Ausgabe",
        "issues": "Ausgaben",
        "photo": "Foto",
        "write here…": "hier schreiben…"
    ]

    private static let italianExtras = [
        "Privacy": "Privacy",
        "PenPal user": "Utente PenPal",
        "Back": "Indietro",
        "Enabled": "Attive",
        "Disabled": "Disattivate",
        "Not Determined": "Non ancora deciso",
        "Margin note notifications": "Notifiche delle note a margine",
        "Notify me when someone leaves a note.": "Avvisami quando qualcuno lascia una nota.",
        "PenPal Lab": "PenPal Lab",
        "Help shape the future of PenPal": "Aiuta a immaginare il futuro di PenPal",
        "Development Preview": "Anteprima di sviluppo",
        "Suggest an idea": "Proponi un'idea",
        "What should PenPal do next?": "Cosa dovrebbe fare PenPal adesso?",
        "Suggestions may be visible to other Founder Supporters.": "I suggerimenti possono essere visibili ad altri Founder Supporter.",
        "Submit suggestion": "Invia suggerimento",
        "Submitting...": "Invio...",
        "Most supported": "Più sostenute",
        "Newest": "Più recenti",
        "Sort suggestions": "Ordina suggerimenti",
        "Under review": "In revisione",
        "Planned": "Pianificato",
        "In progress": "In corso",
        "Released": "Pubblicato",
        "Not planned": "Non previsto",
        "I want this too": "Lo vorrei anch'io",
        "Vote removed": "Voto rimosso",
        "Thanks for helping shape PenPal": "Grazie per aiutare PenPal a crescere",
        "Roadmap": "Roadmap",
        "No roadmap items yet.": "Ancora nessun elemento nella roadmap.",
        "Suggestions": "Suggerimenti",
        "No suggestions yet.": "Ancora nessun suggerimento.",
        "PenPal Lab is only available to Founder Supporters.": "PenPal Lab è disponibile solo per i Founder Supporter.",
        "This area is not available for your account right now.": "Quest'area non è disponibile per il tuo account.",
        "Title": "Titolo",
        "Description": "Descrizione",
        "Category": "Categoria",
        "Feature": "Funzione",
        "Design": "Design",
        "Magazine page": "Pagina del magazine",
        "Bug": "Errore",
        "Other": "Altro",
        "Founder": "Founder",
        "Founder Supporter": "Founder Supporter",
        "Choose what PenPal can notify you about.": "Scegli per cosa PenPal può inviarti notifiche.",
        "iPhone notifications": "Notifiche iPhone",
        "Notifications are disabled in iPhone Settings.": "Le notifiche sono disattivate nelle Impostazioni iPhone.",
        "Open iPhone Settings": "Apri Impostazioni iPhone",
        "Open Settings": "Apri Impostazioni",
        "Allow PenPal notifications": "Consenti notifiche PenPal",
        "Tap to allow iPhone notifications for PenPal.": "Tocca per consentire le notifiche iPhone per PenPal.",
        "Manage iPhone notification delivery in Settings.": "Gestisci la consegna delle notifiche iPhone nelle Impostazioni.",
        "Covers friend requests, groups, magazines, activity, margin notes and PenPal announcements.": "Include richieste di amicizia, gruppi, riviste, attività, note a margine e novità da PenPal.",
        "Enable notifications in iPhone Settings to receive PenPal notifications.": "Attiva le notifiche nelle Impostazioni iPhone per ricevere notifiche da PenPal.",
        "Friend requests and new friends": "Richieste di amicizia e nuovi amici",
        "Group invitations and group updates": "Inviti e aggiornamenti dei gruppi",
        "New magazines": "Nuove riviste",
        "Magazine activity": "Attività delle riviste",
        "Margin notes": "Note a margine",
        "Replies and reactions": "Risposte e reazioni",
        "PenPal announcements": "Novità da PenPal",
        "Notification preferences saved.": "Preferenze notifiche salvate.",
        "Saving...": "Salvataggio...",
        "Your PenPal Plan": "Il tuo piano PenPal",
        "Upgrade or change plan": "Aggiorna o cambia piano",
        "Compare plans": "Confronta i piani",
        "Restore purchases": "Ripristina acquisti",
        "About PenPal": "Informazioni su PenPal",
        "More PenPal options": "Altre opzioni PenPal",
        "Free": "Gratis",
        "Pro": "Pro",
        "Premium": "Premium",
        "Included features": "Funzioni incluse",
        "Create magazines, save drafts, publish to groups and collect your memories in PenPal.": "Crea riviste, salva bozze, pubblica nei gruppi e raccogli i tuoi ricordi in PenPal.",
        "Renewal information": "Informazioni sul rinnovo",
        "No renewal information is available yet.": "Non sono ancora disponibili informazioni sul rinnovo.",
        "Manage subscription": "Gestisci abbonamento",
        "A quieter place for shared monthly magazines.": "Uno spazio più tranquillo per riviste mensili condivise.",
        "Founder Supporter Hub": "Hub Founder Supporter",
        "Submit feedback": "Invia feedback",
        "Voting and roadmap": "Voti e roadmap",
        "Founder benefits": "Vantaggi Founder",
        "Founder badge": "Badge Founder",
        "Current plan": "Piano attuale",
        "Continue": "Continua",
        "Purchases restored.": "Acquisti ripristinati.",
        "Purchases could not be restored right now.": "Al momento non è possibile ripristinare gli acquisti.",
        "Subscriptions are not available in this development build yet.": "Gli abbonamenti non sono ancora disponibili in questa build di sviluppo.",
        "Create magazines, save drafts and share with your groups.": "Crea riviste, salva bozze e condividile con i tuoi gruppi.",
        "Extra creative tools and more room to shape each issue.": "Strumenti creativi extra e più spazio per dare forma a ogni numero.",
        "The fullest PenPal experience for frequent magazine makers.": "L’esperienza PenPal più completa per chi crea riviste spesso.",
        "Includes PenPal Lab, voting, roadmap previews and the Founder badge.": "Include PenPal Lab, votazioni, anteprime della roadmap e il badge Founder.",
        "Ideas and voting": "Idee e votazioni",
        "Early access to PenPal Lab experiments.": "Accesso anticipato agli esperimenti di PenPal Lab.",
        "Vote on ideas and help shape the roadmap.": "Vota le idee e contribuisci alla roadmap.",
        "A subtle Founder badge inside PenPal Lab.": "Un badge Founder discreto dentro PenPal Lab.",
        "PenPal Lab is included with Founder Supporter.": "PenPal Lab è incluso con Founder Supporter.",
        "Upgrade to unlock ideas, voting, feedback and the roadmap.": "Fai l’upgrade per sbloccare idee, votazioni, feedback e roadmap.",
        "Shape upcoming ideas, vote on suggestions and follow what is planned.": "Contribuisci alle prossime idee, vota i suggerimenti e segui ciò che è in programma.",
        "Share thoughtful product ideas with the PenPal team.": "Condividi idee di prodotto curate con il team PenPal.",
        "Support ideas and see what is planned, in progress or released.": "Sostieni le idee e scopri cosa è pianificato, in corso o pubblicato.",
        "See what Founder Supporter unlocks as PenPal grows.": "Scopri cosa sblocca Founder Supporter mentre PenPal cresce.",
        "A subtle mark for early supporters inside PenPal Lab.": "Un segno discreto per i primi sostenitori dentro PenPal Lab.",
        "You need to be logged in.": "Devi effettuare l'accesso.",
        "Please add a title.": "Aggiungi un titolo.",
        "Please add a description.": "Aggiungi una descrizione.",
        "Please keep your suggestion a little shorter.": "Rendi il suggerimento un po' più breve.",
        "Settings": "Impostazioni",
        "Language": "Lingua",
        "Privacy Policy": "Informativa sulla privacy",
        "How your data is used": "Come usiamo i tuoi dati",
        "Sign out": "Esci",
        "Delete profile permanently": "Elimina il profilo definitivamente",
        "Deleting account...": "Eliminazione dell'account...",
        "Delete profile permanently?": "Vuoi eliminare il profilo definitivamente?",
        "Delete everything": "Elimina tutto",
        "Cancel": "Annulla",
        "Confirm Password": "Conferma password",
        "Password": "Password",
        "Delete account permanently": "Elimina account definitivamente",
        "Incorrect password.": "Password non corretta.",
        "Profile": "Profilo",
        "Edit profile": "Modifica profilo",
        "Change profile photo": "Cambia foto profilo",
        "Display name": "Nome visualizzato",
        "Save profile": "Salva profilo",
        "Your name": "Il tuo nome",
        "Username": "Nome utente",
        "Confirm password": "Conferma password",
        "Create Profile": "Crea profilo",
        "Please enter your email.": "Inserisci la tua email.",
        "Password reset email sent.": "Email per reimpostare la password inviata.",
        "Profile saved.": "Profilo salvato.",
        "Friends": "Amici",
        "My friends": "I miei amici",
        "No friends yet.": "Ancora nessun amico.",
        "Remove": "Rimuovi",
        "Remove friend?": "Rimuovere questo amico?",
        "You will no longer be connected.": "Non sarete più collegati.",
        "Friend Requests": "Richieste di amicizia",
        "Friend requests": "Richieste di amicizia",
        "pending": "in sospeso",
        "friends": "amici",
        "Accept": "Accetta",
        "Decline": "Rifiuta",
        "PenPal archive": "Archivio PenPal",
        "Stay in each other's chapters.": "Resta parte delle storie dei tuoi amici.",
        "Sign up": "Registrati",
        "Log in": "Accedi",
        "Forgot password?": "Password dimenticata?",
        "Reset password": "Reimposta password",
        "Enter your email and we’ll send you a link to set a new password.": "Inserisci la tua email e ti manderemo un link per creare una nuova password.",
        "Send reset email": "Invia email di reimpostazione",
        "Please enter a username.": "Inserisci un nome utente.",
        "Passwords do not match.": "Le password non coincidono.",
        "Username must be at least 3 characters.": "Il nome utente deve avere almeno 3 caratteri.",
        "Username too long.": "Nome utente troppo lungo.",
        "This username is already taken.": "Questo nome utente è già occupato.",
        "Delete": "Elimina",
        "Group": "Gruppo",
        "Year": "Anno",
        "Add group picture": "Aggiungi foto del gruppo",
        "Leave group": "Lascia il gruppo",
        "Delete group": "Elimina gruppo",
        "Leave group?": "Vuoi lasciare il gruppo?",
        "Leave": "Lascia",
        "Delete group?": "Eliminare il gruppo?",
        "This permanently deletes the group for all members.": "Questo elimina il gruppo definitivamente per tutti i membri.",
        "Members": "Membri",
        "No members yet": "Ancora nessun membro",
        "Create group": "Crea gruppo",
        "Creating...": "Creazione...",
        "Group name": "Nome del gruppo",
        "people · add or view members": "persone · aggiungi o vedi membri",
        "Member added.": "Membro aggiunto.",
        "Please enter a group name.": "Inserisci un nome per il gruppo.",
        "You already have a group with this name.": "Hai già un gruppo con questo nome.",
        "User not found.": "Utente non trovato.",
        "Already in group.": "Già nel gruppo.",
        "This deletes your account, profile, drafts, published issues, friend connections and groups you own.": "Questo elimina account, profilo, bozze, giornali pubblicati, amicizie e gruppi che possiedi.",
        "New Issue": "Nuovo giornale",
        "Continue your unfinished issues": "Continua i giornali non finiti",
        "Generated issue": "Giornale generato",
        "Preview finished magazine": "Anteprima giornale finito",
        "Edit magazine": "Modifica giornale",
        "Finished magazine preview": "Anteprima giornale finito",
        "Finish issue": "Completa giornale",
        "Group magazines": "Giornali del gruppo",
        "You will no longer receive magazines from this group.": "Non riceverai più giornali da questo gruppo.",
        "1 issue": "1 giornale",
        "issues": "giornali",
        "photo": "foto",
        "write here…": "scrivi qui…",
        "No throwbacks yet — published issues will appear here.": "Ancora niente pubblicato - i giornali pubblicati appariranno qui.",
        "Throwback": "Ricordi",
        "Delete issue?": "Eliminare il giornale?",
        "This issue will be permanently removed.": "Questo giornale verrà eliminato definitivamente.",
        "No drafts yet — start your first issue and save it here.": "Ancora nessuna bozza - inizia il tuo primo giornale e salvalo qui.",
        "Saved Drafts": "Bozze salvate",
        "Delete draft?": "Eliminare la bozza?",
        "This draft will be permanently removed.": "Questa bozza verrà eliminata definitivamente.",
        "Draft": "Bozza",
        "Drafts": "Bozze",
        "Publish to": "Pubblica in",
        "Continue editing": "Continua a modificare",
        "Preview draft": "Anteprima bozza",
        "Publish draft": "Pubblica bozza",
        "This draft has no pages to publish.": "Questa bozza non ha pagine da pubblicare.",
        "Loading draft...": "Caricamento bozza...",
        "This draft has no editable pages.": "Questa bozza non ha pagine modificabili.",
        "This draft is still loading or has no editable pages.": "Questa bozza sta ancora caricando o non ha pagine modificabili.",
        "No pages saved.": "Nessuna pagina salvata.",
        "Page": "Pagina",
        "of": "di",
        "Edit": "Modifica",
        "No magazines published this month yet.": "Nessun giornale pubblicato questo mese.",
        "Preprint review": "Revisione prima della stampa",
        "Delete any page you do not want. The layout is locked to the PowerPoint template. Text boxes can be written in; photo boxes keep their size and only the photo inside can be zoomed or moved.": "Elimina le pagine che non vuoi. Il layout resta bloccato al modello PowerPoint. Puoi scrivere nei campi di testo; i riquadri foto mantengono la dimensione e solo la foto dentro puo essere ingrandita o spostata.",
        "Delete any pages you don't want to include. Magazines can contain up to 30 pages.": "Elimina le pagine che non vuoi includere. I giornali possono contenere fino a 30 pagine.",
        "Edit selected pages": "Modifica le pagine selezionate",
        "No pages to edit.": "Nessuna pagina da modificare.",
        "Edit this page": "Modifica questa pagina",
        "Delete page": "Elimina pagina",
        "No pages to preview.": "Nessuna pagina da vedere in anteprima.",
        "Preview": "Anteprima",
        "Add sections or pages": "Aggiungi capitoli o pagine",
        "All sections are already in this issue.": "Tutte le sezioni sono gia in questo giornale.",
        "Add selected": "Aggiungi selezionati",
        "Publish to groups": "Pubblica nei gruppi",
        "You are not in any groups yet.": "Non sei ancora in nessun gruppo.",
        "Sections added. Save the draft to keep these changes.": "Sezioni aggiunte. Salva la bozza per mantenere le modifiche.",
        "Page deleted. Save the draft to keep this change.": "Pagina eliminata. Salva la bozza per mantenere la modifica.",
        "Create at least one page first.": "Crea prima almeno una pagina.",
        "Draft could not be prepared for saving.": "Non e stato possibile preparare la bozza per il salvataggio.",
        "Draft could not be saved:": "Impossibile salvare la bozza:",
        "Draft saved. You can find it in Drafts.": "Bozza salvata. La trovi in Bozze.",
        "Select at least one group.": "Seleziona almeno un gruppo.",
        "An issue can contain up to 30 pages.": "Un giornale puo contenere fino a 30 pagine.",
        "Your magazine has more than 30 pages. Delete pages before publishing.": "Il tuo giornale ha più di 30 pagine. Elimina alcune pagine prima di pubblicare.",
        "Your issue has too many photos. Please keep it under 50 photos.": "Il tuo giornale ha troppe foto. Tienilo sotto le 50 foto.",
        "Issue published. You can find it in old magazines.": "Giornale pubblicato. Lo trovi nei vecchi giornali.",
        "Issue could not be published:": "Impossibile pubblicare il giornale:",
        "Saving...": "Salvataggio...",
        "Save for later": "Salva per dopo",
        "Save Draft": "Salva bozza",
        "Continue Draft": "Continua bozza",
        "Load Draft": "Carica bozza",
        "Local Draft": "Bozza locale",
        "Draft saved locally.": "Bozza salvata sul dispositivo.",
        "Continue editing your saved local draft": "Continua a modificare la bozza salvata sul dispositivo",
        "Local draft could not be loaded:": "Impossibile caricare la bozza locale:",
        "Publishing...": "Pubblicazione...",
        "Publish selected groups": "Pubblica nei gruppi selezionati",
        "slide to track progress": "scorri per segnare il progresso",
        "swipe to review": "scorri per recensire"
    ]

    private static let spanishExtras = [
        "Privacy": "Privacidad",
        "PenPal user": "Usuario PenPal",
        "Back": "Atrás",
        "Enabled": "Activadas",
        "Disabled": "Desactivadas",
        "Not Determined": "Sin decidir",
        "Margin note notifications": "Notificaciones de notas al margen",
        "Notify me when someone leaves a note.": "Avísame cuando alguien deje una nota.",
        "PenPal Lab": "PenPal Lab",
        "Help shape the future of PenPal": "Ayuda a dar forma al futuro de PenPal",
        "Development Preview": "Vista previa de desarrollo",
        "Suggest an idea": "Sugerir una idea",
        "What should PenPal do next?": "¿Qué debería hacer PenPal ahora?",
        "Suggestions may be visible to other Founder Supporters.": "Las sugerencias pueden ser visibles para otros Founder Supporters.",
        "Submit suggestion": "Enviar sugerencia",
        "Submitting...": "Enviando...",
        "Most supported": "Más apoyadas",
        "Newest": "Más recientes",
        "Sort suggestions": "Ordenar sugerencias",
        "Under review": "En revisión",
        "Planned": "Planeado",
        "In progress": "En progreso",
        "Released": "Publicado",
        "Not planned": "No planeado",
        "I want this too": "Yo también lo quiero",
        "Vote removed": "Voto retirado",
        "Thanks for helping shape PenPal": "Gracias por ayudar a dar forma a PenPal",
        "Roadmap": "Hoja de ruta",
        "No roadmap items yet.": "Aún no hay elementos en la hoja de ruta.",
        "Suggestions": "Sugerencias",
        "No suggestions yet.": "Aún no hay sugerencias.",
        "PenPal Lab is only available to Founder Supporters.": "PenPal Lab solo está disponible para Founder Supporters.",
        "This area is not available for your account right now.": "Esta área no está disponible para tu cuenta ahora mismo.",
        "Title": "Título",
        "Description": "Descripción",
        "Category": "Categoría",
        "Feature": "Función",
        "Design": "Diseño",
        "Magazine page": "Página de revista",
        "Bug": "Error",
        "Other": "Otro",
        "Founder": "Founder",
        "Founder Supporter": "Founder Supporter",
        "Choose what PenPal can notify you about.": "Elige sobre qué puede avisarte PenPal.",
        "iPhone notifications": "Notificaciones del iPhone",
        "Notifications are disabled in iPhone Settings.": "Las notificaciones están desactivadas en los Ajustes del iPhone.",
        "Open iPhone Settings": "Abrir Ajustes del iPhone",
        "Open Settings": "Abrir Ajustes",
        "Allow PenPal notifications": "Permitir notificaciones de PenPal",
        "Tap to allow iPhone notifications for PenPal.": "Toca para permitir las notificaciones del iPhone para PenPal.",
        "Manage iPhone notification delivery in Settings.": "Gestiona la entrega de notificaciones del iPhone en Ajustes.",
        "Covers friend requests, groups, magazines, activity, margin notes and PenPal announcements.": "Incluye solicitudes de amistad, grupos, revistas, actividad, notas al margen y novedades de PenPal.",
        "Enable notifications in iPhone Settings to receive PenPal notifications.": "Activa las notificaciones en los Ajustes del iPhone para recibir notificaciones de PenPal.",
        "Friend requests and new friends": "Solicitudes de amistad y nuevos amigos",
        "Group invitations and group updates": "Invitaciones y novedades de grupos",
        "New magazines": "Nuevas revistas",
        "Magazine activity": "Actividad de revistas",
        "Margin notes": "Notas al margen",
        "Replies and reactions": "Respuestas y reacciones",
        "PenPal announcements": "Novedades de PenPal",
        "Notification preferences saved.": "Preferencias de notificaciones guardadas.",
        "Saving...": "Guardando...",
        "Your PenPal Plan": "Tu plan de PenPal",
        "Upgrade or change plan": "Mejorar o cambiar plan",
        "Compare plans": "Comparar planes",
        "Restore purchases": "Restaurar compras",
        "About PenPal": "Acerca de PenPal",
        "More PenPal options": "Más opciones de PenPal",
        "Free": "Gratis",
        "Pro": "Pro",
        "Premium": "Premium",
        "Included features": "Funciones incluidas",
        "Create magazines, save drafts, publish to groups and collect your memories in PenPal.": "Crea revistas, guarda borradores, publica en grupos y reúne tus recuerdos en PenPal.",
        "Renewal information": "Información de renovación",
        "No renewal information is available yet.": "Aún no hay información de renovación disponible.",
        "Manage subscription": "Gestionar suscripción",
        "A quieter place for shared monthly magazines.": "Un lugar más tranquilo para revistas mensuales compartidas.",
        "Founder Supporter Hub": "Centro Founder Supporter",
        "Submit feedback": "Enviar comentarios",
        "Voting and roadmap": "Votaciones y hoja de ruta",
        "Founder benefits": "Ventajas Founder",
        "Founder badge": "Insignia Founder",
        "Current plan": "Plan actual",
        "Continue": "Continuar",
        "Purchases restored.": "Compras restauradas.",
        "Purchases could not be restored right now.": "No se han podido restaurar las compras ahora mismo.",
        "Subscriptions are not available in this development build yet.": "Las suscripciones aún no están disponibles en esta versión de desarrollo.",
        "Create magazines, save drafts and share with your groups.": "Crea revistas, guarda borradores y compártelos con tus grupos.",
        "Extra creative tools and more room to shape each issue.": "Más herramientas creativas y más espacio para dar forma a cada edición.",
        "The fullest PenPal experience for frequent magazine makers.": "La experiencia PenPal más completa para quienes crean revistas con frecuencia.",
        "Includes PenPal Lab, voting, roadmap previews and the Founder badge.": "Incluye PenPal Lab, votaciones, avances de la hoja de ruta y la insignia Founder.",
        "Ideas and voting": "Ideas y votaciones",
        "Early access to PenPal Lab experiments.": "Acceso anticipado a experimentos de PenPal Lab.",
        "Vote on ideas and help shape the roadmap.": "Vota ideas y ayuda a dar forma a la hoja de ruta.",
        "A subtle Founder badge inside PenPal Lab.": "Una insignia Founder sutil dentro de PenPal Lab.",
        "PenPal Lab is included with Founder Supporter.": "PenPal Lab está incluido con Founder Supporter.",
        "Upgrade to unlock ideas, voting, feedback and the roadmap.": "Mejora tu plan para desbloquear ideas, votaciones, comentarios y la hoja de ruta.",
        "Shape upcoming ideas, vote on suggestions and follow what is planned.": "Da forma a próximas ideas, vota sugerencias y sigue lo que está previsto.",
        "Share thoughtful product ideas with the PenPal team.": "Comparte ideas cuidadas sobre el producto con el equipo de PenPal.",
        "Support ideas and see what is planned, in progress or released.": "Apoya ideas y consulta qué está previsto, en progreso o publicado.",
        "See what Founder Supporter unlocks as PenPal grows.": "Descubre qué desbloquea Founder Supporter a medida que PenPal crece.",
        "A subtle mark for early supporters inside PenPal Lab.": "Una marca sutil para quienes apoyaron PenPal desde el principio dentro de PenPal Lab.",
        "You need to be logged in.": "Debes iniciar sesión.",
        "Please add a title.": "Añade un título.",
        "Please add a description.": "Añade una descripción.",
        "Please keep your suggestion a little shorter.": "Haz tu sugerencia un poco más breve.",
        "Settings": "Ajustes",
        "Language": "Idioma",
        "Privacy Policy": "Política de privacidad",
        "How your data is used": "Cómo usamos tus datos",
        "Sign out": "Cerrar sesión",
        "Delete profile permanently": "Eliminar perfil permanentemente",
        "Deleting account...": "Eliminando cuenta...",
        "Delete profile permanently?": "Eliminar perfil",
        "Delete everything": "Eliminar permanentemente",
        "Cancel": "Cancelar",
        "This deletes your account, profile, drafts, published issues, friend connections and groups you own.": "Esta acción eliminará permanentemente tu perfil y no se puede deshacer.",
        "Account settings": "Configuración de la cuenta",
        "Email": "Correo electrónico",
        "Notifications": "Notificaciones",
        "Confirm Password": "Confirmar contraseña",
        "Password": "Contraseña",
        "Delete account permanently": "Eliminar permanentemente",
        "Incorrect password.": "Contraseña incorrecta.",
        "Profile": "Perfil",
        "Edit profile": "Editar perfil",
        "Change profile photo": "Cambiar foto de perfil",
        "Display name": "Nombre visible",
        "Save profile": "Guardar perfil",
        "Your name": "Tu nombre",
        "Username": "Nombre de usuario",
        "Confirm password": "Confirmar contraseña",
        "Create Profile": "Crear perfil",
        "Please enter your email.": "Introduce tu email.",
        "Password reset email sent.": "Email para restablecer la contraseña enviado.",
        "Profile saved.": "Perfil guardado.",
        "Friends": "Amigos",
        "My friends": "Mis amigos",
        "No friends yet.": "Todavía no tienes amigos.",
        "Remove": "Eliminar",
        "Remove friend?": "¿Eliminar este amigo?",
        "You will no longer be connected.": "Ya no estaréis conectados.",
        "Friend Requests": "Solicitudes de amistad",
        "Friend requests": "Solicitudes de amistad",
        "pending": "pendientes",
        "friends": "amigos",
        "Accept": "Aceptar",
        "Decline": "Rechazar",
        "PenPal archive": "Archivo PenPal",
        "Stay in each other's chapters.": "Sigue formando parte de las historias de tus amigos.",
        "New Issue": "Nueva edición",
        "Start creating": "Empezar a crear",
        "Drafts": "Borradores",
        "Continue your unfinished issues": "Continúa tus ediciones sin terminar",
        "Sign up": "Registrarse",
        "Log in": "Iniciar sesión",
        "Forgot password?": "¿Olvidaste tu contraseña?",
        "Reset password": "Restablecer contraseña",
        "Enter your email and we’ll send you a link to set a new password.": "Introduce tu email y te enviaremos un enlace para crear una contraseña nueva.",
        "Send reset email": "Enviar email de restablecimiento",
        "Please enter a username.": "Introduce un nombre de usuario.",
        "Passwords do not match.": "Las contraseñas no coinciden.",
        "Username must be at least 3 characters.": "El nombre de usuario debe tener al menos 3 caracteres.",
        "Username too long.": "Nombre de usuario demasiado largo.",
        "This username is already taken.": "Ese nombre de usuario ya está en uso.",
        "Delete": "Eliminar",
        "Group": "Grupo",
        "Group magazines": "Revistas del grupo",
        "Year": "Año",
        "Add group picture": "Añadir foto del grupo",
        "Leave group": "Salir del grupo",
        "Delete group": "Eliminar grupo",
        "Leave group?": "¿Salir del grupo?",
        "Leave": "Salir",
        "You will no longer receive magazines from this group.": "Ya no recibirás revistas de este grupo.",
        "Delete group?": "¿Eliminar grupo?",
        "This permanently deletes the group for all members.": "Esto elimina el grupo definitivamente para todos los miembros.",
        "Members": "Miembros",
        "No members yet": "Aún no hay miembros",
        "Create group": "Crear grupo",
        "Creating...": "Creando...",
        "Group name": "Nombre del grupo",
        "people · add or view members": "personas · añade o ve miembros",
        "Member added.": "Miembro añadido.",
        "Please enter a group name.": "Introduce un nombre para el grupo.",
        "You already have a group with this name.": "Ya tienes un grupo con ese nombre.",
        "User not found.": "No se encontró al usuario.",
        "Already in group.": "Ya está en el grupo.",
        "Saved Drafts": "Borradores guardados",
        "Draft": "Borrador",
        "Publish to": "Publicar en",
        "Continue editing": "Seguir editando",
        "Preview draft": "Vista previa del borrador",
        "Publish draft": "Publicar borrador",
        "No pages saved.": "No hay páginas guardadas.",
        "Page": "Página",
        "of": "de",
        "Edit": "Editar",
        "Preprint review": "Revisión previa",
        "Edit selected pages": "Editar páginas seleccionadas",
        "Generated issue": "Edición generada",
        "No pages to edit.": "No hay páginas para editar.",
        "Preview finished magazine": "Vista previa de la revista terminada",
        "Edit magazine": "Editar revista",
        "Finished magazine preview": "Vista previa final de la revista",
        "Edit this page": "Editar esta página",
        "Delete page": "Eliminar página",
        "Preview": "Vista previa",
        "Add sections or pages": "Añadir secciones o páginas",
        "Add selected": "Añadir selección",
        "Finish issue": "Finalizar edición",
        "Publish to groups": "Publicar en grupos",
        "1 issue": "1 edición",
        "issues": "ediciones",
        "photo": "Añadir foto",
        "write here…": "Escribe tu reflexión…",
        "No throwbacks yet — published issues will appear here.": "Aún no hay recuerdos — las ediciones publicadas aparecerán aquí.",
        "Throwback": "Recuerdos",
        "Delete issue?": "¿Eliminar edición?",
        "This issue will be permanently removed.": "Esta edición se eliminará permanentemente.",
        "No drafts yet — start your first issue and save it here.": "Aún no hay borradores — empieza tu primera edición y guárdala aquí.",
        "Delete draft?": "¿Eliminar borrador?",
        "This draft will be permanently removed.": "Este borrador se eliminará permanentemente.",
        "This draft has no pages to publish.": "Este borrador no tiene páginas para publicar.",
        "Loading draft...": "Cargando borrador...",
        "This draft has no editable pages.": "Este borrador no tiene páginas editables.",
        "This draft is still loading or has no editable pages.": "Este borrador aún carga o no tiene páginas editables.",
        "No magazines published this month yet.": "Aún no hay revistas publicadas este mes.",
        "Delete any page you do not want. The layout is locked to the PowerPoint template. Text boxes can be written in; photo boxes keep their size and only the photo inside can be zoomed or moved.": "Elimina cualquier página que no quieras. El diseño queda bloqueado al modelo de PowerPoint. Puedes escribir en los cuadros de texto; los cuadros de foto mantienen su tamaño y solo la foto interior se puede ampliar o mover.",
        "Delete any pages you don't want to include. Magazines can contain up to 30 pages.": "Elimina las páginas que no quieras incluir. Cada revista puede contener hasta 30 páginas.",
        "No pages to preview.": "No hay páginas para previsualizar.",
        "All sections are already in this issue.": "Todas las secciones ya están en esta edición.",
        "You are not in any groups yet.": "Aún no estás en ningún grupo.",
        "Sections added. Save the draft to keep these changes.": "Secciones añadidas. Guarda el borrador para conservar los cambios.",
        "Page deleted. Save the draft to keep this change.": "Página eliminada. Guarda el borrador para conservar este cambio.",
        "Create at least one page first.": "Crea primero al menos una página.",
        "Draft could not be prepared for saving.": "No se pudo preparar el borrador para guardar.",
        "Draft could not be saved:": "No se pudo guardar el borrador:",
        "Draft saved. You can find it in Drafts.": "Borrador guardado. Lo encontrarás en Borradores.",
        "Select at least one group.": "Selecciona al menos un grupo.",
        "An issue can contain up to 30 pages.": "Una edición puede contener hasta 30 páginas.",
        "Your magazine has more than 30 pages. Delete pages before publishing.": "Tu revista tiene más de 30 páginas. Elimina páginas antes de publicar.",
        "Your issue has too many photos. Please keep it under 50 photos.": "Tu edición tiene demasiadas fotos. Manténla por debajo de 50 fotos.",
        "Issue published. You can find it in old magazines.": "Edición publicada. La encontrarás en revistas antiguas.",
        "Issue could not be published:": "No se pudo publicar la edición:",
        "Saving...": "Guardando...",
        "Save for later": "Guardar para después",
        "Save Draft": "Guardar borrador",
        "Continue Draft": "Continuar borrador",
        "Load Draft": "Cargar borrador",
        "Local Draft": "Borrador local",
        "Draft saved locally.": "Borrador guardado en el dispositivo.",
        "Continue editing your saved local draft": "Sigue editando el borrador guardado en el dispositivo",
        "Local draft could not be loaded:": "No se pudo cargar el borrador local:",
        "Publishing...": "Publicando...",
        "Publish selected groups": "Publicar en grupos seleccionados",
        "Find Friends": "Buscar amigos",
        "Find friends": "Buscar amigos",
        "Search, requests and friends": "Busca personas, solicitudes y amigos",
        "Search by username": "Buscar por nombre de usuario",
        "Search users": "Buscar usuarios",
        "Add Friend": "Añadir amigo",
        "Remove friend": "Eliminar amigo",
        "Incoming requests": "Solicitudes recibidas",
        "Pending sent requests": "Solicitudes enviadas pendientes",
        "No pending requests.": "No hay solicitudes pendientes.",
        "No sent requests pending.": "No hay solicitudes enviadas pendientes.",
        "Pending": "Pendiente",
        "Respond to request": "Responder solicitud",
        "This is you": "Este eres tú",
        "Friend request sent.": "Solicitud de amistad enviada.",
        "Open Settings": "Abrir Ajustes",
        "Allow notifications": "Permitir notificaciones",
        "Reminder saved.": "Recordatorio guardado.",
        "Reminder turned off.": "Recordatorio desactivado.",
        "Publishing Reminder": "Recordatorio de publicación",
        "Current streak": "Racha actual",
        "Posted": "Han publicado",
        "Posted singular": "Ha publicado",
        "Still missing": "Faltan por publicar",
        "Still missing singular": "Falta por publicar",
        "Group monthly progress": "Progreso mensual del grupo",
        "Day of month": "Día del mes",
        "Time": "Hora",
        "Rename group": "Renombrar grupo",
        "Group Members": "Miembros del grupo",
        "Join my PenPal group": "Únete a mi grupo de PenPal",
        "Share group link": "Compartir enlace del grupo",
        "Invite people to join this group": "Invita a otras personas a unirse a este grupo",
        "Copy invite link": "Copiar enlace de invitación",
        "Save the invitation link to your clipboard": "Guarda el enlace de invitación en el portapapeles",
        "Invite link copied.": "Enlace de invitación copiado.",
        "Send to groups": "Enviar a grupos",
        "Send": "Enviar",
        "Sending...": "Enviando...",
        "Issue sent to selected groups.": "Edición enviada a los grupos seleccionados.",
        "This issue is already available in all your groups.": "Esta edición ya está disponible en todos tus grupos.",
        "This sends the same published issue to the selected groups without creating another throwback copy.": "Esto envía la misma edición publicada a los grupos seleccionados sin crear otra copia en Recuerdos.",
        "Only the publisher can send this issue to more groups.": "Solo quien publicó la edición puede enviarla a más grupos.",
        "Select at least one new group.": "Selecciona al menos un grupo nuevo.",
        "Issue could not be sent to more groups:": "No se pudo enviar la edición a más grupos:",
        "pages": "páginas",
        "Clean Neutral": "Neutro limpio",
        "Black & White": "Blanco y negro",
        "Soft Blush": "Rosa suave",
        "Quiet Sage": "Salvia serena",
        "Calm Atlantic": "Atlántico sereno",
        "Marine": "Marino",
        "Tap highlighted text to edit": "Toca el texto resaltado para editarlo",
        "Done": "Listo",
        "Close": "Cerrar",
        "Photo": "Foto",
        "Adjust photo": "Ajustar foto",
        "Change photo": "Cambiar foto",
        "Fit / Fill": "Ajustar / Rellenar",
        "Reset position": "Restablecer posición",
        "Delete photo": "Eliminar foto",
        "Paste image": "Pegar imagen",
        "No photo selected.": "No hay foto seleccionada.",
        "Save": "Guardar",
        "Margin Notes": "Notas al margen",
        "No margin notes on this page yet.": "Aún no hay notas al margen en esta página.",
        "Leave a Note": "Dejar una nota",
        "Edit Your Note": "Editar tu nota",
        "Save Note": "Guardar nota",
        "Update Note": "Actualizar nota",
        "slide to track progress": "Marca tu progreso",
        "swipe to review": "desliza para valorar"
    ]

    private static let frenchExtras = [
        "Privacy": "Confidentialité",
        "PenPal user": "Utilisateur PenPal",
        "Back": "Retour",
        "Enabled": "Activées",
        "Disabled": "Désactivées",
        "Not Determined": "Pas encore décidé",
        "Margin note notifications": "Notifications des notes en marge",
        "Notify me when someone leaves a note.": "Préviens-moi quand quelqu’un laisse une note.",
        "PenPal Lab": "PenPal Lab",
        "Help shape the future of PenPal": "Aide à imaginer l'avenir de PenPal",
        "Development Preview": "Aperçu de développement",
        "Suggest an idea": "Proposer une idée",
        "What should PenPal do next?": "Que devrait faire PenPal ensuite ?",
        "Suggestions may be visible to other Founder Supporters.": "Les suggestions peuvent être visibles par d'autres Founder Supporters.",
        "Submit suggestion": "Envoyer la suggestion",
        "Submitting...": "Envoi...",
        "Most supported": "Les plus soutenues",
        "Newest": "Les plus récentes",
        "Sort suggestions": "Trier les suggestions",
        "Under review": "En étude",
        "Planned": "Prévu",
        "In progress": "En cours",
        "Released": "Publié",
        "Not planned": "Non prévu",
        "I want this too": "Je le veux aussi",
        "Vote removed": "Vote retiré",
        "Thanks for helping shape PenPal": "Merci d'aider PenPal à évoluer",
        "Roadmap": "Feuille de route",
        "No roadmap items yet.": "Aucun élément dans la feuille de route.",
        "Suggestions": "Suggestions",
        "No suggestions yet.": "Aucune suggestion pour l'instant.",
        "PenPal Lab is only available to Founder Supporters.": "PenPal Lab est réservé aux Founder Supporters.",
        "This area is not available for your account right now.": "Cet espace n'est pas disponible pour ton compte pour le moment.",
        "Title": "Titre",
        "Description": "Description",
        "Category": "Catégorie",
        "Feature": "Fonctionnalité",
        "Design": "Design",
        "Magazine page": "Page de magazine",
        "Bug": "Bug",
        "Other": "Autre",
        "Founder": "Founder",
        "Founder Supporter": "Founder Supporter",
        "Choose what PenPal can notify you about.": "Choisis ce que PenPal peut t’envoyer comme notifications.",
        "iPhone notifications": "Notifications iPhone",
        "Notifications are disabled in iPhone Settings.": "Les notifications sont désactivées dans les Réglages de l’iPhone.",
        "Open iPhone Settings": "Ouvrir les Réglages iPhone",
        "Open Settings": "Ouvrir les Réglages",
        "Allow PenPal notifications": "Autoriser les notifications PenPal",
        "Tap to allow iPhone notifications for PenPal.": "Touche pour autoriser les notifications iPhone pour PenPal.",
        "Manage iPhone notification delivery in Settings.": "Gère l’envoi des notifications iPhone dans les Réglages.",
        "Covers friend requests, groups, magazines, activity, margin notes and PenPal announcements.": "Inclut les demandes d’amis, les groupes, les magazines, l’activité, les notes en marge et les annonces PenPal.",
        "Enable notifications in iPhone Settings to receive PenPal notifications.": "Active les notifications dans les Réglages iPhone pour recevoir les notifications PenPal.",
        "Friend requests and new friends": "Demandes d’amis et nouveaux amis",
        "Group invitations and group updates": "Invitations et actualités des groupes",
        "New magazines": "Nouveaux magazines",
        "Magazine activity": "Activité des magazines",
        "Margin notes": "Notes en marge",
        "Replies and reactions": "Réponses et réactions",
        "PenPal announcements": "Annonces PenPal",
        "Notification preferences saved.": "Préférences de notification enregistrées.",
        "Saving...": "Enregistrement...",
        "Your PenPal Plan": "Ton abonnement PenPal",
        "Upgrade or change plan": "Améliorer ou changer d’abonnement",
        "Compare plans": "Comparer les abonnements",
        "Restore purchases": "Restaurer les achats",
        "About PenPal": "À propos de PenPal",
        "More PenPal options": "Plus d’options PenPal",
        "Free": "Gratuit",
        "Pro": "Pro",
        "Premium": "Premium",
        "Included features": "Fonctionnalités incluses",
        "Create magazines, save drafts, publish to groups and collect your memories in PenPal.": "Crée des magazines, enregistre des brouillons, publie dans des groupes et rassemble tes souvenirs dans PenPal.",
        "Renewal information": "Informations de renouvellement",
        "No renewal information is available yet.": "Aucune information de renouvellement n’est encore disponible.",
        "Manage subscription": "Gérer l’abonnement",
        "A quieter place for shared monthly magazines.": "Un espace plus calme pour des magazines mensuels partagés.",
        "Founder Supporter Hub": "Espace Founder Supporter",
        "Submit feedback": "Envoyer un retour",
        "Voting and roadmap": "Votes et feuille de route",
        "Founder benefits": "Avantages Founder",
        "Founder badge": "Badge Founder",
        "Current plan": "Abonnement actuel",
        "Continue": "Continuer",
        "Purchases restored.": "Achats restaurés.",
        "Purchases could not be restored right now.": "Impossible de restaurer les achats pour le moment.",
        "Subscriptions are not available in this development build yet.": "Les abonnements ne sont pas encore disponibles dans cette version de développement.",
        "Create magazines, save drafts and share with your groups.": "Crée des magazines, enregistre des brouillons et partage-les avec tes groupes.",
        "Extra creative tools and more room to shape each issue.": "Des outils créatifs en plus et plus d’espace pour façonner chaque numéro.",
        "The fullest PenPal experience for frequent magazine makers.": "L’expérience PenPal la plus complète pour celles et ceux qui créent souvent des magazines.",
        "Includes PenPal Lab, voting, roadmap previews and the Founder badge.": "Inclut PenPal Lab, les votes, les aperçus de la feuille de route et le badge Founder.",
        "Ideas and voting": "Idées et votes",
        "Early access to PenPal Lab experiments.": "Accès anticipé aux expériences PenPal Lab.",
        "Vote on ideas and help shape the roadmap.": "Vote pour les idées et aide à façonner la feuille de route.",
        "A subtle Founder badge inside PenPal Lab.": "Un badge Founder discret dans PenPal Lab.",
        "PenPal Lab is included with Founder Supporter.": "PenPal Lab est inclus avec Founder Supporter.",
        "Upgrade to unlock ideas, voting, feedback and the roadmap.": "Passe à l’offre supérieure pour débloquer les idées, les votes, les retours et la feuille de route.",
        "Shape upcoming ideas, vote on suggestions and follow what is planned.": "Aide à façonner les prochaines idées, vote pour les suggestions et suis ce qui est prévu.",
        "Share thoughtful product ideas with the PenPal team.": "Partage des idées produit réfléchies avec l’équipe PenPal.",
        "Support ideas and see what is planned, in progress or released.": "Soutiens des idées et découvre ce qui est prévu, en cours ou publié.",
        "See what Founder Supporter unlocks as PenPal grows.": "Découvre ce que Founder Supporter débloque à mesure que PenPal évolue.",
        "A subtle mark for early supporters inside PenPal Lab.": "Une marque discrète pour les premiers soutiens dans PenPal Lab.",
        "You need to be logged in.": "Tu dois être connecté.",
        "Please add a title.": "Ajoute un titre.",
        "Please add a description.": "Ajoute une description.",
        "Please keep your suggestion a little shorter.": "Raccourcis un peu ta suggestion.",
        "Settings": "Réglages",
        "Language": "Langue",
        "Privacy Policy": "Politique de confidentialité",
        "How your data is used": "Comment tes données sont utilisées",
        "Sign out": "Se déconnecter",
        "Delete profile permanently": "Supprimer le profil définitivement",
        "Deleting account...": "Suppression du compte...",
        "Delete profile permanently?": "Supprimer le profil définitivement ?",
        "Delete everything": "Tout supprimer",
        "Cancel": "Annuler",
        "This deletes your account, profile, drafts, published issues, friend connections and groups you own.": "Cela supprime ton compte, ton profil, tes brouillons, tes numéros publiés, tes liens d’amitié et les groupes que tu gères.",
        "Confirm Password": "Confirmer le mot de passe",
        "Password": "Mot de passe",
        "Delete account permanently": "Supprimer le compte définitivement",
        "Incorrect password.": "Mot de passe incorrect.",
        "Profile": "Profil",
        "Edit profile": "Modifier le profil",
        "Change profile photo": "Changer la photo de profil",
        "Display name": "Nom affiché",
        "Save profile": "Enregistrer le profil",
        "Your name": "Ton nom",
        "Username": "Nom d’utilisateur",
        "Confirm password": "Confirmer le mot de passe",
        "Create Profile": "Créer un profil",
        "Please enter your email.": "Entre ton e-mail.",
        "Password reset email sent.": "E-mail de réinitialisation envoyé.",
        "Profile saved.": "Profil enregistré.",
        "Friends": "Amis",
        "My friends": "Mes amis",
        "No friends yet.": "Pas encore d’amis.",
        "Remove": "Retirer",
        "Remove friend?": "Retirer cet ami ?",
        "You will no longer be connected.": "Vous ne serez plus connectés.",
        "Friend Requests": "Demandes d’amis",
        "Friend requests": "Demandes d’amis",
        "pending": "en attente",
        "friends": "amis",
        "Accept": "Accepter",
        "Decline": "Refuser",
        "PenPal archive": "Archive PenPal",
        "Stay in each other's chapters.": "Reste dans les histoires de tes amis.",
        "New Issue": "Nouveau numéro",
        "Start creating": "Commencer",
        "Drafts": "Brouillons",
        "Continue your unfinished issues": "Continue tes numéros inachevés",
        "Sign up": "S’inscrire",
        "Log in": "Se connecter",
        "Forgot password?": "Mot de passe oublié ?",
        "Reset password": "Réinitialiser le mot de passe",
        "Enter your email and we’ll send you a link to set a new password.": "Entre ton e-mail et nous t’enverrons un lien pour créer un nouveau mot de passe.",
        "Send reset email": "Envoyer l’e-mail",
        "Please enter a username.": "Entre un nom d’utilisateur.",
        "Passwords do not match.": "Les mots de passe ne correspondent pas.",
        "Username must be at least 3 characters.": "Le nom d’utilisateur doit contenir au moins 3 caractères.",
        "Username too long.": "Nom d’utilisateur trop long.",
        "This username is already taken.": "Ce nom d’utilisateur est déjà pris.",
        "Delete": "Supprimer",
        "Group": "Groupe",
        "Group magazines": "Magazines du groupe",
        "Year": "Année",
        "Add group picture": "Ajouter une photo de groupe",
        "Leave group": "Quitter le groupe",
        "Delete group": "Supprimer le groupe",
        "Leave group?": "Quitter le groupe ?",
        "Leave": "Quitter",
        "You will no longer receive magazines from this group.": "Tu ne recevras plus les magazines de ce groupe.",
        "Delete group?": "Supprimer le groupe ?",
        "This permanently deletes the group for all members.": "Cela supprime définitivement le groupe pour tous les membres.",
        "Members": "Membres",
        "No members yet": "Aucun membre pour l’instant",
        "Create group": "Créer un groupe",
        "Creating...": "Création...",
        "Group name": "Nom du groupe",
        "people · add or view members": "personnes · ajouter ou voir les membres",
        "Member added.": "Membre ajouté.",
        "Please enter a group name.": "Entre un nom de groupe.",
        "You already have a group with this name.": "Tu as déjà un groupe avec ce nom.",
        "User not found.": "Utilisateur introuvable.",
        "Already in group.": "Déjà dans le groupe.",
        "Saved Drafts": "Brouillons enregistrés",
        "Draft": "Brouillon",
        "Publish to": "Publier dans",
        "Continue editing": "Continuer l’édition",
        "Preview draft": "Aperçu du brouillon",
        "Publish draft": "Publier le brouillon",
        "No pages saved.": "Aucune page enregistrée.",
        "Page": "Page",
        "of": "sur",
        "Edit": "Modifier",
        "Preprint review": "Révision avant impression",
        "Edit selected pages": "Modifier les pages choisies",
        "Generated issue": "Numéro généré",
        "No pages to edit.": "Aucune page à modifier.",
        "Preview finished magazine": "Aperçu du magazine terminé",
        "Edit magazine": "Modifier le magazine",
        "Finished magazine preview": "Aperçu du magazine terminé",
        "Edit this page": "Modifier cette page",
        "Delete page": "Supprimer la page",
        "Preview": "Aperçu",
        "Add sections or pages": "Ajouter des sections ou des pages",
        "Add selected": "Ajouter la sélection",
        "Finish issue": "Terminer le numéro",
        "Publish to groups": "Publier dans les groupes",
        "1 issue": "1 numéro",
        "issues": "numéros",
        "photo": "photo",
        "write here…": "écris ici…",
        "No throwbacks yet — published issues will appear here.": "Aucun souvenir pour l’instant — les numéros publiés apparaîtront ici.",
        "Throwback": "Souvenirs",
        "Delete issue?": "Supprimer le numéro ?",
        "This issue will be permanently removed.": "Ce numéro sera supprimé définitivement.",
        "No drafts yet — start your first issue and save it here.": "Aucun brouillon pour l’instant — commence ton premier numéro et enregistre-le ici.",
        "Delete draft?": "Supprimer le brouillon ?",
        "This draft will be permanently removed.": "Ce brouillon sera supprimé définitivement.",
        "This draft has no pages to publish.": "Ce brouillon n’a aucune page à publier.",
        "Loading draft...": "Chargement du brouillon...",
        "This draft has no editable pages.": "Ce brouillon n’a aucune page modifiable.",
        "This draft is still loading or has no editable pages.": "Ce brouillon charge encore ou n’a aucune page modifiable.",
        "No magazines published this month yet.": "Aucun magazine publié ce mois-ci.",
        "Delete any page you do not want. The layout is locked to the PowerPoint template. Text boxes can be written in; photo boxes keep their size and only the photo inside can be zoomed or moved.": "Supprime les pages que tu ne veux pas. La mise en page reste verrouillée sur le modèle PowerPoint. Tu peux écrire dans les zones de texte; les cadres photo gardent leur taille et seule la photo à l’intérieur peut être agrandie ou déplacée.",
        "Delete any pages you don't want to include. Magazines can contain up to 30 pages.": "Supprime les pages que tu ne veux pas inclure. Les magazines peuvent contenir jusqu’à 30 pages.",
        "No pages to preview.": "Aucune page à prévisualiser.",
        "All sections are already in this issue.": "Toutes les sections sont déjà dans ce numéro.",
        "You are not in any groups yet.": "Tu n’es encore dans aucun groupe.",
        "Sections added. Save the draft to keep these changes.": "Sections ajoutées. Enregistre le brouillon pour conserver ces changements.",
        "Page deleted. Save the draft to keep this change.": "Page supprimée. Enregistre le brouillon pour conserver ce changement.",
        "Create at least one page first.": "Crée d’abord au moins une page.",
        "Draft could not be prepared for saving.": "Le brouillon n’a pas pu être préparé pour l’enregistrement.",
        "Draft could not be saved:": "Le brouillon n’a pas pu être enregistré :",
        "Draft saved. You can find it in Drafts.": "Brouillon enregistré. Tu le trouveras dans Brouillons.",
        "Select at least one group.": "Sélectionne au moins un groupe.",
        "An issue can contain up to 30 pages.": "Un numéro peut contenir jusqu’à 30 pages.",
        "Your magazine has more than 30 pages. Delete pages before publishing.": "Ton magazine contient plus de 30 pages. Supprime des pages avant de publier.",
        "Your issue has too many photos. Please keep it under 50 photos.": "Ton numéro contient trop de photos. Reste sous 50 photos.",
        "Issue published. You can find it in old magazines.": "Numéro publié. Tu le trouveras dans les anciens magazines.",
        "Issue could not be published:": "Le numéro n’a pas pu être publié :",
        "Saving...": "Enregistrement...",
        "Save for later": "Enregistrer pour plus tard",
        "Save Draft": "Enregistrer le brouillon",
        "Continue Draft": "Continuer le brouillon",
        "Load Draft": "Charger le brouillon",
        "Local Draft": "Brouillon local",
        "Draft saved locally.": "Brouillon enregistré sur l’appareil.",
        "Continue editing your saved local draft": "Continue à modifier le brouillon enregistré sur l’appareil",
        "Local draft could not be loaded:": "Le brouillon local n’a pas pu être chargé :",
        "Publishing...": "Publication...",
        "Publish selected groups": "Publier dans les groupes sélectionnés",
        "slide to track progress": "glisse pour suivre le progrès",
        "swipe to review": "glisse pour noter"
    ]
}

func appText(_ english: String, _ languageRaw: String) -> String {
    AppLocalization.text(english, languageRaw: languageRaw)
}

func localizedFullMonthName(for month: Int, languageRaw: String) -> String {
    guard (1...12).contains(month) else { return "" }
    let language = AppLanguage(rawValue: languageRaw) ?? .english
    switch language {
    case .english:
        return ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"][month - 1]
    case .german:
        return ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"][month - 1]
    case .italian:
        return ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"][month - 1]
    case .spanish:
        return ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"][month - 1]
    case .french:
        return ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"][month - 1]
    }
}

func localizedMemberCount(_ count: Int, languageRaw: String) -> String {
    switch AppLanguage(rawValue: languageRaw) ?? .english {
    case .spanish:
        return "\(count) \(count == 1 ? "miembro" : "miembros")"
    default:
        return "\(count) \(count == 1 ? "member" : "members")"
    }
}

func localizedIssueCount(_ count: Int, languageRaw: String) -> String {
    switch AppLanguage(rawValue: languageRaw) ?? .english {
    case .spanish:
        return "\(count) \(count == 1 ? "edición" : "ediciones")"
    default:
        return count == 1 ? appText("1 issue", languageRaw) : "\(count) \(appText("issues", languageRaw))"
    }
}

func localizedMonthCount(_ count: Int, languageRaw: String) -> String {
    switch AppLanguage(rawValue: languageRaw) ?? .english {
    case .spanish:
        return "\(count) \(count == 1 ? "mes" : "meses")"
    default:
        return "\(count) \(count == 1 ? "month" : "months")"
    }
}

func localizedPostedProgress(posted: Int, total: Int, languageRaw: String) -> String {
    switch AppLanguage(rawValue: languageRaw) ?? .english {
    case .spanish:
        return "\(posted) de \(max(total, 0)) miembros \(posted == 1 ? "ha publicado" : "han publicado")"
    default:
        return "\(posted) / \(max(total, 0)) members posted"
    }
}

func localizedRemainingCharacters(_ count: Int, languageRaw: String) -> String {
    switch AppLanguage(rawValue: languageRaw) ?? .english {
    case .spanish:
        return "\(count) \(count == 1 ? "carácter restante" : "caracteres restantes")"
    default:
        return "\(count) characters left"
    }
}

func localizedDisplayDate(_ date: Date, languageRaw: String) -> String {
    let formatter = DateFormatter()
    formatter.dateStyle = .long
    formatter.timeStyle = .none
    switch AppLanguage(rawValue: languageRaw) ?? .english {
    case .english:
        formatter.locale = Locale(identifier: "en")
    case .german:
        formatter.locale = Locale(identifier: "de")
    case .italian:
        formatter.locale = Locale(identifier: "it")
    case .spanish:
        formatter.locale = Locale(identifier: "es")
    case .french:
        formatter.locale = Locale(identifier: "fr")
    }
    return formatter.string(from: date)
}

func localizedIssueTitle(owner: String, month: Int, languageRaw: String) -> String {
    let monthName = localizedFullMonthName(for: month, languageRaw: languageRaw)
    switch AppLanguage(rawValue: languageRaw) ?? .english {
    case .spanish:
        return "\(owner): edición de \(monthName)"
    default:
        return "\(owner)'s \(monthName) Issue"
    }
}
