import Foundation

extension MagazineTemplateLocalization {
    static let italianTranslations: [String: String] = [
        "Monthly Reset": "Rito mensile",
        "Tiny Wins": "Piccole vittorie",
        "Hobbies": "Passioni",
        "Relationships": "Relazioni",
        "Playlist & Music": "Playlist & musica",
        "Cinema": "Cinema",
        "Reading": "Letture",
        "Food & Recipes": "Tavola & ricette",
        "Travel & Places": "Viaggi & luoghi",
        "Favourites": "Preferiti",
        "Affirmations & Goals": "Affermazioni & obiettivi",
        "ISSUE №01 · 2026": "NUMERO №01 · 2026",
        "ISSUE №01": "NUMERO №01",
        "STAY IN EACH OTHER'S CHAPTERS": "RESTATE NEI CAPITOLI L’UNO DELL’ALTRA",
        "STAY PART OF YOUR FRIENDS' STORIES": "Resta parte delle storie dei tuoi amici.",
        "“A magazine you make\nto grow together.”": "“Un magazine creato\nper crescere insieme.”",
        "MAKE IT.  SHARE IT.  REMEMBER IT.": "Crealo.  Condividilo.  Ricordalo.",
        "penpal · the editorial journal": "PenPal · diario editoriale",
        "MADE WITH LOVE": "Fatto con amore.",
        "Contents.": "Indice.",
        "In this issue.": "In questo numero.",
        "CONTENTS · IN THIS ISSUE": "INDICE · IN QUESTO NUMERO",
        "MONTHLY RESET": "RITO MENSILE",
        "MONTHLY RESET · DAILY REFLECTION": "RITO MENSILE · RIFLESSIONE",
        "MONTHLY RESET · GRATITUDE": "RITO MENSILE · GRATITUDINE",
        "MONTHLY RESET · LETTER": "RITO MENSILE · LETTERA",
        "MONTHLY RESET · LOOKING BACK": "RITO MENSILE · SGUARDO INDIETRO",
        "MONTHLY RESET · GROW TRACKER": "RITO MENSILE · CRESCITA",
        "TINY WINS · THE DAILY ME": "PICCOLE VITTORIE · CRONACHE DI ME",
        "TINY WINS · TROPHY CABINET": "PICCOLE VITTORIE · TROFEI",
        "TINY WINS · STREAK": "PICCOLE VITTORIE · SERIE",
        "TINY WINS · HIGHLIGHT REEL": "PICCOLE VITTORIE · HIGHLIGHT",
        "HOBBIES · TRACKER": "PASSIONI · TRACKER",
        "HOBBIES · A NEW TRY": "PASSIONI · NUOVO TENTATIVO",
        "HOBBIES · GALLERY": "PASSIONI · GALLERIA",
        "HOBBIES · PROGRESS": "PASSIONI · PROGRESSI",
        "RELATIONSHIPS · DATE REVIEW": "RELAZIONI · DOPO L’INCONTRO",
        "RELATIONSHIPS · THE RANKING": "RELAZIONI · CLASSIFICA",
        "RELATIONSHIPS · APPRECIATION": "RELAZIONI · GRATITUDINE",
        "RELATIONSHIPS · IN LOVE WITH LIFE": "RELAZIONI · INNAMORARSI DELLA VITA",
        "RELATIONSHIPS · NEWEST OBSESSION": "RELAZIONI · ULTIMA INFATUAZIONE",
        "RELATIONSHIPS · PEOPLE I LOVE": "RELAZIONI · PERSONE CHE AMO",
        "PLAYLIST & MUSIC · WRAPPED": "PLAYLIST & MUSICA · RITRATTO",
        "PLAYLIST & MUSIC · FESTIVAL": "PLAYLIST & MUSICA · FESTIVAL",
        "PLAYLIST & MUSIC · LINER NOTES": "PLAYLIST & MUSICA · NOTE",
        "PLAYLIST & MUSIC · MIXTAPE": "PLAYLIST & MUSICA · MIXTAPE",
        "CINEMA · TICKET STUB": "CINEMA · BIGLIETTO",
        "CINEMA · WATCH LOG": "CINEMA · VISTI",
        "CINEMA · HIGHLIGHTS": "CINEMA · MOMENTI",
        "READING · BOOKPLATE": "LETTURE · EX LIBRIS",
        "READING · MARGIN NOTES": "LETTURE · NOTE A MARGINE",
        "READING · MINI REVIEWS": "LETTURE · MINI-RECENSIONI",
        "READING · TBR STACK": "LETTURE · DA LEGGERE",
        "FOOD & RECIPES · CULINARY CREATIONS": "TAVOLA & RICETTE · CREAZIONI",
        "FOOD & RECIPES · WEEK ON A PLATE": "TAVOLA & RICETTE · SETTIMANA NEL PIATTO",
        "FOOD & RECIPES · TABLE FOR ONE": "TAVOLA & RICETTE · UN TAVOLO PER UNO",
        "TRAVEL · POSTCARD": "VIAGGI · CARTOLINA",
        "TRAVEL · PLACES SEEN": "VIAGGI · LUOGHI VISITATI",
        "FAVOURITES · BEAUTY SHELF": "PREFERITI · BELLEZZA",
        "FAVOURITES · EDIBLE": "PREFERITI · SAPORI",
        "FAVOURITES · APPS & INTERNET": "PREFERITI · APP & WEB",
        "FAVOURITES · RITUALS": "PREFERITI · RITUALI",
        "GOALS · OUTLOOK": "OBIETTIVI · PROSPETTIVA",
        "GOALS · AFFIRMATIONS": "OBIETTIVI · AFFERMAZIONI",
        "GOALS · VISION BOARD": "OBIETTIVI · TAVOLA VISIVA",
        "GOALS · SUMMARY": "OBIETTIVI · SOMMARIO",
        "THE DAILY ME": "CRONACHE DI ME",
        "TROPHY CABINET": "TROFEI",
        "HIGHLIGHT REEL": "MOMENTI MIGLIORI",
        "HOBBY TRACKER": "TRACKER PASSIONI",
        "A NEW TRY": "UN NUOVO TENTATIVO",
        "HOBBY GALLERY": "GALLERIA DELLE PASSIONI",
        "PROGRESS TRACKER": "TRACCIA DEI PROGRESSI",
        "DATE REVIEW": "DOPO L’INCONTRO",
        "FIRST IMPRESSIONS": "PRIME IMPRESSIONI",
        "VIBE CHECK": "ATMOSFERA",
        "conversation": "conversazione",
        "chemistry": "chimica",
        "humor": "umorismo",
        "looks": "fascino",
        "presence": "presenza",
        "manners": "modi",
        "overall": "insieme",
        "THE RANKING": "LA CLASSIFICA",
        "Ranking.": "La classifica.",
        "WOULD SEE AGAIN": "LA RIVEDREI?",
        "DO I WANT TO SEE THIS PERSON AGAIN?": "Mi va di rivedere questa persona?",
        "YES": "Sì",
        "NO": "No",
        "MAYBE": "Forse",
        "NEVER": "Mai",
        "Y": "S",
        "N": "N",
        "APPRECIATION POST": "NOTA DI GRATITUDINE",
        "PEOPLE I LOVE": "PERSONE CHE AMO",
        "NEWEST OBSESSION": "ULTIMA INFATUAZIONE",
        "MY RECOMMENDATIONS": "LE MIE SEGNALAZIONI",
        "MY ROUTINES": "LE MIE ROUTINE",
        "BOOKPLATE": "EX LIBRIS",
        "MARGIN NOTES": "NOTE A MARGINE",
        "TO BE READ": "DA LEGGERE",
        "CULINARY CREATIONS": "CREAZIONI",
        "WEEK ON A PLATE": "SETTIMANA NEL PIATTO",
        "TABLE FOR ONE": "Un tavolo per uno",
        "POSTCARD": "CARTOLINA",
        "PLACES SEEN": "Luoghi visitati",
        "BEAUTY SHELF": "Bellezza",
        "EDIBLE FAVOURITES": "I miei preferiti",
        "WORD OF THE MONTH": "PAROLA DEL MESE",
        "VISION BOARD": "Tavola visiva",
        "AFFIRMATIONS": "AFFERMAZIONI",
        "TITLE": "TITOLO",
        "AUTHOR": "AUTORE",
        "GENRE": "GENERE",
        "DATE": "Data",
        "NAME": "NOME",
        "THEIR NAME": "NOME",
        "AGE": "ETÀ",
        "OCCUPATION": "Professione",
        "PLACE": "Luogo",
        "WHERE": "DOVE",
        "WHEN": "QUANDO",
        "WITH": "CON",
        "YEAR": "ANNO",
        "RUNTIME": "DURATA",
        "DIRECTED BY": "REGIA",
        "RATING": "Valutazione",
        "ROW": "FILA",
        "SEAT": "POSTO",
        "ALBUM": "ALBUM",
        "ARTIST": "ARTISTA",
        "FAVOURITE TRACK": "BRANO PREFERITO",
        "TOP ARTIST": "ARTISTA TOP",
        "TOP SONG": "BRANO TOP",
        "A MOOD": "Atmosfera",
        "BRAND / PRODUCT": "Brand / Prodotto",
        "WHY I LOVE IT →": "Perché lo amo →",
        "WHAT IT’S ABOUT": "Di cosa parla",
        "WHAT I ORDERED →": "Cosa ho ordinato →",
        "WORTH RETURNING?": "Ci tornerei?",
        "ATMOSPHERE": "Atmosfera",
        "SERVICE": "Servizio",
        "VALUE": "Qualità/prezzo",
        "WORK": "LAVORO",
        "HEALTH": "SALUTE",
        "LOVE": "AMORE",
        "MONEY": "DENARO",
        "REST": "RIPOSO",
        "CRAFT": "CREATIVITÀ",
        "INTENTIONS": "Intenzioni",
        "cover": "Copertina",
        "▢  photo": "▢  Foto",
        "▢  cover": "▢  Copertina",
        "▢  cover art": "▢  Copertina",
        "▢  picture": "▢  Immagine",
        "▢  portrait": "▢  Ritratto",
        "write here…": "Scrivi qui…",
        "write one word here": "Scrivi una parola",
        "write your word": "Scrivi la tua parola",
        "a few lines from you…": "Qualche riga, con calma…",
        "your name": "Il tuo nome",
        "LIVE · CAPTURE · SHARE": "VIVI · CATTURA · CONDIVIDI",
        "Monthly Reset.": "Rito mensile.",
        "A slow audit of the days behind — what stayed, what shifted, what is worth remembering.": "Uno sguardo quieto ai giorni trascorsi: ciò che resta, ciò che cambia, ciò che merita memoria.",
        "SECTION": "SEZIONE",
        "FEELING": "SENSAZIONE",
        "ONE GOOD THING": "UNA COSA BELLA",
        "ONE HARD THING": "UNA COSA DIFFICILE",
        "ONE THING I LEARNED": "UNA COSA CHE HO IMPARATO",
        "ONE THING I’M GRATEFUL FOR": "UNA COSA PER CUI PROVO GRATITUDINE",
        "HIGHS & LOWS": "LUCI & OMBRE",
        "How the month": "Come il mese",
        "shaped me.": "mi ha cambiato.",
        "THE HIGHS": "LE LUCI",
        "THE LOWS": "LE OMBRE",
        "MONTH IN ONE FRAME": "QUESTO MESE IN UN’IMMAGINE",
        "▢  a high moment": "▢  un momento bello",
        "▢  a low moment": "▢  un momento difficile",
        "▢  one image that holds the whole month": "▢  un’immagine che racconta tutto il mese",
        "GRATITUDE": "GRATITUDINE",
        "What I am": "Per cosa provo",
        "grateful for.": "gratitudine.",
        "small things": "Piccole cose",
        "people": "Persone",
        "places": "Luoghi",
        "moments": "Momenti",
        "things you gave me this month —": "Cose che questo mese mi ha regalato –",
        "A LETTER": "UNA LETTERA",
        "Dear month,": "Caro mese,",
        "a letter to the month from me.": "una lettera per il mese.",
        "LOOKING BACK": "GUARDANDO INDIETRO",
        "A WORD FOR THE MONTH": "Una parola per il mese",
        "one word": "Una parola",
        "THE FIRST THING I WANT TO REMEMBER…": "LA PRIMA COSA CHE VOGLIO RICORDARE…",
        "WHAT I AM READY TO CHANGE…": "COSA SONO PRONTO A CAMBIARE…",
        "WHAT I LEARNED ABOUT MYSELF…": "COSA HO IMPARATO SU DI ME…",
        "Tiny Wins.": "Piccole vittorie.",
        "Small triumphs, printed in earnest — the quiet headlines of an honest week.": "Piccole vittorie da condividere – i titoli gentili di un mese riuscito.",
        "Small wins to share — the gentle headlines of a good month.": "Piccole vittorie da condividere – i titoli gentili di un mese riuscito.",
        "Local human has a very good": "Una persona ha vissuto un",
        "month.": "mese straordinario.",
        "A MONTH OF TINY VICTORIES": "UN MESE DI PICCOLE VITTORIE",
        "WIN OF THE MONTH": "VITTORIA DEL MESE",
        "EDITORIAL — WHAT MADE THIS MONTH A WIN": "EDITORIALE – COSA HA RESO SPECIALE QUESTO MESE",
        "WHAT HAPPENED →": "COSA È SUCCESSO →",
        "AWARD Nº 01": "PREMIO N. 01",
        "AWARD Nº 02": "PREMIO N. 02",
        "AWARD Nº 03": "PREMIO N. 03",
        "AWARD Nº 04": "PREMIO N. 04",
        "FOR": "PER",
        "Hobbies.": "Passioni.",
        "The slow practice of becoming better at something you love.": "L’arte di migliorare in ciò che ami.",
        "Skill": "Progressi",
        "consistency": "costanza",
        "confidence": "sicurezza",
        "creativity": "creatività",
        "speed": "velocità",
        "technique": "tecnica",
        "theory": "teoria",
        "effort": "impegno",
        "cost": "spesa",
        "difficulty": "difficoltà",
        "reward": "soddisfazione",
        "Relationships.": "Relazioni.",
        "Notes on being known — the people in your corner, on the page.": "Un’ode alle persone al tuo fianco, con quei dettagli che solo tu conosci.",
        "An ode to the people by your side, with a little gossip in the margins.": "Un’ode alle persone al tuo fianco, con quei dettagli che solo tu conosci.",
        "WHY I LOVE THEM": "PERCHÉ LE AMO",
        "WHY I LOVE THEM →": "Perché le amo →",
        "why I love them →": "Perché le amo →",
        "first noticed": "La prima volta che l’ho notata",
        "why they’re hot": "Cosa la rende magnetica",
        "what I already know about them": "Cosa so già di questa persona",
        "Playlist & Music.": "Playlist & musica.",
        "Liner notes from the month — the songs that scored your days.": "Note del mese – le canzoni che hanno dato ritmo ai giorni.",
        "Notes of the month — the songs that carried these days.": "Note del mese – le canzoni che hanno dato ritmo ai giorni.",
        "ON REPEAT": "IN LOOP",
        "a line about why →": "Una riga per ricordarla →",
        "artist · song": "artista · brano",
        "when I am in my feelings": "Quando mi sento fragile",
        "when I am happy": "Quando sono felice",
        "when I am in love": "Quando sono innamorato",
        "artist:": "Artista:",
        "song:": "Brano:",
        "Cinema.": "Cinema.",
        "Tickets, scenes, scores — the dark room remembered.": "Biglietti, scene, voti – tutto ciò che resta della sala buia.",
        "ADMIT ONE": "INGRESSO",
        "WATCH LOG": "FILM VISTI",
        "MOVIE HIGHLIGHTS": "MOMENTI DI CINEMA",
        "Reading.": "Letture.",
        "Stories worth being remembered — pages, lines, and the lives they made.": "Storie che meritano memoria – pagine, frasi e vite che si aprono.",
        "Stories worth remembering — pages, lines, and the lives they opened.": "Storie che meritano memoria – pagine, frasi e vite che si aprono.",
        "Food & Recipes.": "Tavola & ricette.",
        "From the kitchen — the dishes, the table, the small rituals of the week.": "Dalla cucina – piatti, tavola e piccoli rituali del mese.",
        "From the kitchen — the dishes, the table, the small rituals of the month.": "Dalla cucina – piatti, tavola e piccoli rituali del mese.",
        "Travel & Places.": "Viaggi & luoghi.",
        "Postcards from the coast — and everywhere else worth remembering.": "Cartoline dalla costa – e da ogni luogo che valeva la pena ricordare.",
        "Postcards from everywhere worth exploring and remembering.": "Cartoline da ogni luogo che valeva la pena esplorare.",
        "Favourites.": "Preferiti.",
        "The small obsessions — the things kept close, this month.": "Piccole ossessioni, cose tenute vicine questo mese.",
        "Affirmations & Goals.": "Affermazioni & obiettivi.",
        "The intentions to carry into the next month — said quietly, said clearly.": "Le intenzioni da portare nel prossimo mese, dette piano e con chiarezza.",
        "A small triumph!": "Un piccolo trionfo!",
        "CORRESPONDENT NOTE": "NOTA DEL CORRISPONDENTE",
        "How I grew.": "Come sono\ncambiato.",
        "END OF MONTH, HONESTLY.": "FINE DEL MESE",
        "End of": "Fine del",
        "month": "mese",
        "People I love.": "Le persone\nche amo.",
        "Crush": "Crush",
        "Diary.": "Diary.",
        "My Month": "Il mese",
        "in Sound.": "in musica.",
        "Album of": "Album del",
        "the Week.": "mese.",
        "The film of": "Il film della",
        "the night.": "serata.",
        "What I": "Cosa ho",
        "watched.": "guardato.",
        "To be": "Da",
        "read.": "leggere.",
        "Wish you": "Vorrei che tu",
        "were here.": "fossi qui.",
        "The month": "Il mese",
        "ahead.": "che arriva.",
        "photo": "Foto",
        "Trophy": "Trofei",
        "Cabinet.": "in vetrina.",
        "Highlight": "Momenti",
        "Reel.": "migliori.",
        "How I spend": "A cosa dedico",
        "my time.": "il mio tempo.",
        "Trying out": "Nuove cose",
        "new things.": "da provare.",
        "How it": "Com’è",
        "went.": "andata.",
        "Music": "Moodboard",
        "Moodboard.": "musicale.",
        "And the Oscar": "E l’Oscar",
        "goes to…": "va a…",
        "Ex Libris.": "Ex libris.",
        "Book of": "Libro del",
        "the Month.": "mese.",
        "Mini": "Mini",
        "Reviews.": "recensioni.",
        "Table": "Un tavolo",
        "for": "per",
        "one": "uno",
        "Worth a": "Vale un",
        "return trip.": "ritorno.",
        "Apps &": "App &",
        "Internet.": "web.",
        "For next": "Per il prossimo",
        "End of month,": "Fine del",
        "honestly.": "mese.",
        "Streak.": "Serie.",
        "THIS MONTH": "QUESTO MESE",
        "✦ 0/31": "✦ 0/31",
        "A MEMORY": "UN RICORDO",
        "THIS MONTH, I WANT TO FEEL —": "QUESTO MESE VOGLIO SENTIRMI —",
        "this month, I want to feel —": "questo mese voglio sentirmi —",
        "A LINE WORTH KEEPING": "UNA FRASE DA TENERE",
        "ONE MORE THING I WANT TO REMEMBER": "UN’ALTRA COSA CHE VOGLIO RICORDARE",
        "Hobby": "Hobby",
        "Gallery.": "galleria.",
        "Progress.": "progressi.",
        "HOBBY 01": "HOBBY 01",
        "HOBBY 02": "HOBBY 02",
        "HOBBY 03": "HOBBY 03",
        "HOBBY 04": "HOBBY 04",
        "NAME →": "Nome →",
        "WILL I CONTINUE?": "CONTINUERÒ?",
        "WHAT I LEARNED": "COSA HO IMPARATO",
        "WHERE →": "Dove →",
        "SCORECARD": "PAGELLA",
        "HOW WE MET": "COME CI SIAMO CONOSCIUTI",
        "N° 01": "N. 01",
        "N° 02": "N. 02",
        "The people": "Le persone",
        "in my corner.": "al mio fianco.",
        "In love with": "Innamorarsi",
        "life.": "della vita.",
        "Dear life,": "Cara vita,",
        "yours, always.": "tua, sempre.",
        "name:": "Nome:",
        "WRAPPED": "RIEPILOGO",
        "LIVE FROM MY HEADPHONES": "LIVE DALLE MIE CUFFIE",
        "TOP 5": "TOP 5",
        "SONG NAME - ARTIST": "TITOLO – ARTISTA",
        "HEADLINER": "HEADLINER",
        "DISCOVERY STAGE": "PALCO SCOPERTE",
        "LINER NOTES": "NOTE",
        "MIXTAPE": "MIXTAPE",
        "SCENE 01": "SCENA 01",
        "SCENE 02": "SCENA 02",
        "SCENE 03": "SCENA 03",
        "SCENE 04": "SCENA 04",
        "RATING →": "Valutazione →",
        "EX LIBRIS": "EX LIBRIS",
        "BREAKFAST": "COLAZIONE",
        "LUNCH": "PRANZO",
        "DINNER": "CENA",
        "RESTAURANT": "RISTORANTE",
        "OCCASION": "Occasione",
        "FOOD": "CIBO",
        "Postcards from the coast": "Cartoline dal viaggio",
        "STAMP": "FRANCOBOLLO",
        "Greetings from": "Un saluto da",
        "TO": "Per",
        "APP / PODCAST / SITE": "App / Podcast / Sito",
        "Rituals.": "Rituali.",
        "health & wellness": "salute & benessere",
        "A WORD FOR NEXT MONTH": "Una parola per il prossimo mese",
        "OUTLOOK": "PROSPETTIVA",
        "Vision": "Tavola",
        "Board.": "visiva.",
        "FINAL THOUGHTS": "PENSIERI FINALI",
        "— and let it lead the month.": "– e lascia che accompagni il mese.",
        "WHAT I WILL REMEMBER ABOUT IT": "COSA VOGLIO RICORDARE",
        "WHAT STAYED WITH ME": "COSA MI È RIMASTO",
        "body": "corpo",
        "mind": "mente",
        "love": "amore",
        "rest": "riposo",
        "title": "titolo",
        "name": "Nome",
        "My culinary": "Le mie creazioni",
        "creations.": "in cucina.",
        "week one": "settimana uno",
        "week two": "settimana due",
        "week three": "settimana tre",
        "week four": "settimana quattro",
        "with love,": "con affetto,",
        "The Monthly": "La storia",
        "Story.": "del mese.",
        "▢  self portrait": "▢  autoritratto",
        "▢  a moment": "▢  un momento",
        "a note →": "una nota →",
        "TOP STORY": "STORIA PRINCIPALE",
        "▢  the scene of the win": "▢  la scena della vittoria",
        "▢  scene 01": "▢  scena 01",
        "▢  scene 02": "▢  scena 02",
        "▢  scene 03": "▢  scena 03",
        "▢  scene 04": "▢  scena 04",
        "▢  the practice": "▢  la pratica",
        "▢  photo · large": "▢  Foto grande",
        "▢  photo · wide": "▢  Foto panoramica",
        "▢  photo · banner": "▢  Foto banner",
        "▢  the date": "▢  La data",
        "The": "Il",
        "APPRECIATION": "GRATITUDINE",
        "▢  a small joy": "▢  una piccola gioia",
        "sign here": "Firma qui",
        "▢  poster": "▢  poster",
        "writing": "Stile",
        "characters": "Personaggi",
        "plot": "Trama",
        "feeling": "Emozione",
        "A week,": "Una settimana",
        "on a plate.": "nel piatto.",
        "DAY": "GIORNO",
        "MON": "LUN",
        "TUE": "MAR",
        "WED": "MER",
        "THU": "GIO",
        "FRI": "VEN",
        "SAT": "SAB",
        "SUN": "DOM",
        "▢  the meal": "▢  Il piatto",
        "▢  the view": "▢  La vista",
        "a place": "Luogo",
        "Places": "Luoghi",
        "seen.": "visitati.",
        "Beauty": "Scaffale",
        "Shelf.": "beauty.",
        "▢  product": "▢  Prodotto",
        "▢  the meal of the month": "▢  Il piatto del mese",
        "CAFÉ / BAR": "CAFFÈ / BAR",
        "MORNING": "MATTINA",
        "— sunrise —": "— alba —",
        "AFTERNOON": "POMERIGGIO",
        "— midday —": "— mezzogiorno —",
        "NIGHT": "SERA",
        "— sundown —": "— tramonto —",
        "▢  become": "▢  Chi voglio diventare",
        "▢  the feeling": "▢  Come voglio sentirmi",
        "the feeling": "Come voglio sentirmi",
        "▢  dream": "▢  Sognare",
        "▢  wear": "▢  Indossare",
        "▢  place": "▢  Luoghi",
        "place": "Luoghi",
        "▢  read": "▢  Leggere",
        "▢  make": "▢  Fare",
        "▢  do": "▢  Agire",
        "— THE EDITORS": "— La redazione",
        "One month older and wiser.": "",
        "make": "Fare",
        "do": "Agire",
        "become": "Chi voglio diventare",
        "dream": "Sognare",
        "read": "Leggere",
        "wear": "Indossare",
        "PenPalooza": "PenPalooza",
        "FEATURE 1": "FEATURE 1",
        "FEATURE 2": "FEATURE 2",
        "M": "L",
        "T": "M",
        "W": "M",
        "F": "V",
        "S": "S",
        "This Month": "Questo mese",
        "VOL. I": "VOL. I"
    ]
}
