import Foundation

extension MagazineTemplateLocalization {
    static let frenchTranslations: [String: String] = [
        "Monthly Reset": "Bilan mensuel",
        "Tiny Wins": "Petites victoires",
        "Hobbies": "Loisirs",
        "Relationships": "Relations",
        "Playlist & Music": "Playlist & musique",
        "Cinema": "Cinéma",
        "Reading": "Lecture",
        "Food & Recipes": "Cuisine & recettes",
        "Travel & Places": "Voyages & lieux",
        "Favourites": "Favoris",
        "Favorites": "Favoris",
        "Goals": "Objectifs",
        "Affirmations & Goals": "Affirmations & objectifs",
        "ISSUE №01 · 2026": "NUMÉRO №01 · 2026",
        "ISSUE №01": "NUMÉRO №01",
        "Issue No.01": "NUMÉRO №01",
        "STAY IN EACH OTHER'S CHAPTERS": "RESTE DANS LES HISTOIRES DE TES AMIS.",
        "STAY PART OF YOUR FRIENDS' STORIES": "Reste dans les histoires de tes amis.",
        "“A magazine you make\nto grow together.”": "« Un magazine que tu crées\npour grandir ensemble. »",
        "\"A magazine you create to grow together.\"": "« Un magazine que tu crées pour grandir ensemble. »",
        "MAKE IT.  SHARE IT.  REMEMBER IT.": "CRÉE-LE.  PARTAGE-LE.  SOUVIENS-T’EN.",
        "CREATE IT. SHARE IT. REMEMBER IT.": "CRÉE-LE. PARTAGE-LE. SOUVIENS-T’EN.",
        "penpal · the editorial journal": "penpal · le journal éditorial",
        "MADE WITH LOVE": "FAIT AVEC AMOUR",
        "Contents.": "Sommaire.",
        "In this issue.": "Dans ce numéro.",
        "CONTENTS · IN THIS ISSUE": "SOMMAIRE · DANS CE NUMÉRO",
        "MONTHLY RESET": "BILAN MENSUEL",
        "MONTHLY RESET · DAILY REFLECTION": "BILAN MENSUEL · RÉFLEXION",
        "MONTHLY RESET · GRATITUDE": "BILAN MENSUEL · GRATITUDE",
        "MONTHLY RESET · LETTER": "BILAN MENSUEL · LETTRE",
        "MONTHLY RESET · LOOKING BACK": "BILAN MENSUEL · RÉTROSPECTIVE",
        "MONTHLY RESET · GROW TRACKER": "BILAN MENSUEL · ÉVOLUTION",
        "TINY WINS · THE DAILY ME": "PETITES VICTOIRES · MOI AU QUOTIDIEN",
        "TINY WINS · TROPHY CABINET": "PETITES VICTOIRES · TROPHÉES",
        "TINY WINS · STREAK": "PETITES VICTOIRES · SÉRIE",
        "TINY WINS · HIGHLIGHT REEL": "PETITES VICTOIRES · MOMENTS FORTS",
        "HOBBIES · TRACKER": "LOISIRS · SUIVI",
        "HOBBIES · A NEW TRY": "LOISIRS · NOUVEL ESSAI",
        "HOBBIES · GALLERY": "LOISIRS · GALERIE",
        "HOBBIES · PROGRESS": "LOISIRS · PROGRÈS",
        "RELATIONSHIPS · DATE REVIEW": "RELATIONS · BILAN DE RENCONTRE",
        "RELATIONSHIPS · THE RANKING": "RELATIONS · CLASSEMENT",
        "RELATIONSHIPS · APPRECIATION": "RELATIONS · APPRÉCIATION",
        "RELATIONSHIPS · IN LOVE WITH LIFE": "RELATIONS · AIMER LA VIE",
        "RELATIONSHIPS · NEWEST OBSESSION": "RELATIONS · NOUVELLE OBSESSION",
        "RELATIONSHIPS · PEOPLE I LOVE": "RELATIONS · PERSONNES QUE J’AIME",
        "PLAYLIST & MUSIC · WRAPPED": "PLAYLIST & MUSIQUE · RÉCAP",
        "PLAYLIST & MUSIC · FESTIVAL": "PLAYLIST & MUSIQUE · FESTIVAL",
        "PLAYLIST & MUSIC · LINER NOTES": "PLAYLIST & MUSIQUE · NOTES",
        "PLAYLIST & MUSIC · MIXTAPE": "PLAYLIST & MUSIQUE · MIXTAPE",
        "CINEMA · TICKET STUB": "CINÉMA · TICKET",
        "CINEMA · WATCH LOG": "CINÉMA · VISIONNAGES",
        "CINEMA · HIGHLIGHTS": "CINÉMA · MOMENTS FORTS",
        "READING · BOOKPLATE": "LECTURE · EX LIBRIS",
        "READING · MARGIN NOTES": "LECTURE · NOTES",
        "READING · MINI REVIEWS": "LECTURE · MINI AVIS",
        "READING · TBR STACK": "LECTURE · À LIRE",
        "FOOD & RECIPES · CULINARY CREATIONS": "CUISINE & RECETTES · CRÉATIONS",
        "FOOD & RECIPES · WEEK ON A PLATE": "CUISINE & RECETTES · SEMAINE DANS L’ASSIETTE",
        "FOOD & RECIPES · TABLE FOR ONE": "CUISINE & RECETTES · TABLE POUR UNE",
        "TRAVEL · POSTCARD": "VOYAGE · CARTE POSTALE",
        "TRAVEL · PLACES SEEN": "VOYAGE • LIEUX VUS",
        "FAVOURITES · BEAUTY SHELF": "FAVORIS · BEAUTÉ",
        "FAVOURITES · EDIBLE": "FAVORIS • GOURMANDS",
        "FAVOURITES · APPS & INTERNET": "FAVORIS • APPS & INTERNET",
        "FAVOURITES · RITUALS": "FAVORIS · RITUELS",
        "GOALS · OUTLOOK": "OBJECTIFS • À VENIR",
        "GOALS · AFFIRMATIONS": "OBJECTIFS • AFFIRMATIONS",
        "GOALS · VISION BOARD": "OBJECTIFS • TABLEAU DE VISION",
        "GOALS · SUMMARY": "OBJECTIFS · RÉSUMÉ",
        "DATE REVIEW": "BILAN DE RENCONTRE",
        "FIRST IMPRESSIONS": "PREMIÈRES IMPRESSIONS",
        "VIBE CHECK": "RESSENTI",
        "conversation": "conversation",
        "chemistry": "alchimie",
        "humor": "humour",
        "looks": "style",
        "presence": "présence",
        "manners": "manières",
        "overall": "global",
        "THE RANKING": "LE CLASSEMENT",
        "RANKING": "CLASSEMENT",
        "Ranking.": "classement.",
        "WOULD SEE AGAIN": "À REVOIR",
        "DO I WANT TO SEE THIS PERSON AGAIN?": "EST-CE QUE JE VEUX REVOIR CETTE PERSONNE ?",
        "YES": "OUI",
        "NO": "NON",
        "MAYBE": "PEUT-ÊTRE",
        "NEVER": "JAMAIS",
        "Y": "O",
        "N": "N",
        "TITLE": "TITRE",
        "AUTHOR": "AUTEUR",
        "GENRE": "GENRE",
        "DATE": "DATE",
        "NAME": "NOM",
        "THEIR NAME": "SON NOM",
        "AGE": "ÂGE",
        "OCCUPATION": "MÉTIER",
        "PLACE": "LIEU",
        "WHERE": "OÙ",
        "WHEN": "QUAND",
        "WITH": "AVEC",
        "YEAR": "ANNÉE",
        "RUNTIME": "DURÉE",
        "DIRECTED BY": "RÉALISÉ PAR",
        "RATING": "NOTE",
        "ROW": "RANG",
        "SEAT": "PLACE",
        "ALBUM": "ALBUM",
        "ARTIST": "ARTISTE",
        "FAVOURITE TRACK": "TITRE PRÉFÉRÉ",
        "TOP ARTIST": "ARTISTE N° 1",
        "TOP SONG": "CHANSON N° 1",
        "A MOOD": "L’AMBIANCE DU MOIS",
        "BRAND / PRODUCT": "MARQUE / PRODUIT",
        "WHY I LOVE IT →": "POURQUOI J’AIME →",
        "WHAT IT’S ABOUT": "DE QUOI ÇA PARLE",
        "What is it about": "DE QUOI ÇA PARLE",
        "Beauty Shelf.": "Mes favoris beauté.",
        "Brand / Product": "MARQUE / PRODUIT",
        "Why I love it →": "POURQUOI J’AIME →",
        "Rating →": "NOTE →",
        "Worth it.": "À refaire.",
        "Favorites • Food": "FAVORIS • GOURMANDS",
        "Favorites • Apps & Internet": "FAVORIS • APPS & INTERNET",
        "App / Podcast / Site": "APP / PODCAST / SITE",
        "Goals • Looking Ahead": "OBJECTIFS • À VENIR",
        "The Month Ahead.": "Le mois à venir.",
        "Perspective": "PERSPECTIVE",
        "One word for this month": "UN MOT POUR LE MOIS À VENIR",
        "write one word": "écris un mot",
        "For the next extraordinary month.": "Pour un mois exceptionnel.",
        "One word for next month": "UN MOT POUR LE PROCHAIN MOIS",
        "Intentions": "INTENTIONS",
        "Goals • Affirmations": "OBJECTIFS • AFFIRMATIONS",
        "Goals • Vision Board": "OBJECTIFS • TABLEAU DE VISION",
        "Vision Board.": "Tableau de vision.",
        "Travel • Places Visited": "VOYAGE • LIEUX VUS",
        "Places Visited.": "Lieux vus.",
        "large photo": "grande photo",
        "banner photo": "photo panoramique",
        "WHAT I ORDERED →": "CE QUE J’AI COMMANDÉ →",
        "WORTH RETURNING?": "À REFAIRE ?",
        "ATMOSPHERE": "AMBIANCE",
        "SERVICE": "SERVICE",
        "VALUE": "VALEUR",
        "WORK": "TRAVAIL",
        "HEALTH": "SANTÉ",
        "LOVE": "AMOUR",
        "MONEY": "ARGENT",
        "REST": "REPOS",
        "CRAFT": "CRÉATIVITÉ",
        "CREATIVE": "CRÉATIVITÉ",
        "INTENTIONS": "INTENTIONS",
        "cover": "couverture",
        "▢  photo": "▢  photo",
        "▢  cover": "▢  couverture",
        "▢  cover art": "▢  couverture",
        "▢  picture": "▢  image",
        "▢  portrait": "▢  portrait",
        "write here…": "écris ici…",
        "write one word here": "écris un mot",
        "write your word": "écris ton mot",
        "a few lines from you…": "quelques lignes de toi…",
        "your name": "ton nom",
        "LIVE · CAPTURE · SHARE": "VIVRE · CAPTURER · PARTAGER",
        "Monthly Reset.": "Bilan mensuel.",
        "A slow audit of the days behind — what stayed, what shifted, what is worth remembering.": "Un regard posé sur les jours passés — ce qui est resté, ce qui a bougé, ce qui mérite d’être gardé.",
        "SECTION": "SECTION",
        "FEELING": "RESSENTI",
        "ONE GOOD THING": "UNE BELLE CHOSE",
        "ONE HARD THING": "UNE CHOSE DIFFICILE",
        "ONE THING I LEARNED": "UNE CHOSE QUE J’AI APPRISE",
        "ONE THING I’M GRATEFUL FOR": "UNE CHOSE POUR LAQUELLE J’ÉPROUVE DE LA GRATITUDE",
        "HIGHS & LOWS": "HAUTS & BAS",
        "How the month": "Comment ce mois",
        "shaped me.": "m’a fait évoluer.",
        "THE HIGHS": "LES HAUTS",
        "THE LOWS": "LES BAS",
        "MONTH IN ONE FRAME": "CE MOIS EN UNE IMAGE",
        "▢  a high moment": "▢  un moment fort",
        "▢  a low moment": "▢  un moment difficile",
        "▢  one image that holds the whole month": "▢  une image qui raconte le mois",
        "GRATITUDE": "GRATITUDE",
        "What I am": "Ce pour quoi",
        "grateful for.": "j’éprouve de la gratitude.",
        "small things": "petites choses",
        "people": "personnes",
        "places": "lieux",
        "moments": "moments",
        "things you gave me this month —": "ce que ce mois a apporté —",
        "A LETTER": "UNE LETTRE",
        "Dear month,": "Cher mois,",
        "a letter to the month from me.": "une lettre à ce mois.",
        "LOOKING BACK": "EN REGARDANT EN ARRIÈRE",
        "A WORD FOR THE MONTH": "UN MOT POUR CE MOIS",
        "one word": "un mot",
        "THE FIRST THING I WANT TO REMEMBER…": "LA PREMIÈRE CHOSE DONT JE VEUX ME SOUVENIR…",
        "WHAT I AM READY TO CHANGE…": "CE QUE JE VEUX CHANGER…",
        "WHAT I LEARNED ABOUT MYSELF…": "CE QUE J’AI APPRIS SUR MOI…",
        "Tiny Wins.": "Petites victoires.",
        "Small triumphs, printed in earnest — the quiet headlines of an honest week.": "De petites victoires à partager — les temps forts d’un beau mois.",
        "Small wins to share — the gentle headlines of a good month.": "De petites victoires à partager — les temps forts d’un beau mois.",
        "Small wins to share — the headlines of a good month.": "De petites victoires à partager — les temps forts d’un beau mois.",
        "Local human has a very good": "Une personne ordinaire connaît un",
        "month.": "mois exceptionnel.",
        "A MONTH OF TINY VICTORIES": "UN MOIS DE PETITES VICTOIRES",
        "WIN OF THE MONTH": "VICTOIRE DU MOIS",
        "EDITORIAL — WHAT MADE THIS MONTH A WIN": "ÉDITORIAL — CE QUI A RENDU CE MOIS SPÉCIAL",
        "WHAT HAPPENED →": "CE QUI S’EST PASSÉ →",
        "AWARD Nº 01": "PRIX N° 01",
        "AWARD Nº 02": "PRIX N° 02",
        "AWARD Nº 03": "PRIX N° 03",
        "AWARD Nº 04": "PRIX N° 04",
        "FOR": "POUR",
        "Hobbies.": "Loisirs.",
        "The slow practice of becoming better at something you love.": "Le plaisir de progresser dans quelque chose que tu aimes.",
        "The practice of becoming better at something you love.": "Le plaisir de progresser dans quelque chose que tu aimes.",
        "Skill": "Où j’en",
        "consistency": "régularité",
        "confidence": "confiance",
        "creativity": "créativité",
        "speed": "vitesse",
        "technique": "technique",
        "theory": "théorie",
        "effort": "effort",
        "cost": "coût",
        "difficulty": "difficulté",
        "reward": "récompense",
        "Relationships.": "Relations.",
        "Notes on being known — the people in your corner, on the page.": "Une ode aux personnes à tes côtés, avec quelques potins en marge.",
        "An ode to the people by your side, with a little gossip in the margins.": "Une ode aux personnes à tes côtés, avec quelques potins en marge.",
        "WHY I LOVE THEM": "POURQUOI JE L’AIME",
        "WHY I LOVE THEM →": "POURQUOI JE L’AIME →",
        "why I love them →": "pourquoi je l’aime →",
        "first noticed": "première fois que je l’ai remarqué",
        "why they’re hot": "ce qui m’attire chez cette personne",
        "what I already know about them": "ce que je sais déjà de cette personne",
        "Playlist & Music.": "Playlist & musique.",
        "Liner notes from the month — the songs that scored your days.": "La bande-son du mois — les chansons qui ont accompagné tes journées.",
        "Notes of the month — the songs that carried these days.": "La bande-son du mois — les chansons qui ont accompagné tes journées.",
        "ON REPEAT": "EN BOUCLE",
        "a line about why →": "pourquoi ce choix →",
        "artist · song": "artiste · chanson",
        "when I am in my feelings": "quand je suis triste",
        "when I am happy": "quand je suis de bonne humeur",
        "when I am in love": "quand je pense à l’amour",
        "artist:": "artiste :",
        "song:": "chanson :",
        "Cinema.": "Cinéma.",
        "Tickets, scenes, scores — the dark room remembered.": "Tickets, scènes, notes — pour se souvenir des performances dignes d’un Oscar.",
        "Tickets, scenes, scores — remembering Oscar-worthy perfomances.": "Tickets, scènes, notes — pour se souvenir des performances dignes d’un Oscar.",
        "Tickets, scenes, scores — remembering Oscar-worthy performances.": "Tickets, scènes, notes — pour se souvenir des performances dignes d’un Oscar.",
        "ADMIT ONE": "ENTRÉE",
        "WATCH LOG": "JOURNAL DES FILMS",
        "MOVIE HIGHLIGHTS": "MOMENTS DE CINÉMA",
        "Reading.": "Lecture.",
        "Stories worth being remembered — pages, lines, and the lives they made.": "Des histoires qui restent — des pages, des lignes et des mondes qu’elles ont ouverts.",
        "Stories worth remembering — pages, lines, and the lives they opened.": "Des histoires qui restent — des pages, des lignes et des mondes qu’elles ont ouverts.",
        "Food & Recipes.": "Cuisine & recettes.",
        "From the kitchen — the dishes, the table, the small rituals of the week.": "Depuis la cuisine — les plats, la table et les petits rituels du mois.",
        "From the kitchen — the dishes, the table, the small rituals of the month.": "Depuis la cuisine — les plats, la table et les petits rituels du mois.",
        "Travel & Places.": "Voyages & lieux.",
        "Postcards from the coast — and everywhere else worth remembering.": "Des cartes postales de tous les endroits qui méritaient le détour.",
        "Postcards from everywhere worth exploring and remembering.": "Des cartes postales de tous les endroits qui méritaient le détour.",
        "Favourites.": "Favoris.",
        "Favorites.": "Favoris.",
        "The small obsessions — the things kept close, this month.": "Tout ce que j’ai aimé ce mois-ci.",
        "Everything I loved this month.": "Tout ce que j’ai aimé ce mois-ci.",
        "Affirmations & Goals.": "Affirmations & objectifs.",
        "The intentions to carry into the next month — said quietly, said clearly.": "Des intentions à emporter dans le mois à venir — formulées avec douceur et clarté.",
        "The intentions to carry into next month — softly spoken, clearly held.": "Des intentions à emporter dans le mois à venir — formulées avec douceur et clarté.",
        "A small triumph!": "Une petite victoire !",
        "CORRESPONDENT NOTE": "NOTE DE CORRESPONDANCE",
        "How I grew.": "Comment j’ai\ngrandi.",
        "END OF MONTH, HONESTLY.": "FIN DU MOIS",
        "End of": "Fin du",
        "month": "mois",
        "People I love.": "Les gens\nque j’aime.",
        "My Month": "Mon mois",
        "in Sound.": "en musique.",
        "Album of": "Album du",
        "the Week.": "mois.",
        "The film of": "Le film de la",
        "the night.": "soirée.",
        "What I": "Ce que j’ai",
        "watched.": "regardé.",
        "To be": "À",
        "read.": "lire.",
        "Wish you": "J’aimerais que tu",
        "were here.": "sois ici.",
        "The month": "Le mois",
        "ahead.": "à venir.",
        "THE DAILY ME": "MOI AU QUOTIDIEN",
        "TROPHY CABINET": "VITRINE DES TROPHÉES",
        "HIGHLIGHT REEL": "MOMENTS FORTS",
        "HOBBY TRACKER": "SUIVI DES LOISIRS",
        "A NEW TRY": "UN NOUVEL ESSAI",
        "HOBBY GALLERY": "GALERIE DES LOISIRS",
        "PROGRESS TRACKER": "SUIVI DES PROGRÈS",
        "APPRECIATION POST": "MOT D’APPRÉCIATION",
        "PEOPLE I LOVE": "PERSONNES QUE J’AIME",
        "NEWEST OBSESSION": "NOUVELLE OBSESSION",
        "MY RECOMMENDATIONS": "MES RECOMMANDATIONS",
        "MY ROUTINES": "MES ROUTINES",
        "BOOKPLATE": "EX LIBRIS",
        "MARGIN NOTES": "NOTES EN MARGE",
        "TO BE READ": "À LIRE",
        "CULINARY CREATIONS": "CRÉATIONS CULINAIRES",
        "WEEK ON A PLATE": "SEMAINE DANS L’ASSIETTE",
        "TABLE FOR ONE": "TABLE POUR UNE",
        "POSTCARD": "CARTE POSTALE",
        "PLACES SEEN": "LIEUX VUS",
        "BEAUTY SHELF": "MES FAVORIS BEAUTÉ",
        "EDIBLE FAVOURITES": "FAVORIS GOURMANDS",
        "WORD OF THE MONTH": "MOT DU MOIS",
        "VISION BOARD": "TABLEAU DE VISION",
        "AFFIRMATIONS": "AFFIRMATIONS",
        "photo": "photo",
        "Trophy": "Vitrine",
        "Cabinet.": "des trophées.",
        "Highlight": "Moments",
        "Reel.": "forts.",
        "How I spend": "Comment je passe",
        "my time.": "mon temps.",
        "Trying out": "Essayer",
        "new things.": "de nouvelles choses.",
        "How it": "Comment ça",
        "went.": "s’est passé.",
        "Crush": "Journal",
        "Diary.": "de coup de cœur.",
        "Music": "Ambiances",
        "Moodboard.": "musicales.",
        "And the Oscar": "Et l’Oscar",
        "goes to…": "revient à…",
        "Ex Libris.": "Ex libris.",
        "Book of": "Livre du",
        "the Month.": "mois.",
        "Mini": "Mini",
        "Reviews.": "avis.",
        "Table": "Table",
        "for": "pour",
        "one": "une",
        "Worth a": "À",
        "return trip.": "refaire.",
        "Apps &": "Apps &",
        "Internet.": "Internet.",
        "For next": "Pour un",
        "End of month,": "Fin du",
        "honestly.": "mois.",
        "Streak.": "Série.",
        "THIS MONTH": "CE MOIS-CI",
        "✦ 0/31": "✦ 0/31",
        "A MEMORY": "UN SOUVENIR",
        "THIS MONTH, I WANT TO FEEL —": "CE MOIS-CI, JE VEUX ME SENTIR —",
        "this month, I want to feel —": "ce mois-ci, je veux me sentir —",
        "A LINE WORTH KEEPING": "UNE LIGNE À GARDER",
        "ONE MORE THING I WANT TO REMEMBER": "UNE CHOSE DE PLUS À RETENIR",
        "Hobby": "Galerie de",
        "Gallery.": "loisirs.",
        "Progress.": "suis.",
        "HOBBY 01": "LOISIR 01",
        "HOBBY 02": "LOISIR 02",
        "HOBBY 03": "LOISIR 03",
        "HOBBY 04": "LOISIR 04",
        "NAME →": "NOM →",
        "WILL I CONTINUE?": "JE CONTINUE ?",
        "WHAT I LEARNED": "CE QUE J’AI APPRIS",
        "WHERE →": "OÙ →",
        "SCORECARD": "FICHE DE SCORE",
        "HOW WE MET": "COMMENT ON S’EST RENCONTRÉS",
        "N° 01": "N° 01",
        "N° 02": "N° 02",
        "The people": "Les personnes",
        "in my corner.": "à mes côtés.",
        "In love with": "Aimer",
        "life.": "la vie.",
        "Dear life,": "Chère vie,",
        "yours, always.": "à toi, toujours.",
        "name:": "nom :",
        "WRAPPED": "RÉCAP",
        "LIVE FROM MY HEADPHONES": "EN DIRECT DE MON CASQUE",
        "TOP 5": "TOP 5",
        "SONG NAME - ARTIST": "TITRE · ARTISTE",
        "HEADLINER": "TÊTE D’AFFICHE",
        "DISCOVERY STAGE": "SCÈNE DÉCOUVERTE",
        "LINER NOTES": "NOTES",
        "MIXTAPE": "MIXTAPE",
        "SCENE 01": "SCÈNE 01",
        "SCENE 02": "SCÈNE 02",
        "SCENE 03": "SCÈNE 03",
        "SCENE 04": "SCÈNE 04",
        "RATING →": "NOTE →",
        "EX LIBRIS": "EX LIBRIS",
        "BREAKFAST": "PETIT-DÉJEUNER",
        "LUNCH": "DÉJEUNER",
        "DINNER": "DÎNER",
        "RESTAURANT": "RESTAURANT",
        "OCCASION": "OCCASION",
        "FOOD": "CUISINE",
        "STAMP": "TIMBRE",
        "Greetings from": "Un petit mot de",
        "TO": "À",
        "APP / PODCAST / SITE": "APP / PODCAST / SITE",
        "Rituals.": "Rituels.",
        "health & wellness": "santé & bien-être",
        "A WORD FOR NEXT MONTH": "UN MOT POUR LE PROCHAIN MOIS",
        "OUTLOOK": "PERSPECTIVE",
        "Vision": "Tableau",
        "Board.": "de vision.",
        "FINAL THOUGHTS": "PENSÉES FINALES",
        "— and let it lead the month.": "— et laisse-le guider le mois.",
        "WHAT I WILL REMEMBER ABOUT IT": "CE QUE J’EN RETIENS",
        "WHAT STAYED WITH ME": "CE QUE J’EN RETIENS",
        "body": "corps",
        "mind": "esprit",
        "love": "amour",
        "rest": "repos",
        "title": "titre",
        "name": "nom",
        "My culinary": "Mes créations",
        "creations.": "en cuisine.",
        "week one": "semaine 1",
        "week two": "semaine 2",
        "week three": "semaine 3",
        "week four": "semaine 4",
        "with love,": "avec amour,",
        "The Monthly": "L’histoire",
        "Story.": "du mois.",
        "▢  self portrait": "▢  autoportrait",
        "▢  a moment": "▢  un moment",
        "a note →": "une note →",
        "TOP STORY": "GRAND TITRE",
        "▢  the scene of the win": "▢  le moment de la victoire",
        "▢  scene 01": "▢  scène 01",
        "▢  scene 02": "▢  scène 02",
        "▢  scene 03": "▢  scène 03",
        "▢  scene 04": "▢  scène 04",
        "▢  the practice": "▢  en pratique",
        "▢  photo · large": "▢  grande photo",
        "▢  photo · wide": "▢  photo grand format",
        "▢  photo · banner": "▢  photo panoramique",
        "▢  the date": "▢  le rendez-vous",
        "The": "Le",
        "APPRECIATION": "APPRÉCIATION",
        "▢  a small joy": "▢  une petite joie",
        "sign here": "signature",
        "▢  poster": "▢  affiche",
        "writing": "écriture",
        "characters": "personnages",
        "plot": "intrigue",
        "feeling": "ressenti",
        "A week,": "Une semaine",
        "on a plate.": "dans l’assiette.",
        "DAY": "JOUR",
        "MON": "LUN",
        "TUE": "MAR",
        "WED": "MER",
        "THU": "J",
        "FRI": "VEN",
        "SAT": "SAM",
        "SUN": "D",
        "▢  the meal": "▢  le repas",
        "▢  the view": "▢  la vue",
        "a place": "un lieu",
        "Places": "Lieux",
        "seen.": "vus.",
        "Beauty": "Mes favoris",
        "Shelf.": "beauté.",
        "▢  product": "▢  produit",
        "▢  the meal of the month": "▢  le repas du mois",
        "CAFÉ / BAR": "CAFÉ / BAR",
        "MORNING": "MATIN",
        "— sunrise —": "— lever du soleil —",
        "AFTERNOON": "APRÈS-MIDI",
        "— midday —": "— midi —",
        "NIGHT": "SOIR",
        "— sundown —": "— coucher du soleil —",
        "▢  become": "▢  devenir",
        "▢  the feeling": "▢  ressentir",
        "the feeling": "ressentir",
        "▢  dream": "▢  rêver",
        "▢  wear": "▢  porter",
        "▢  place": "▢  aller",
        "place": "aller",
        "▢  read": "▢  lire",
        "▢  make": "▢  faire",
        "▢  do": "▢  agir",
        "— THE EDITORS": "— LA RÉDACTION",
        "— THE EDITOR": "— LA RÉDACTION",
        "One month older and wiser.": "",
        "make": "faire",
        "do": "agir",
        "become": "devenir",
        "dream": "rêver",
        "read": "lire",
        "wear": "porter",
        "PenPalooza": "PenPalooza",
        "FEATURE 1": "FILM 1",
        "FEATURE 2": "FILM 2",
        "M": "L",
        "T": "M",
        "W": "M",
        "F": "V",
        "S": "S",
        "This Month": "Ce mois-ci",
        "VOL. I": "VOL. I"
    ]
}
