import Foundation

extension MagazineTemplateLocalization {
    static let italianTranslations: [String: String] = [
        "Monthly Reset": "Reset mensile",
        "Tiny Wins": "Piccole vittorie",
        "Hobbies": "Hobby",
        "Relationships": "Relazioni",
        "Playlist & Music": "Playlist & musica",
        "Cinema": "Cinema",
        "Reading": "Letture",
        "Food & Recipes": "Cibo & ricette",
        "Travel & Places": "Viaggi & luoghi",
        "Favourites": "Preferiti",
        "Affirmations & Goals": "Affermazioni",
        "ISSUE №01 · 2026": "NUMERO №01 · 2026",
        "ISSUE №01": "NUMERO №01",
        "STAY IN EACH OTHER'S CHAPTERS": "RESTATE NEI CAPITOLI L’UNO DELL’ALTRA",
        "STAY PART OF YOUR FRIENDS' STORIES": "Resta parte delle storie dei tuoi amici.",
        "“A magazine you make\nto grow together.”": "“Un magazine che create\nper crescere insieme.”",
        "MAKE IT.  SHARE IT.  REMEMBER IT.": "CREALO.  CONDIVIDILO.  RICORDALO.",
        "penpal · the editorial journal": "penpal · il diario editoriale",
        "MADE WITH LOVE": "FATTO CON AMORE",
        "Contents.": "Indice.",
        "In this issue.": "In questo numero.",
        "CONTENTS · IN THIS ISSUE": "INDICE · IN QUESTO NUMERO",
        "MONTHLY RESET": "RESET MENSILE",
        "MONTHLY RESET · DAILY REFLECTION": "RESET MENSILE · RIFLESSIONE",
        "MONTHLY RESET · GRATITUDE": "RESET MENSILE · GRATITUDINE",
        "MONTHLY RESET · LETTER": "RESET MENSILE · LETTERA",
        "MONTHLY RESET · LOOKING BACK": "RESET MENSILE · RICORDI",
        "MONTHLY RESET · GROW TRACKER": "RESET MENSILE · CRESCITA",
        "TINY WINS · THE DAILY ME": "PICCOLE VITTORIE · CRONACHE DI ME",
        "TINY WINS · TROPHY CABINET": "PICCOLE VITTORIE · TROFEI",
        "TINY WINS · STREAK": "PICCOLE VITTORIE · SERIE",
        "TINY WINS · HIGHLIGHT REEL": "PICCOLE VITTORIE · HIGHLIGHT",
        "HOBBIES · TRACKER": "HOBBY · TRACKER",
        "HOBBIES · A NEW TRY": "HOBBY · NUOVA PROVA",
        "HOBBIES · GALLERY": "HOBBY · GALLERIA",
        "HOBBIES · PROGRESS": "HOBBY · PROGRESSI",
        "RELATIONSHIPS · DATE REVIEW": "RELAZIONI · RECENSIONE DATE",
        "RELATIONSHIPS · THE RANKING": "RELAZIONI · CLASSIFICA",
        "RELATIONSHIPS · APPRECIATION": "RELAZIONI · APPREZZAMENTO",
        "RELATIONSHIPS · IN LOVE WITH LIFE": "RELAZIONI · INNAMORATA DELLA VITA",
        "RELATIONSHIPS · NEWEST OBSESSION": "RELAZIONI · NUOVA OSSESSIONE",
        "RELATIONSHIPS · PEOPLE I LOVE": "RELAZIONI · PERSONE CHE AMO",
        "PLAYLIST & MUSIC · WRAPPED": "PLAYLIST & MUSICA · RIEPILOGO",
        "PLAYLIST & MUSIC · FESTIVAL": "PLAYLIST & MUSICA · FESTIVAL",
        "PLAYLIST & MUSIC · LINER NOTES": "PLAYLIST & MUSICA · NOTE",
        "PLAYLIST & MUSIC · MIXTAPE": "PLAYLIST & MUSICA · MIXTAPE",
        "CINEMA · TICKET STUB": "CINEMA · BIGLIETTO",
        "CINEMA · WATCH LOG": "CINEMA · DIARIO",
        "CINEMA · HIGHLIGHTS": "CINEMA · HIGHLIGHT",
        "READING · BOOKPLATE": "LETTURE · EX LIBRIS",
        "READING · MARGIN NOTES": "LETTURE · NOTE A MARGINE",
        "READING · MINI REVIEWS": "LETTURE · MINI RECENSIONI",
        "READING · TBR STACK": "LETTURE · DA LEGGERE",
        "FOOD & RECIPES · CULINARY CREATIONS": "CIBO & RICETTE · CREAZIONI",
        "FOOD & RECIPES · WEEK ON A PLATE": "CIBO & RICETTE · SETTIMANA NEL PIATTO",
        "FOOD & RECIPES · TABLE FOR ONE": "CIBO & RICETTE · TAVOLO PER UNA",
        "TRAVEL · POSTCARD": "VIAGGI · CARTOLINA",
        "TRAVEL · PLACES SEEN": "VIAGGI · LUOGHI VISTI",
        "FAVOURITES · BEAUTY SHELF": "PREFERITI · BEAUTY SHELF",
        "FAVOURITES · EDIBLE": "PREFERITI · SAPORI",
        "FAVOURITES · APPS & INTERNET": "PREFERITI · APP & INTERNET",
        "FAVOURITES · RITUALS": "PREFERITI · RITUALI",
        "GOALS · OUTLOOK": "OBIETTIVI · PROSPETTIVA",
        "GOALS · AFFIRMATIONS": "OBIETTIVI · AFFERMAZIONI",
        "GOALS · VISION BOARD": "OBIETTIVI · VISION BOARD",
        "GOALS · SUMMARY": "OBIETTIVI · SOMMARIO",
        "THE DAILY ME": "CRONACHE DI ME",
        "TROPHY CABINET": "TROFEI",
        "HIGHLIGHT REEL": "HIGHLIGHT",
        "HOBBY TRACKER": "TRACKER HOBBY",
        "A NEW TRY": "UNA NUOVA PROVA",
        "HOBBY GALLERY": "GALLERIA HOBBY",
        "PROGRESS TRACKER": "TRACCIATORE DEI PROGRESSI",
        "DATE REVIEW": "RECENSIONE DATE",
        "FIRST IMPRESSIONS": "PRIME IMPRESSIONI",
        "VIBE CHECK": "VIBE CHECK",
        "conversation": "conversazione",
        "chemistry": "chimica",
        "humor": "umorismo",
        "looks": "aspetto",
        "presence": "presenza",
        "manners": "modi",
        "overall": "totale",
        "THE RANKING": "LA CLASSIFICA",
        "Ranking.": "La classifica.",
        "WOULD SEE AGAIN": "RIVEDREI",
        "DO I WANT TO SEE THIS PERSON AGAIN?": "VOGLIO RIVEDERE QUESTA PERSONA?",
        "YES": "SÌ",
        "NO": "NO",
        "MAYBE": "FORSE",
        "NEVER": "MAI",
        "Y": "S",
        "N": "N",
        "APPRECIATION POST": "POST DI APPREZZAMENTO",
        "PEOPLE I LOVE": "PERSONE CHE AMO",
        "NEWEST OBSESSION": "NUOVA OSSESSIONE",
        "MY RECOMMENDATIONS": "I MIEI CONSIGLI",
        "MY ROUTINES": "LE MIE ROUTINE",
        "BOOKPLATE": "EX LIBRIS",
        "MARGIN NOTES": "NOTE A MARGINE",
        "TO BE READ": "DA LEGGERE",
        "CULINARY CREATIONS": "CREAZIONI",
        "WEEK ON A PLATE": "SETTIMANA NEL PIATTO",
        "TABLE FOR ONE": "TAVOLO PER UNA",
        "POSTCARD": "CARTOLINA",
        "PLACES SEEN": "LUOGHI VISTI",
        "BEAUTY SHELF": "BEAUTY SHELF",
        "EDIBLE FAVOURITES": "PREFERITI DA MANGIARE",
        "WORD OF THE MONTH": "PAROLA DEL MESE",
        "VISION BOARD": "VISION BOARD",
        "AFFIRMATIONS": "AFFERMAZIONI",
        "TITLE": "TITOLO",
        "AUTHOR": "AUTORE",
        "GENRE": "GENERE",
        "DATE": "DATA",
        "NAME": "NOME",
        "THEIR NAME": "IL LORO NOME",
        "AGE": "ETÀ",
        "OCCUPATION": "OCCUPAZIONE",
        "PLACE": "LUOGO",
        "WHERE": "DOVE",
        "WHEN": "QUANDO",
        "WITH": "CON",
        "YEAR": "ANNO",
        "RUNTIME": "DURATA",
        "DIRECTED BY": "REGIA",
        "RATING": "VOTO",
        "ROW": "FILA",
        "SEAT": "POSTO",
        "ALBUM": "ALBUM",
        "ARTIST": "ARTISTA",
        "FAVOURITE TRACK": "BRANO PREFERITO",
        "TOP ARTIST": "ARTISTA TOP",
        "TOP SONG": "BRANO TOP",
        "A MOOD": "SENTIMENTO",
        "BRAND / PRODUCT": "BRAND / PRODOTTO",
        "WHY I LOVE IT →": "PERCHÉ LO AMO →",
        "WHAT IT’S ABOUT": "DI COSA PARLA",
        "WHAT I ORDERED →": "COSA HO ORDINATO →",
        "WORTH RETURNING?": "DA TORNARCI?",
        "ATMOSPHERE": "ATMOSFERA",
        "SERVICE": "SERVIZIO",
        "VALUE": "VALORE",
        "WORK": "LAVORO",
        "HEALTH": "SALUTE",
        "LOVE": "AMORE",
        "MONEY": "SOLDI",
        "REST": "RIPOSO",
        "CRAFT": "CREATIVITÀ",
        "INTENTIONS": "INTENZIONI",
        "cover": "copertina",
        "▢  photo": "▢  foto",
        "▢  cover": "▢  copertina",
        "▢  cover art": "▢  cover",
        "▢  picture": "▢  immagine",
        "▢  portrait": "▢  ritratto",
        "write here…": "scrivi qui…",
        "write one word here": "scrivi una parola",
        "write your word": "scrivi la tua parola",
        "a few lines from you…": "qualche riga da te…",
        "your name": "il tuo nome",
        "LIVE · CAPTURE · SHARE": "VIVI · CATTURA · CONDIVIDI",
        "Monthly Reset.": "Reset mensile.",
        "A slow audit of the days behind — what stayed, what shifted, what is worth remembering.": "Uno sguardo ai giorni passati — cosa è rimasto, cosa è cambiato, cosa vale la pena ricordare.",
        "SECTION": "SEZIONE",
        "FEELING": "SENSAZIONE",
        "ONE GOOD THING": "UNA COSA BELLA",
        "ONE HARD THING": "UNA COSA DIFFICILE",
        "ONE THING I LEARNED": "UNA COSA CHE HO IMPARATO",
        "ONE THING I’M GRATEFUL FOR": "UNA COSA PER CUI SONO GRATA",
        "HIGHS & LOWS": "ALTI & BASSI",
        "How the month": "Come questo mese",
        "shaped me.": "mi ha cambiata.",
        "THE HIGHS": "GLI ALTI",
        "THE LOWS": "I BASSI",
        "MONTH IN ONE FRAME": "QUESTO MESE IN UN’IMMAGINE",
        "▢  a high moment": "▢  un momento bello",
        "▢  a low moment": "▢  un momento difficile",
        "▢  one image that holds the whole month": "▢  un’immagine che racconta tutto il mese",
        "GRATITUDE": "GRATITUDINE",
        "What I am": "Per cosa sono",
        "grateful for.": "grata.",
        "small things": "piccole cose",
        "people": "persone",
        "places": "luoghi",
        "moments": "momenti",
        "things you gave me this month —": "cose che questo mese ha portato con sé —",
        "A LETTER": "UNA LETTERA",
        "Dear month,": "Caro mese,",
        "a letter to the month from me.": "una lettera al mese.",
        "LOOKING BACK": "GUARDANDO INDIETRO",
        "A WORD FOR THE MONTH": "UNA PAROLA PER QUESTO MESE",
        "one word": "una parola",
        "THE FIRST THING I WANT TO REMEMBER…": "LA PRIMA COSA CHE VOGLIO RICORDARE…",
        "WHAT I AM READY TO CHANGE…": "COSA SONO PRONTA A CAMBIARE…",
        "WHAT I LEARNED ABOUT MYSELF…": "COSA HO IMPARATO SU DI ME…",
        "Tiny Wins.": "Piccole vittorie.",
        "Small triumphs, printed in earnest — the quiet headlines of an honest week.": "Piccole vittorie da condividere — i titoli gentili di un mese riuscito.",
        "Small wins to share — the gentle headlines of a good month.": "Piccole vittorie da condividere — i titoli gentili di un mese riuscito.",
        "Local human has a very good": "Una persona locale ha un",
        "month.": "mese straordinario.",
        "A MONTH OF TINY VICTORIES": "UN MESE DI PICCOLE VITTORIE",
        "WIN OF THE MONTH": "VITTORIA DEL MESE",
        "EDITORIAL — WHAT MADE THIS MONTH A WIN": "EDITORIALE — COSA HA RESO QUESTO MESE UNA VITTORIA",
        "WHAT HAPPENED →": "COSA È SUCCESSO →",
        "AWARD Nº 01": "PREMIO N. 01",
        "AWARD Nº 02": "PREMIO N. 02",
        "AWARD Nº 03": "PREMIO N. 03",
        "AWARD Nº 04": "PREMIO N. 04",
        "FOR": "PER",
        "Hobbies.": "Hobby.",
        "The slow practice of becoming better at something you love.": "Il progresso lento in qualcosa che ami.",
        "Skill": "Come sto",
        "consistency": "costanza",
        "confidence": "sicurezza",
        "creativity": "creatività",
        "speed": "velocità",
        "technique": "tecnica",
        "theory": "teoria",
        "effort": "impegno",
        "cost": "costo",
        "difficulty": "difficoltà",
        "reward": "ricompensa",
        "Relationships.": "Relazioni.",
        "Notes on being known — the people in your corner, on the page.": "Un’ode alle persone al tuo fianco, con un po’ di gossip ai margini.",
        "An ode to the people by your side, with a little gossip in the margins.": "Un’ode alle persone al tuo fianco, con un po’ di gossip ai margini.",
        "WHY I LOVE THEM": "PERCHÉ LE AMO",
        "WHY I LOVE THEM →": "PERCHÉ LE AMO →",
        "why I love them →": "perché le amo →",
        "first noticed": "notato/a per la prima volta",
        "why they’re hot": "cosa lo/la rende figo/a",
        "what I already know about them": "cosa so già di lui/lei",
        "Playlist & Music.": "Playlist & musica.",
        "Liner notes from the month — the songs that scored your days.": "Note del mese — le canzoni che hanno accompagnato questi giorni.",
        "Notes of the month — the songs that carried these days.": "Note del mese — le canzoni che hanno accompagnato questi giorni.",
        "ON REPEAT": "IN LOOP",
        "a line about why →": "una riga sul perché →",
        "artist · song": "artista · canzone",
        "when I am in my feelings": "quando sono triste",
        "when I am happy": "quando sono felice",
        "when I am in love": "quando sono innamorata",
        "artist:": "artista:",
        "song:": "canzone:",
        "Cinema.": "Cinema.",
        "Tickets, scenes, scores — the dark room remembered.": "Biglietti, scene, voti — tutto quello che resta della serata cinema.",
        "ADMIT ONE": "INGRESSO",
        "WATCH LOG": "DIARIO FILM",
        "MOVIE HIGHLIGHTS": "HIGHLIGHT DEL FILM",
        "Reading.": "Letture.",
        "Stories worth being remembered — pages, lines, and the lives they made.": "Storie che meritano di restare — pagine, frasi e le vite che hanno acceso.",
        "Stories worth remembering — pages, lines, and the lives they opened.": "Storie che meritano di restare — pagine, frasi e le vite che hanno acceso.",
        "Food & Recipes.": "Cibo & ricette.",
        "From the kitchen — the dishes, the table, the small rituals of the week.": "Dalla cucina — i piatti, la tavola, i piccoli rituali del mese.",
        "From the kitchen — the dishes, the table, the small rituals of the month.": "Dalla cucina — i piatti, la tavola, i piccoli rituali del mese.",
        "Travel & Places.": "Viaggi & luoghi.",
        "Postcards from the coast — and everywhere else worth remembering.": "Cartoline dalla costa — e da ogni luogo che valeva la pena esplorare.",
        "Postcards from everywhere worth exploring and remembering.": "Cartoline da ogni luogo che valeva la pena esplorare.",
        "Favourites.": "Preferiti.",
        "The small obsessions — the things kept close, this month.": "Tutto ciò che ho amato questo mese.",
        "Affirmations & Goals.": "Affermazioni & obiettivi.",
        "The intentions to carry into the next month — said quietly, said clearly.": "Le intenzioni da portare nel prossimo mese — dette piano, dette con chiarezza.",
        "A small triumph!": "Un piccolo trionfo!",
        "CORRESPONDENT NOTE": "NOTA DEL CORRISPONDENTE",
        "How I grew.": "Come sono\ncresciuta.",
        "END OF MONTH, HONESTLY.": "FINE DEL MESE",
        "End of": "Fine del",
        "month": "mese",
        "People I love.": "Persone\nche amo.",
        "Crush": "Crush",
        "Diary.": "Diary.",
        "My Month": "Il mio mese",
        "in Sound.": "in musica.",
        "Album of": "Album del",
        "the Week.": "mese.",
        "The film of": "Il film della",
        "the night.": "serata.",
        "What I": "Cosa ho",
        "watched.": "guardato.",
        "To be": "Da",
        "read.": "leggere.",
        "Wish you": "Vorrei che tu",
        "were here.": "fossi qui.",
        "The month": "Il mese",
        "ahead.": "che arriva.",
        "photo": "foto",
        "Trophy": "Trofei",
        "Cabinet.": "in vetrina.",
        "Highlight": "Momenti",
        "Reel.": "migliori.",
        "How I spend": "Come passo",
        "my time.": "il mio tempo.",
        "Trying out": "Provare",
        "new things.": "cose nuove.",
        "How it": "Com’è",
        "went.": "andata.",
        "Music": "Musica",
        "Moodboard.": "moodboard.",
        "And the Oscar": "E l’Oscar",
        "goes to…": "va a…",
        "Ex Libris.": "Ex libris.",
        "Book of": "Libro del",
        "the Month.": "mese.",
        "Mini": "Mini",
        "Reviews.": "recensioni.",
        "Table": "Tavolo",
        "for": "per",
        "one": "una",
        "Worth a": "Vale un",
        "return trip.": "ritorno.",
        "Apps &": "App &",
        "Internet.": "Internet.",
        "For next": "Per il prossimo",
        "End of month,": "Fine del",
        "honestly.": "mese.",
        "Streak.": "Serie.",
        "THIS MONTH": "QUESTO MESE",
        "✦ 0/31": "✦ 0/31",
        "A MEMORY": "UN RICORDO",
        "THIS MONTH, I WANT TO FEEL —": "QUESTO MESE VOGLIO SENTIRMI —",
        "this month, I want to feel —": "questo mese voglio sentirmi —",
        "A LINE WORTH KEEPING": "UNA FRASE DA TENERE",
        "ONE MORE THING I WANT TO REMEMBER": "UN’ALTRA COSA CHE VOGLIO RICORDARE",
        "Hobby": "Hobby",
        "Gallery.": "galleria.",
        "Progress.": "procedendo.",
        "HOBBY 01": "HOBBY 01",
        "HOBBY 02": "HOBBY 02",
        "HOBBY 03": "HOBBY 03",
        "HOBBY 04": "HOBBY 04",
        "NAME →": "NOME →",
        "WILL I CONTINUE?": "CONTINUERÒ?",
        "WHAT I LEARNED": "COSA HO IMPARATO",
        "WHERE →": "DOVE →",
        "SCORECARD": "PAGELLA",
        "HOW WE MET": "COME CI SIAMO CONOSCIUTI",
        "N° 01": "N. 01",
        "N° 02": "N. 02",
        "The people": "Le persone",
        "in my corner.": "al mio fianco.",
        "In love with": "Innamorata",
        "life.": "della vita.",
        "Dear life,": "Cara vita,",
        "yours, always.": "tua, sempre.",
        "name:": "nome:",
        "WRAPPED": "RIEPILOGO",
        "LIVE FROM MY HEADPHONES": "LIVE DALLE MIE CUFFIE",
        "TOP 5": "TOP 5",
        "SONG NAME - ARTIST": "TITOLO - ARTISTA",
        "HEADLINER": "HEADLINER",
        "DISCOVERY STAGE": "PALCO SCOPERTE",
        "LINER NOTES": "NOTE",
        "MIXTAPE": "MIXTAPE",
        "SCENE 01": "SCENA 01",
        "SCENE 02": "SCENA 02",
        "SCENE 03": "SCENA 03",
        "SCENE 04": "SCENA 04",
        "RATING →": "VOTO →",
        "EX LIBRIS": "EX LIBRIS",
        "BREAKFAST": "COLAZIONE",
        "LUNCH": "PRANZO",
        "DINNER": "CENA",
        "RESTAURANT": "RISTORANTE",
        "OCCASION": "OCCASIONE",
        "FOOD": "CIBO",
        "Postcards from the coast": "Cartoline dalla costa",
        "STAMP": "FRANCOBOLLO",
        "Greetings from": "Saluti da",
        "TO": "A",
        "APP / PODCAST / SITE": "APP / PODCAST / SITO",
        "Rituals.": "Rituali.",
        "health & wellness": "salute & benessere",
        "A WORD FOR NEXT MONTH": "UNA PAROLA PER IL PROSSIMO MESE",
        "OUTLOOK": "PROSPETTIVA",
        "Vision": "Vision",
        "Board.": "board.",
        "FINAL THOUGHTS": "PENSIERI FINALI",
        "— and let it lead the month.": "— e lascia che guidi il mese.",
        "WHAT I WILL REMEMBER ABOUT IT": "COSA VOGLIO RICORDARE",
        "WHAT STAYED WITH ME": "COSA MI È RIMASTO",
        "body": "corpo",
        "mind": "mente",
        "love": "amore",
        "rest": "riposo",
        "title": "titolo",
        "name": "nome",
        "My culinary": "Le mie creazioni",
        "creations.": "in cucina.",
        "week one": "settimana uno",
        "week two": "settimana due",
        "week three": "settimana tre",
        "week four": "settimana quattro",
        "with love,": "con affetto,",
        "The Monthly": "La storia",
        "Story.": "del mese.",
        "▢  self portrait": "▢  autoritratto",
        "▢  a moment": "▢  un momento",
        "a note →": "una nota →",
        "TOP STORY": "STORIA PRINCIPALE",
        "▢  the scene of the win": "▢  la scena della vittoria",
        "▢  scene 01": "▢  scena 01",
        "▢  scene 02": "▢  scena 02",
        "▢  scene 03": "▢  scena 03",
        "▢  scene 04": "▢  scena 04",
        "▢  the practice": "▢  la pratica",
        "▢  photo · large": "▢  foto · grande",
        "▢  photo · wide": "▢  foto · larga",
        "▢  photo · banner": "▢  foto · banner",
        "▢  the date": "▢  il date",
        "The": "Il",
        "APPRECIATION": "APPREZZAMENTO",
        "▢  a small joy": "▢  una piccola gioia",
        "sign here": "firma qui",
        "▢  poster": "▢  poster",
        "writing": "scrittura",
        "characters": "personaggi",
        "plot": "trama",
        "feeling": "sensazione",
        "A week,": "Una settimana",
        "on a plate.": "nel piatto.",
        "DAY": "GIORNO",
        "MON": "LUN",
        "TUE": "MAR",
        "WED": "MER",
        "THU": "GIO",
        "FRI": "VEN",
        "SAT": "SAB",
        "SUN": "DOM",
        "▢  the meal": "▢  il pasto",
        "▢  the view": "▢  la vista",
        "a place": "un luogo",
        "Places": "Luoghi",
        "seen.": "visti.",
        "Beauty": "Beauty",
        "Shelf.": "shelf.",
        "▢  product": "▢  prodotto",
        "▢  the meal of the month": "▢  il pasto del mese",
        "CAFÉ / BAR": "CAFFÈ / BAR",
        "MORNING": "MATTINA",
        "— sunrise —": "— alba —",
        "AFTERNOON": "POMERIGGIO",
        "— midday —": "— mezzogiorno —",
        "NIGHT": "SERA",
        "— sundown —": "— tramonto —",
        "▢  become": "▢  diventare",
        "▢  the feeling": "▢  la sensazione",
        "the feeling": "la sensazione",
        "▢  dream": "▢  sognare",
        "▢  wear": "▢  indossare",
        "▢  place": "▢  luogo",
        "place": "luogo",
        "▢  read": "▢  leggere",
        "▢  make": "▢  fare",
        "▢  do": "▢  agire",
        "— THE EDITORS": "— LA REDAZIONE",
        "One month older and wiser.": "",
        "make": "fare",
        "do": "agire",
        "become": "diventare",
        "dream": "sognare",
        "read": "leggere",
        "wear": "indossare",
        "PenPalooza": "PenPalooza",
        "FEATURE 1": "FEATURE 1",
        "FEATURE 2": "FEATURE 2",
        "M": "L",
        "T": "M",
        "W": "M",
        "F": "V",
        "S": "S",
        "This Month": "Questo mese",
        "VOL. I": "VOL. I"
    ]
}
