import Foundation

extension MagazineTemplateLocalization {
    static let spanishTranslations: [String: String] = [
        "Monthly Reset": "Reinicio mensual",
        "Tiny Wins": "Pequeñas victorias",
        "Hobbies": "Aficiones",
        "Relationships": "Relaciones",
        "Playlist & Music": "Playlist y música",
        "Cinema": "Cine",
        "Reading": "Lectura",
        "Food & Recipes": "Comida y recetas",
        "Travel & Places": "Viajes y lugares",
        "Favourites": "Favoritos",
        "Affirmations & Goals": "Afirmaciones y metas",
        "ISSUE №01 · 2026": "EDICIÓN №01 · 2026",
        "ISSUE №01": "EDICIÓN №01",
        "STAY IN EACH OTHER'S CHAPTERS": "PERMANEZCAN EN SUS CAPÍTULOS",
        "STAY PART OF YOUR FRIENDS' STORIES": "Sigue formando parte de las historias de tus amigos.",
        "“A magazine you make\nto grow together.”": "“Una revista que crean\npara crecer juntos.”",
        "MAKE IT.  SHARE IT.  REMEMBER IT.": "HAZLA.  COMPÁRTELA.  RECUÉRDALA.",
        "penpal · the editorial journal": "penpal · el diario editorial",
        "MADE WITH LOVE": "HECHO CON AMOR",
        "Contents.": "Índice.",
        "In this issue.": "En esta edición.",
        "CONTENTS · IN THIS ISSUE": "ÍNDICE · EN ESTA EDICIÓN",
        "MONTHLY RESET": "REINICIO MENSUAL",
        "MONTHLY RESET · DAILY REFLECTION": "REINICIO MENSUAL · REFLEXIÓN",
        "MONTHLY RESET · GRATITUDE": "REINICIO MENSUAL · GRATITUD",
        "MONTHLY RESET · LETTER": "REINICIO MENSUAL · CARTA",
        "MONTHLY RESET · LOOKING BACK": "REINICIO MENSUAL · MIRAR ATRÁS",
        "MONTHLY RESET · GROW TRACKER": "REINICIO MENSUAL · CRECIMIENTO",
        "TINY WINS · THE DAILY ME": "PEQUEÑAS VICTORIAS · MI DÍA",
        "TINY WINS · TROPHY CABINET": "PEQUEÑAS VICTORIAS · TROFEOS",
        "TINY WINS · STREAK": "PEQUEÑAS VICTORIAS · RACHA",
        "TINY WINS · HIGHLIGHT REEL": "PEQUEÑAS VICTORIAS · MOMENTOS",
        "HOBBIES · TRACKER": "AFICIONES · SEGUIMIENTO",
        "HOBBIES · A NEW TRY": "AFICIONES · NUEVO INTENTO",
        "HOBBIES · GALLERY": "AFICIONES · GALERÍA",
        "HOBBIES · PROGRESS": "AFICIONES · PROGRESO",
        "RELATIONSHIPS · DATE REVIEW": "RELACIONES · RESEÑA DE CITA",
        "RELATIONSHIPS · THE RANKING": "RELACIONES · CLASIFICACIÓN",
        "RELATIONSHIPS · APPRECIATION": "RELACIONES · APRECIO",
        "RELATIONSHIPS · IN LOVE WITH LIFE": "RELACIONES · ENAMORADA DE LA VIDA",
        "RELATIONSHIPS · NEWEST OBSESSION": "RELACIONES · NUEVA OBSESIÓN",
        "RELATIONSHIPS · PEOPLE I LOVE": "RELACIONES · PERSONAS QUE AMO",
        "PLAYLIST & MUSIC · WRAPPED": "PLAYLIST Y MÚSICA · RESUMEN",
        "PLAYLIST & MUSIC · FESTIVAL": "PLAYLIST Y MÚSICA · FESTIVAL",
        "PLAYLIST & MUSIC · LINER NOTES": "PLAYLIST Y MÚSICA · NOTAS",
        "PLAYLIST & MUSIC · MIXTAPE": "PLAYLIST Y MÚSICA · MIXTAPE",
        "CINEMA · TICKET STUB": "CINE · ENTRADA",
        "CINEMA · WATCH LOG": "CINE · REGISTRO",
        "CINEMA · HIGHLIGHTS": "CINE · MOMENTOS",
        "READING · BOOKPLATE": "LECTURA · EX LIBRIS",
        "READING · MARGIN NOTES": "LECTURA · NOTAS",
        "READING · MINI REVIEWS": "LECTURA · MINI RESEÑAS",
        "READING · TBR STACK": "LECTURA · POR LEER",
        "FOOD & RECIPES · CULINARY CREATIONS": "COMIDA Y RECETAS · CREACIONES",
        "FOOD & RECIPES · WEEK ON A PLATE": "COMIDA Y RECETAS · SEMANA EN PLATO",
        "FOOD & RECIPES · TABLE FOR ONE": "COMIDA Y RECETAS · MESA PARA UNA",
        "TRAVEL · POSTCARD": "VIAJES · POSTAL",
        "TRAVEL · PLACES SEEN": "VIAJES · LUGARES VISTOS",
        "FAVOURITES · BEAUTY SHELF": "FAVORITOS · ESTANTE BEAUTY",
        "FAVOURITES · EDIBLE": "FAVORITOS · COMIDA",
        "FAVOURITES · APPS & INTERNET": "FAVORITOS · APPS E INTERNET",
        "FAVOURITES · RITUALS": "FAVORITOS · RITUALES",
        "GOALS · OUTLOOK": "METAS · PANORAMA",
        "GOALS · AFFIRMATIONS": "METAS · AFIRMACIONES",
        "GOALS · VISION BOARD": "METAS · VISION BOARD",
        "GOALS · SUMMARY": "METAS · RESUMEN",
        "DATE REVIEW": "RESEÑA DE CITA",
        "FIRST IMPRESSIONS": "PRIMERAS IMPRESIONES",
        "VIBE CHECK": "SENSACIÓN GENERAL",
        "conversation": "Conversación",
        "chemistry": "Química",
        "humor": "Humor",
        "looks": "Apariencia",
        "presence": "Presencia",
        "manners": "Modales",
        "overall": "General",
        "THE RANKING": "LA CLASIFICACIÓN",
        "Ranking.": "Clasificación.",
        "WOULD SEE AGAIN": "VOLVERÍA A VER",
        "DO I WANT TO SEE THIS PERSON AGAIN?": "¿QUIERO VOLVER A VER A ESTA PERSONA?",
        "YES": "SÍ",
        "NO": "NO",
        "MAYBE": "QUIZÁS",
        "NEVER": "NUNCA",
        "Y": "S",
        "N": "N",
        "TITLE": "TÍTULO",
        "AUTHOR": "AUTOR",
        "GENRE": "GÉNERO",
        "DATE": "FECHA",
        "NAME": "NOMBRE",
        "THEIR NAME": "SU NOMBRE",
        "AGE": "EDAD",
        "OCCUPATION": "OCUPACIÓN",
        "PLACE": "LUGAR",
        "WHERE": "DÓNDE",
        "WHEN": "CUÁNDO",
        "WITH": "CON",
        "YEAR": "AÑO",
        "RUNTIME": "DURACIÓN",
        "DIRECTED BY": "DIRECCIÓN",
        "RATING": "PUNTUACIÓN",
        "ROW": "FILA",
        "SEAT": "ASIENTO",
        "ALBUM": "ÁLBUM",
        "ARTIST": "ARTISTA",
        "FAVOURITE TRACK": "CANCIÓN FAVORITA",
        "TOP ARTIST": "ARTISTA TOP",
        "TOP SONG": "CANCIÓN TOP",
        "A MOOD": "UN MOOD",
        "BRAND / PRODUCT": "MARCA / PRODUCTO",
        "WHY I LOVE IT →": "POR QUÉ ME ENCANTA →",
        "WHAT IT’S ABOUT": "DE QUÉ TRATA",
        "WHAT I ORDERED →": "QUÉ PEDÍ →",
        "WORTH RETURNING?": "¿VOLVERÍA?",
        "ATMOSPHERE": "AMBIENTE",
        "SERVICE": "SERVICIO",
        "VALUE": "VALOR",
        "WORK": "TRABAJO",
        "HEALTH": "SALUD",
        "LOVE": "AMOR",
        "MONEY": "DINERO",
        "REST": "DESCANSO",
        "CRAFT": "CREAR",
        "INTENTIONS": "INTENCIONES",
        "cover": "portada",
        "▢  photo": "▢  Añadir foto",
        "▢  cover": "▢  Añadir portada",
        "▢  cover art": "▢  Añadir portada",
        "▢  picture": "▢  Añadir imagen",
        "▢  portrait": "▢  Añadir retrato",
        "write here…": "Escribe tu reflexión…",
        "write one word here": "Una palabra para recordar",
        "write your word": "Elige tu palabra",
        "a few lines from you…": "Unas líneas para guardar…",
        "your name": "Tu Nombre",
        "LIVE · CAPTURE · SHARE": "VIVE · CAPTURA · COMPARTE",
        "Monthly Reset.": "Reinicio mensual.",
        "A slow audit of the days behind — what stayed, what shifted, what is worth remembering.": "Una revisión tranquila de los días que pasaron: lo que quedó, lo que cambió y lo que merece recordarse.",
        "SECTION": "SECCIÓN",
        "FEELING": "SENSACIÓN",
        "ONE GOOD THING": "ALGO BUENO",
        "ONE HARD THING": "ALGO DIFÍCIL",
        "ONE THING I LEARNED": "ALGO QUE APRENDÍ",
        "ONE THING I’M GRATEFUL FOR": "ALGO QUE AGRADEZCO",
        "HIGHS & LOWS": "ALTOS & BAJOS",
        "How the month": "Cómo este mes",
        "shaped me.": "me cambió.",
        "THE HIGHS": "LOS ALTOS",
        "THE LOWS": "LOS BAJOS",
        "MONTH IN ONE FRAME": "ESTE MES EN UNA IMAGEN",
        "▢  a high moment": "▢  un momento brillante",
        "▢  a low moment": "▢  un momento difícil",
        "▢  one image that holds the whole month": "▢  una imagen que cuenta todo el mes",
        "GRATITUDE": "GRATITUD",
        "What I am": "Por qué siento",
        "grateful for.": "gratitud.",
        "small things": "cosas pequeñas",
        "people": "personas",
        "places": "lugares",
        "moments": "momentos",
        "things you gave me this month —": "cosas que este mes trajo consigo —",
        "A LETTER": "UNA CARTA",
        "Dear month,": "Querido mes,",
        "a letter to the month from me.": "una carta al mes.",
        "LOOKING BACK": "MIRANDO ATRÁS",
        "A WORD FOR THE MONTH": "LA PALABRA DEL PRÓXIMO MES",
        "one word": "una palabra",
        "THE FIRST THING I WANT TO REMEMBER…": "LO PRIMERO QUE QUIERO RECORDAR…",
        "WHAT I AM READY TO CHANGE…": "LO QUE QUIERO CAMBIAR…",
        "WHAT I LEARNED ABOUT MYSELF…": "LO QUE APRENDÍ DE MÍ…",
        "Tiny Wins.": "Pequeñas victorias.",
        "Small triumphs, printed in earnest — the quiet headlines of an honest week.": "Pequeñas victorias para compartir: los mejores momentos de un buen mes.",
        "Small wins to share — the gentle headlines of a good month.": "Pequeñas victorias para compartir: los mejores momentos de un buen mes.",
        "Small wins to share — the headlines of a good month.": "Pequeñas victorias para compartir: los mejores momentos de un buen mes.",
        "Local human has a very good": "Una persona local tiene un",
        "month.": "mes extraordinario.",
        "A MONTH OF TINY VICTORIES": "UN MES DE PEQUEÑAS VICTORIAS",
        "WIN OF THE MONTH": "VICTORIA DEL MES",
        "EDITORIAL — WHAT MADE THIS MONTH A WIN": "EDITORIAL — LO QUE HIZO GANAR A ESTE MES",
        "WHAT HAPPENED →": "QUÉ PASÓ →",
        "AWARD Nº 01": "PREMIO N.º 01",
        "AWARD Nº 02": "PREMIO N.º 02",
        "AWARD Nº 03": "PREMIO N.º 03",
        "AWARD Nº 04": "PREMIO N.º 04",
        "FOR": "POR",
        "Hobbies.": "Aficiones.",
        "The slow practice of becoming better at something you love.": "El arte de mejorar en aquello que amas.",
        "Skill": "Mi",
        "consistency": "constancia",
        "confidence": "confianza",
        "creativity": "creatividad",
        "speed": "velocidad",
        "technique": "técnica",
        "theory": "teoría",
        "effort": "esfuerzo",
        "cost": "coste",
        "difficulty": "dificultad",
        "reward": "satisfacción",
        "Relationships.": "Relaciones.",
        "Notes on being known — the people in your corner, on the page.": "Una oda a las personas que tienes cerca y a esos pequeños detalles que solo tú conoces.",
        "An ode to the people by your side, with a little gossip in the margins.": "Una oda a las personas que tienes cerca y a esos pequeños detalles que solo tú conoces.",
        "WHY I LOVE THEM": "POR QUÉ LAS AMO",
        "WHY I LOVE THEM →": "POR QUÉ LAS AMO →",
        "why I love them →": "por qué las amo →",
        "first noticed": "lo noté por primera vez",
        "why they’re hot": "qué lo/la hace atractivo/a",
        "what I already know about them": "lo que ya sé de él/ella",
        "Playlist & Music.": "Playlist y música.",
        "Liner notes from the month — the songs that scored your days.": "Notas del mes — las canciones que acompañaron estos días.",
        "Notes of the month — the songs that carried these days.": "Notas del mes — las canciones que acompañaron estos días.",
        "ON REPEAT": "EN BUCLE",
        "a line about why →": "una línea sobre por qué →",
        "artist · song": "artista · canción",
        "when I am in my feelings": "cuando estoy triste",
        "when I am happy": "cuando estoy feliz",
        "when I am in love": "cuando estoy enamorada",
        "artist:": "artista:",
        "song:": "canción:",
        "Cinema.": "Cine.",
        "Tickets, scenes, scores — the dark room remembered.": "Entradas, escenas, puntuaciones — todo lo que queda de la noche de cine.",
        "ADMIT ONE": "ENTRADA",
        "WATCH LOG": "REGISTRO DE PELÍCULAS",
        "MOVIE HIGHLIGHTS": "MOMENTOS DE CINE",
        "Reading.": "Lectura.",
        "Stories worth being remembered — pages, lines, and the lives they made.": "Historias que merecen quedarse — páginas, frases y las vidas que abrieron.",
        "Stories worth remembering — pages, lines, and the lives they opened.": "Historias que merecen quedarse — páginas, frases y las vidas que abrieron.",
        "Food & Recipes.": "Comida y recetas.",
        "From the kitchen — the dishes, the table, the small rituals of the week.": "Desde la cocina — los platos, la mesa y los pequeños rituales del mes.",
        "From the kitchen — the dishes, the table, the small rituals of the month.": "Desde la cocina — los platos, la mesa y los pequeños rituales del mes.",
        "Travel & Places.": "Viajes y lugares.",
        "Postcards from the coast — and everywhere else worth remembering.": "Postales de la costa — y de todos los lugares que valía la pena explorar.",
        "Postcards from everywhere worth exploring and remembering.": "Postales de todos los lugares que valía la pena explorar.",
        "Favourites.": "Favoritos.",
        "The small obsessions — the things kept close, this month.": "Todo lo que amé este mes.",
        "Affirmations & Goals.": "Afirmaciones y metas.",
        "The intentions to carry into the next month — said quietly, said clearly.": "Intenciones serenas para abrir el próximo mes con claridad.",
        "A small triumph!": "¡Un pequeño triunfo!",
        "CORRESPONDENT NOTE": "NOTA DE CORRESPONSAL",
        "How I grew.": "Cómo\ncrecí.",
        "END OF MONTH, HONESTLY.": "FIN DE MES",
        "End of": "Fin de",
        "month": "mes",
        "People I love.": "Personas\nque amo.",
        "My Month": "La banda sonora",
        "in Sound.": "de mi mes.",
        "Album of": "Álbum del",
        "the Week.": "mes.",
        "The film of": "La película de la",
        "the night.": "noche.",
        "What I": "Lo que",
        "watched.": "vi.",
        "To be": "Por",
        "read.": "leer.",
        "Wish you": "Ojalá",
        "were here.": "estuvieras aquí.",
        "The month": "El mes",
        "ahead.": "que viene.",
        "THE DAILY ME": "MI DÍA A DÍA",
        "TROPHY CABINET": "VITRINA DE TROFEOS",
        "HIGHLIGHT REEL": "MOMENTOS DESTACADOS",
        "HOBBY TRACKER": "SEGUIMIENTO DE AFICIONES",
        "A NEW TRY": "UN NUEVO INTENTO",
        "HOBBY GALLERY": "GALERÍA DE AFICIONES",
        "PROGRESS TRACKER": "SEGUIMIENTO DE PROGRESO",
        "APPRECIATION POST": "POST DE APRECIO",
        "PEOPLE I LOVE": "PERSONAS QUE AMO",
        "NEWEST OBSESSION": "NUEVA OBSESIÓN",
        "MY RECOMMENDATIONS": "MIS RECOMENDACIONES",
        "MY ROUTINES": "MIS RUTINAS",
        "BOOKPLATE": "EX LIBRIS",
        "MARGIN NOTES": "NOTAS AL MARGEN",
        "TO BE READ": "POR LEER",
        "CULINARY CREATIONS": "CREACIONES CULINARIAS",
        "WEEK ON A PLATE": "SEMANA EN EL PLATO",
        "TABLE FOR ONE": "MESA PARA UNA",
        "POSTCARD": "POSTAL",
        "PLACES SEEN": "LUGARES VISTOS",
        "BEAUTY SHELF": "ESTANTE BEAUTY",
        "EDIBLE FAVOURITES": "FAVORITOS COMESTIBLES",
        "WORD OF THE MONTH": "PALABRA DEL MES",
        "VISION BOARD": "VISION BOARD",
        "AFFIRMATIONS": "AFIRMACIONES",
        "photo": "Añadir foto",
        "Trophy": "Vitrina",
        "Cabinet.": "de trofeos.",
        "Highlight": "Momentos",
        "Reel.": "destacados.",
        "How I spend": "Mi",
        "my time.": "tiempo.",
        "Trying out": "Algo",
        "new things.": "nuevo.",
        "How it": "Cómo",
        "went.": "fue.",
        "Crush": "Crush",
        "Diary.": "diario.",
        "Music": "Música",
        "Moodboard.": "moodboard.",
        "And the Oscar": "Y el Oscar",
        "goes to…": "es para…",
        "Ex Libris.": "Ex libris.",
        "Book of": "Libro del",
        "the Month.": "mes.",
        "Mini": "Mini",
        "Reviews.": "reseñas.",
        "Table": "Mesa",
        "for": "para",
        "one": "una",
        "Worth a": "Vale",
        "return trip.": "volver.",
        "Apps &": "Descubrimientos",
        "Internet.": "digitales.",
        "For next": "Hacia un",
        "End of month,": "Fin de",
        "honestly.": "mes.",
        "Streak.": "Racha.",
        "THIS MONTH": "ESTE MES",
        "✦ 0/31": "✦ 0/31",
        "A MEMORY": "UN RECUERDO",
        "THIS MONTH, I WANT TO FEEL —": "ESTE MES QUIERO SENTIRME —",
        "this month, I want to feel —": "este mes quiero sentirme —",
        "A LINE WORTH KEEPING": "UNA LÍNEA PARA GUARDAR",
        "ONE MORE THING I WANT TO REMEMBER": "UNA COSA MÁS QUE QUIERO RECORDAR",
        "Hobby": "Galería de",
        "Gallery.": "hobbies.",
        "Progress.": "progreso.",
        "HOBBY 01": "AFICIÓN 01",
        "HOBBY 02": "AFICIÓN 02",
        "HOBBY 03": "AFICIÓN 03",
        "HOBBY 04": "AFICIÓN 04",
        "NAME →": "NOMBRE →",
        "WILL I CONTINUE?": "¿SEGUIRÉ?",
        "WHAT I LEARNED": "LO QUE APRENDÍ",
        "WHERE →": "DÓNDE →",
        "SCORECARD": "PUNTUACIÓN",
        "HOW WE MET": "CÓMO NOS CONOCIMOS",
        "N° 01": "N.º 01",
        "N° 02": "N.º 02",
        "The people": "Las personas",
        "in my corner.": "a mi lado.",
        "In love with": "Enamorada",
        "life.": "de la vida.",
        "Dear life,": "Querida vida,",
        "yours, always.": "tuya, siempre.",
        "name:": "Nombre:",
        "WRAPPED": "RESUMEN",
        "LIVE FROM MY HEADPHONES": "EN DIRECTO DESDE MIS AURICULARES",
        "TOP 5": "Mis cinco favoritas",
        "SONG NAME - ARTIST": "CANCIÓN - ARTISTA",
        "HEADLINER": "CABEZA DE CARTEL",
        "DISCOVERY STAGE": "ESCENARIO DESCUBRIMIENTOS",
        "LINER NOTES": "NOTAS",
        "MIXTAPE": "MIXTAPE",
        "SCENE 01": "ESCENA 01",
        "SCENE 02": "ESCENA 02",
        "SCENE 03": "ESCENA 03",
        "SCENE 04": "ESCENA 04",
        "RATING →": "PUNTUACIÓN →",
        "EX LIBRIS": "EX LIBRIS",
        "BREAKFAST": "DESAYUNO",
        "LUNCH": "COMIDA",
        "DINNER": "CENA",
        "RESTAURANT": "RESTAURANTE",
        "OCCASION": "OCASIÓN",
        "FOOD": "COMIDA",
        "STAMP": "SELLO",
        "Greetings from": "Saludos desde",
        "TO": "PARA",
        "APP / PODCAST / SITE": "APP / PODCAST / WEB",
        "Rituals.": "Rituales.",
        "health & wellness": "Salud y bienestar",
        "A WORD FOR NEXT MONTH": "LA PALABRA DEL PRÓXIMO MES",
        "OUTLOOK": "PANORAMA",
        "Vision": "Vision",
        "Board.": "board.",
        "FINAL THOUGHTS": "PENSAMIENTOS FINALES",
        "— and let it lead the month.": "— y deja que guíe el mes.",
        "WHAT I WILL REMEMBER ABOUT IT": "LO QUE VOY A RECORDAR",
        "WHAT STAYED WITH ME": "LO QUE SE QUEDÓ CONMIGO",
        "body": "cuerpo",
        "mind": "mente",
        "love": "amor",
        "rest": "descanso",
        "title": "título",
        "name": "Nombre",
        "My culinary": "Mis creaciones",
        "creations.": "de cocina.",
        "week one": "semana uno",
        "week two": "semana dos",
        "week three": "semana tres",
        "week four": "semana cuatro",
        "with love,": "con cariño,",
        "The Monthly": "La historia",
        "Story.": "del mes.",
        "▢  self portrait": "▢  autorretrato",
        "▢  a moment": "▢  un momento",
        "a note →": "una nota →",
        "TOP STORY": "HISTORIA PRINCIPAL",
        "▢  the scene of the win": "▢  la escena de la victoria",
        "▢  scene 01": "▢  escena 01",
        "▢  scene 02": "▢  escena 02",
        "▢  scene 03": "▢  escena 03",
        "▢  scene 04": "▢  escena 04",
        "▢  the practice": "▢  la práctica",
        "▢  photo · large": "▢  Añadir foto",
        "▢  photo · wide": "▢  Añadir foto",
        "▢  photo · banner": "▢  Añadir foto",
        "▢  the date": "▢  la cita",
        "The": "El",
        "APPRECIATION": "APRECIO",
        "▢  a small joy": "▢  una pequeña alegría",
        "sign here": "firma aquí",
        "▢  poster": "▢  póster",
        "writing": "escritura",
        "characters": "personajes",
        "plot": "trama",
        "feeling": "sensación",
        "A week,": "Una semana",
        "on a plate.": "en el plato.",
        "DAY": "DÍA",
        "MON": "LUN",
        "TUE": "MAR",
        "WED": "MIÉ",
        "THU": "JUE",
        "FRI": "VIE",
        "SAT": "SÁB",
        "SUN": "DOM",
        "▢  the meal": "▢  la comida",
        "▢  the view": "▢  la vista",
        "a place": "un lugar",
        "Places": "Lugares",
        "seen.": "vistos.",
        "Beauty": "Beauty",
        "Shelf.": "shelf.",
        "▢  product": "▢  producto",
        "▢  the meal of the month": "▢  la comida del mes",
        "CAFÉ / BAR": "CAFÉ / BAR",
        "MORNING": "MAÑANA",
        "— sunrise —": "— amanecer —",
        "AFTERNOON": "TARDE",
        "— midday —": "— mediodía —",
        "NIGHT": "NOCHE",
        "— sundown —": "— atardecer —",
        "▢  become": "▢  convertirme",
        "▢  the feeling": "▢  la sensación",
        "the feeling": "la sensación",
        "▢  dream": "▢  soñar",
        "▢  wear": "▢  vestir",
        "▢  place": "▢  lugar",
        "place": "lugar",
        "▢  read": "▢  leer",
        "▢  make": "▢  hacer",
        "▢  do": "▢  actuar",
        "— THE EDITORS": "— LA REDACCIÓN",
        "One month older and wiser.": "",
        "make": "hacer",
        "do": "actuar",
        "become": "convertirme",
        "dream": "soñar",
        "read": "leer",
        "wear": "vestir",
        "PenPalooza": "PenPalooza",
        "FEATURE 1": "FEATURE 1",
        "FEATURE 2": "FEATURE 2",
        "M": "L",
        "T": "M",
        "W": "X",
        "F": "V",
        "S": "S",
        "This Month": "Este mes",
        "VOL. I": "VOL. I"
    ]
}
