import Foundation

extension MagazineTemplateLocalization {
    static let germanTranslations: [String: String] = [
        "Monthly Reset": "Monatsreset",
        "Tiny Wins": "Kleine Siege",
        "Hobbies": "Hobbys",
        "Relationships": "Beziehungen",
        "Playlist & Music": "Playlist & Musik",
        "Cinema": "Kino",
        "Reading": "Lesen",
        "Food & Recipes": "Essen & Rezepte",
        "Travel & Places": "Reisen & Orte",
        "Favourites": "Favoriten",
        "Affirmations & Goals": "Affirmationen & Ziele",
        "ISSUE №01 · 2026": "AUSGABE №01 · 2026",
        "ISSUE №01": "AUSGABE №01",
        "STAY IN EACH OTHER'S CHAPTERS": "Bleib Teil der Geschichten deiner Freunde.",
        "STAY PART OF YOUR FRIENDS' STORIES": "Bleib Teil der Geschichten deiner Freunde.",
        "“A magazine you make\nto grow together.”": "„Ein Magazin, das ihr gemeinsam gestaltet,\num miteinander zu wachsen.“",
        "MAKE IT.  SHARE IT.  REMEMBER IT.": "MACH ES.  TEILE ES.  ERINNERE DICH.",
        "penpal · the editorial journal": "PenPal · das redaktionelle Journal",
        "MADE WITH LOVE": "MIT LIEBE GEMACHT",
        "Contents.": "Inhalt.",
        "In this issue.": "In dieser Ausgabe.",
        "CONTENTS · IN THIS ISSUE": "INHALT · IN DIESER AUSGABE",
        "MONTHLY RESET": "MONATSRESET",
        "MONTHLY RESET · DAILY REFLECTION": "MONATSRESET · TAGESRÜCKBLICK",
        "MONTHLY RESET · GRATITUDE": "MONATSRESET · DANKBARKEIT",
        "MONTHLY RESET · LETTER": "MONATSRESET · BRIEF",
        "MONTHLY RESET · LOOKING BACK": "MONATSRESET · RÜCKBLICK",
        "MONTHLY RESET · GROW TRACKER": "MONATSRESET · WACHSTUM",
        "TINY WINS · THE DAILY ME": "KLEINE SIEGE · DAS TÄGLICHE ICH",
        "TINY WINS · TROPHY CABINET": "KLEINE SIEGE · TROPHÄENSCHRANK",
        "TINY WINS · STREAK": "KLEINE SIEGE · SERIE",
        "TINY WINS · HIGHLIGHT REEL": "KLEINE SIEGE · HIGHLIGHTS",
        "HOBBIES · TRACKER": "HOBBYS · TRACKER",
        "HOBBIES · A NEW TRY": "HOBBYS · NEUER VERSUCH",
        "HOBBIES · GALLERY": "HOBBYS · GALERIE",
        "HOBBIES · PROGRESS": "HOBBYS · FORTSCHRITT",
        "RELATIONSHIPS · DATE REVIEW": "BEZIEHUNGEN · DATE-REVIEW",
        "RELATIONSHIPS · THE RANKING": "BEZIEHUNGEN · DATE-RANKING",
        "RELATIONSHIPS · APPRECIATION": "BEZIEHUNGEN · WERTSCHÄTZUNG",
        "RELATIONSHIPS · IN LOVE WITH LIFE": "BEZIEHUNGEN · VERLIEBT INS LEBEN",
        "RELATIONSHIPS · NEWEST OBSESSION": "BEZIEHUNGEN · NEUESTE OBSESSION",
        "RELATIONSHIPS · PEOPLE I LOVE": "BEZIEHUNGEN · MENSCHEN, DIE ICH LIEBE",
        "PLAYLIST & MUSIC · WRAPPED": "PLAYLIST & MUSIK · RÜCKBLICK",
        "PLAYLIST & MUSIC · FESTIVAL": "PLAYLIST & MUSIK · FESTIVAL",
        "PLAYLIST & MUSIC · LINER NOTES": "PLAYLIST & MUSIK · LINER NOTES",
        "PLAYLIST & MUSIC · MIXTAPE": "PLAYLIST & MUSIK · MIXTAPE",
        "CINEMA · TICKET STUB": "KINO · TICKET",
        "CINEMA · WATCH LOG": "KINO · WATCHLIST",
        "CINEMA · HIGHLIGHTS": "KINO · HIGHLIGHTS",
        "READING · BOOKPLATE": "LESEN · EX LIBRIS",
        "READING · MARGIN NOTES": "LESEN · RANDNOTIZEN",
        "READING · MINI REVIEWS": "LESEN · MINI-REVIEWS",
        "READING · TBR STACK": "LESEN · LESLISTE",
        "FOOD & RECIPES · CULINARY CREATIONS": "ESSEN & REZEPTE · KÜCHENKREATIONEN",
        "FOOD & RECIPES · WEEK ON A PLATE": "ESSEN & REZEPTE · WOCHE AUF DEM TELLER",
        "FOOD & RECIPES · TABLE FOR ONE": "ESSEN & REZEPTE · TISCH FÜR EINS",
        "TRAVEL · POSTCARD": "REISEN · POSTKARTE",
        "TRAVEL · PLACES SEEN": "REISEN · BESUCHTE ORTE",
        "FAVOURITES · BEAUTY SHELF": "FAVORITEN · BEAUTY-REGAL",
        "FAVOURITES · EDIBLE": "FAVORITEN · ESSEN & TRINKEN",
        "FAVOURITES · APPS & INTERNET": "FAVORITEN · APPS & INTERNET",
        "FAVOURITES · RITUALS": "FAVORITEN · RITUALE",
        "GOALS · OUTLOOK": "ZIELE · AUSBLICK",
        "GOALS · AFFIRMATIONS": "ZIELE · AFFIRMATIONEN",
        "GOALS · VISION BOARD": "ZIELE · VISION BOARD",
        "GOALS · SUMMARY": "ZIELE · ZUSAMMENFASSUNG",
        "THE DAILY ME": "DAS TÄGLICHE ICH",
        "TROPHY CABINET": "TROPHÄENSCHRANK",
        "HIGHLIGHT REEL": "HIGHLIGHTS",
        "HOBBY TRACKER": "HOBBY-TRACKER",
        "A NEW TRY": "EIN NEUER VERSUCH",
        "HOBBY GALLERY": "HOBBY-GALERIE",
        "PROGRESS TRACKER": "FORTSCHRITTS-TRACKER",
        "DATE REVIEW": "DATE-REVIEW",
        "FIRST IMPRESSIONS": "ERSTER EINDRUCK",
        "VIBE CHECK": "VIBE-CHECK",
        "conversation": "GESPRÄCH",
        "chemistry": "CHEMIE",
        "humor": "HUMOR",
        "looks": "AUSSEHEN",
        "presence": "PRÄSENZ",
        "manners": "MANIEREN",
        "overall": "GESAMT",
        "THE RANKING": "DAS RANKING",
        "Ranking.": "Ranking.",
        "WOULD SEE AGAIN": "WÜRDE ICH DIE PERSON WIEDERSEHEN?",
        "DO I WANT TO SEE THIS PERSON AGAIN?": "MÖCHTE ICH DIESE PERSON WIEDERSEHEN?",
        "YES": "JA",
        "NO": "NEIN",
        "MAYBE": "VIELLEICHT",
        "NEVER": "NIE",
        "Y": "J",
        "N": "N",
        "APPRECIATION POST": "WERTSCHÄTZUNGS-POST",
        "PEOPLE I LOVE": "MENSCHEN,\nDIE ICH LIEBE",
        "NEWEST OBSESSION": "NEUESTE OBSESSION",
        "MY RECOMMENDATIONS": "MEINE EMPFEHLUNGEN",
        "MY ROUTINES": "MEINE ROUTINEN",
        "BOOKPLATE": "EX LIBRIS",
        "MARGIN NOTES": "RANDNOTIZEN",
        "TO BE READ": "ZU LESEN",
        "CULINARY CREATIONS": "KÜCHENKREATIONEN",
        "WEEK ON A PLATE": "WOCHE AUF DEM TELLER",
        "TABLE FOR ONE": "TISCH FÜR EINS",
        "POSTCARD": "POSTKARTE",
        "PLACES SEEN": "BESUCHTE ORTE",
        "BEAUTY SHELF": "BEAUTY-REGAL",
        "EDIBLE FAVOURITES": "KULINARISCHE FAVORITEN",
        "WORD OF THE MONTH": "WORT DES MONATS",
        "VISION BOARD": "VISION BOARD",
        "AFFIRMATIONS": "AFFIRMATIONEN",
        "TITLE": "TITEL",
        "AUTHOR": "AUTOR",
        "GENRE": "GENRE",
        "DATE": "DATUM",
        "NAME": "NAME",
        "THEIR NAME": "NAME",
        "AGE": "ALTER",
        "OCCUPATION": "BERUF",
        "PLACE": "ORT",
        "WHERE": "WO",
        "WHEN": "WANN",
        "WITH": "MIT",
        "YEAR": "JAHR",
        "RUNTIME": "LAUFZEIT",
        "DIRECTED BY": "REGIE",
        "RATING": "BEWERTUNG",
        "ROW": "REIHE",
        "SEAT": "PLATZ",
        "ALBUM": "ALBUM",
        "ARTIST": "KÜNSTLER",
        "FAVOURITE TRACK": "LIEBLINGSTRACK",
        "TOP ARTIST": "TOP-KÜNSTLER",
        "TOP SONG": "TOP-SONG",
        "A MOOD": "GENRE",
        "BRAND / PRODUCT": "MARKE / PRODUKT",
        "WHY I LOVE IT →": "WARUM ICH ES LIEBE →",
        "WHAT IT’S ABOUT": "WORUM ES GEHT",
        "WHAT I ORDERED →": "WAS ICH BESTELLT HABE →",
        "WORTH RETURNING?": "WIEDER HINGEHEN?",
        "ATMOSPHERE": "ATMOSPHÄRE",
        "SERVICE": "SERVICE",
        "VALUE": "PREIS/LEISTUNG",
        "WORK": "ARBEIT",
        "HEALTH": "GESUNDHEIT",
        "LOVE": "LIEBE",
        "MONEY": "GELD",
        "REST": "RUHE",
        "CRAFT": "KREATIVES",
        "INTENTIONS": "ABSICHTEN",
        "cover": "Buchcover",
        "photo": "Foto hinzufügen",
        "▢  photo": "▢  Foto hinzufügen",
        "▢  cover": "▢  Buchcover",
        "▢  cover art": "▢  Coverbild",
        "▢  picture": "▢  Bild",
        "▢  portrait": "▢  Porträt",
        "write here…": "Hier festhalten…",
        "write one word here": "ein Wort festhalten",
        "write your word": "dein Wort",
        "a few lines from you…": "ein paar Zeilen von dir…",
        "your name": "dein Name",
        "A small triumph!": "Ein kleiner Triumph!",
        "CORRESPONDENT NOTE": "KORRESPONDENTENNOTIZ",
        "Small triumphs, printed in earnest — the quiet headlines of an honest week.": "Kleine Siege zum Teilen – die Schlagzeilen eines guten Monats.",
        "Small wins to share — the gentle headlines of a good month.": "Kleine Siege zum Teilen – die Schlagzeilen eines guten Monats.",
        "Small wins to share — the headlines of a good month.": "Kleine Siege zum Teilen – die Schlagzeilen eines guten Monats.",
        "Local human has a very good": "Ein außergewöhnlich guter",
        "month.": "Monat.",
        "How I grew.": "Wie ich\ngewachsen bin.",
        "Trophy": "Trophäen",
        "Cabinet.": "schrank.",
        "Highlight": "Highlight",
        "Reel.": "-Reel.",
        "How I spend": "So verbringe ich",
        "my time.": "meine Zeit.",
        "Trying out": "Neue Dinge",
        "new things.": "ausprobieren.",
        "How it": "Wie es",
        "went.": "lief.",
        "People I love.": "Menschen,\ndie ich liebe.",
        "Crush": "Crush-",
        "Diary.": "Tagebuch.",
        "My Month": "Mein Monat",
        "in Sound.": "in Musik.",
        "Album of": "Album des",
        "the Week.": "Monats.",
        "Music": "Musik",
        "Moodboard.": "Moodboard.",
        "The film of": "Der Film der",
        "the night.": "Nacht.",
        "What I": "Was ich",
        "watched.": "gesehen habe.",
        "And the Oscar": "Und der Oscar",
        "goes to…": "geht an…",
        "Ex Libris.": "Ex Libris.",
        "Book of": "Buch des",
        "the Month.": "Monats.",
        "Mini": "Mini-",
        "Reviews.": "Reviews.",
        "To be": "Zu",
        "read.": "lesen.",
        "Table": "Tisch",
        "for": "für",
        "one": "eins",
        "Wish you": "Ich wünschte, du",
        "were here.": "wärst hier.",
        "Worth a": "Einen zweiten",
        "return trip.": "Besuch wert.",
        "Apps &": "Apps &",
        "Internet.": "Internet.",
        "The month": "Affirmationen",
        "ahead.": "& Manifestationen.",
        "For next": "Für den nächsten",
        "LIVE · CAPTURE · SHARE": "ERLEBEN · FESTHALTEN · TEILEN",
        "Monthly Reset.": "Monatsreset.",
        "A slow audit of the days behind — what stayed, what shifted, what is worth remembering.": "Ein ruhiger Blick auf die vergangenen Tage – auf das, was blieb, was sich verändert hat und was in Erinnerung bleiben soll.",
        "SECTION": "ABSCHNITT",
        "END OF MONTH, HONESTLY.": "ENDE DES MONATS",
        "End of month,": "Ende des",
        "honestly.": "Monats.",
        "End of": "Ende des",
        "month": "Monats",
        "FEELING": "GEFÜHL",
        "ONE GOOD THING": "EINE GUTE SACHE",
        "ONE HARD THING": "EINE SCHWERE SACHE",
        "ONE THING I LEARNED": "ETWAS, DAS ICH GELERNT HABE",
        "ONE THING I’M GRATEFUL FOR": "ETWAS, WOFÜR ICH DANKBAR BIN",
        "HIGHS & LOWS": "HÖHEN & TIEFEN",
        "How the month": "Wie dieser Monat",
        "shaped me.": "mich geprägt hat.",
        "THE HIGHS": "DIE HÖHEN",
        "THE LOWS": "DIE TIEFEN",
        "MONTH IN ONE FRAME": "DIESER MONAT IN EINEM BILD",
        "▢  a high moment": "▢  ein Highlight",
        "▢  a low moment": "▢  ein Tiefpunkt",
        "▢  one image that holds the whole month": "▢  ein Bild, das den ganzen Monat beschreibt",
        "GRATITUDE": "DANKBARKEIT",
        "What I am": "Wofür ich",
        "grateful for.": "dankbar bin.",
        "small things": "kleine Dinge",
        "people": "Menschen",
        "places": "Orte",
        "moments": "Momente",
        "things you gave me this month —": "Dinge, die dieser Monat mit sich brachte –",
        "A LETTER": "EIN BRIEF",
        "Dear month,": "Lieber Monat,",
        "a letter to the month from me.": "ein Brief an den Monat.",
        "LOOKING BACK": "RÜCKBLICK",
        "A WORD FOR THE MONTH": "EIN WORT ZUM ABSCHLUSS DES MONATS",
        "one word": "ein Wort",
        "THE FIRST THING I WANT TO REMEMBER…": "DAS ERSTE, WORAN ICH MICH ERINNERN WILL…",
        "WHAT I AM READY TO CHANGE…": "WAS ICH BEREIT BIN ZU ÄNDERN…",
        "WHAT I LEARNED ABOUT MYSELF…": "WAS ICH ÜBER MICH GELERNT HABE…",
        "A MONTH OF TINY VICTORIES": "EIN MONAT KLEINER SIEGE",
        "WIN OF THE MONTH": "SIEG DES MONATS",
        "EDITORIAL — WHAT MADE THIS MONTH A WIN": "REDAKTION – WAS DIESEN MONAT BESONDERS GEMACHT HAT",
        "WHAT HAPPENED →": "WAS PASSIERT IST →",
        "AWARD Nº 01": "AUSZEICHNUNG NR. 01",
        "AWARD Nº 02": "AUSZEICHNUNG NR. 02",
        "AWARD Nº 03": "AUSZEICHNUNG NR. 03",
        "AWARD Nº 04": "AUSZEICHNUNG NR. 04",
        "FOR": "FÜR",
        "Streak.": "Serie.",
        "THIS MONTH": "DIESEN MONAT",
        "✦ 0/31": "✦ 0/31",
        "A MEMORY": "EINE ERINNERUNG",
        "THIS MONTH, I WANT TO FEEL —": "DIESEN MONAT WILL ICH MICH FÜHLEN –",
        "this month, I want to feel —": "diesen Monat will ich mich fühlen –",
        "A LINE WORTH KEEPING": "EINE ZEILE, DIE BLEIBEN SOLL",
        "ONE MORE THING I WANT TO REMEMBER": "EINE SACHE, AN DIE ICH MICH ERINNERN WILL",
        "Hobby": "Hobby-",
        "Gallery.": "Galerie.",
        "Progress.": "Tracker.",
        "The slow practice of becoming better at something you love.": "Die Kunst, in etwas besser zu werden, das du liebst.",
        "The practice of becoming better at something you love.": "Die Kunst, in etwas besser zu werden, das du liebst.",
        "Skill": "Fortschritts-",
        "consistency": "Beständigkeit",
        "confidence": "Selbstvertrauen",
        "creativity": "Kreativität",
        "speed": "Tempo",
        "technique": "Technik",
        "theory": "Theorie",
        "HOBBY 01": "HOBBY 01",
        "HOBBY 02": "HOBBY 02",
        "HOBBY 03": "HOBBY 03",
        "HOBBY 04": "HOBBY 04",
        "NAME →": "NAME →",
        "effort": "Aufwand",
        "cost": "Kosten",
        "difficulty": "Schwierigkeit",
        "reward": "Belohnung",
        "WILL I CONTINUE?": "MACHE ICH WEITER?",
        "WHAT I LEARNED": "WAS ICH GELERNT HABE",
        "WHERE →": "WO →",
        "SCORECARD": "BEWERTUNG",
        "HOW WE MET": "WIE WIR UNS KENNENLERNTEN",
        "N° 01": "NR. 01",
        "N° 02": "NR. 02",
        "WHY I LOVE THEM": "WARUM ICH SIE LIEBE",
        "WHY I LOVE THEM →": "WARUM ICH SIE LIEBE →",
        "why I love them →": "Warum ich sie liebe →",
        "The people": "Die Menschen",
        "in my corner.": "an meiner Seite.",
        "Notes on being known — the people in your corner, on the page.": "Eine Ode an die Menschen an deiner Seite – mit etwas Gossip am Rande.",
        "An ode to the people by your side, with a little gossip in the margins.": "Eine Ode an die Menschen an deiner Seite – mit etwas Gossip am Rande.",
        "In love with": "Verliebt ins",
        "life.": "Leben.",
        "Dear life,": "Liebes Leben,",
        "yours, always.": "dein,",
        "name:": "Name:",
        "first noticed": "Zum ersten Mal bemerkt",
        "why they’re hot": "Was macht die Person attraktiv?",
        "what I already know about them": "Was ich über die Person weiß",
        "WRAPPED": "RÜCKBLICK",
        "LIVE FROM MY HEADPHONES": "LIVE AUS MEINEN KOPFHÖRERN",
        "TOP 5": "TOP 5",
        "SONG NAME - ARTIST": "SONGTITEL – KÜNSTLER",
        "HEADLINER": "HEADLINER",
        "DISCOVERY STAGE": "ENTDECKUNGSBÜHNE",
        "ON REPEAT": "IN DAUERSCHLEIFE",
        "Liner notes from the month — the songs that scored your days.": "Noten des Monats – die Lieder, die diesen Monat begleitet haben.",
        "Notes of the month — the songs that carried these days.": "Noten des Monats – die Lieder, die diesen Monat begleitet haben.",
        "a line about why →": "Eine Zeile dazu →",
        "artist · song": "Künstler · Song",
        "LINER NOTES": "LINER NOTES",
        "MIXTAPE": "MIXTAPE",
        "when I am in my feelings": "Wenn ich traurig bin",
        "when I am happy": "Wenn ich glücklich bin",
        "when I am in love": "Wenn ich verliebt bin",
        "artist:": "Künstler:",
        "song:": "Song:",
        "Cinema.": "Kino.",
        "Tickets, scenes, scores — the dark room remembered.": "Tickets, Szenen, Bewertungen – für Oscar-reife Momente.",
        "Tickets, scenes, scores — remembering Oscar-worthy perfomances.": "Tickets, Szenen, Bewertungen – für Oscar-reife Momente.",
        "Tickets, scenes, scores — remembering Oscar-worthy performances.": "Tickets, Szenen, Bewertungen – für Oscar-reife Momente.",
        "ADMIT ONE": "EINTRITT",
        "WATCH LOG": "FILMLOG",
        "MOVIE HIGHLIGHTS": "FILM-HIGHLIGHTS",
        "SCENE 01": "SZENE 01",
        "SCENE 02": "SZENE 02",
        "SCENE 03": "SZENE 03",
        "SCENE 04": "SZENE 04",
        "RATING →": "BEWERTUNG →",
        "Reading.": "Lesen.",
        "Stories worth being remembered — pages, lines, and the lives they made.": "Geschichten, die in Erinnerung bleiben sollen – Seiten, Zeilen und die Menschen, die sie geschaffen haben.",
        "Stories worth remembering — pages, lines, and the lives they opened.": "Geschichten, die in Erinnerung bleiben sollen – Seiten, Zeilen und die Menschen, die sie geschaffen haben.",
        "EX LIBRIS": "EX LIBRIS",
        "From the kitchen — the dishes, the table, the small rituals of the week.": "Aus der Küche – Gerichte, Begegnungen am Tisch und die kleinen Rituale der Woche.",
        "From the kitchen — the dishes, the table, the small rituals of the month.": "Aus der Küche – Gerichte, Begegnungen am Tisch und die kleinen Rituale des Monats.",
        "Food & Recipes.": "Essen & Rezepte.",
        "BREAKFAST": "FRÜHSTÜCK",
        "LUNCH": "MITTAGESSEN",
        "DINNER": "ABENDESSEN",
        "RESTAURANT": "RESTAURANT",
        "OCCASION": "ANLASS",
        "FOOD": "ESSEN",
        "Postcards from the coast — and everywhere else worth remembering.": "Postkarten von der Küste – und von überall sonst, wo Erinnerungen bleiben.",
        "Postcards from everywhere worth exploring and remembering.": "Postkarten von all den Orten, die ich diesen Monat erkundet habe.",
        "Travel & Places.": "Reisen & Orte.",
        "STAMP": "MARKE",
        "Greetings from": "Grüße aus",
        "TO": "AN",
        "The small obsessions — the things kept close, this month.": "Alles, was ich diesen Monat geliebt habe.",
        "Favourites.": "Favoriten.",
        "Beauty": "Beauty",
        "Shelf.": "Regal.",
        "APP / PODCAST / SITE": "APP / PODCAST / WEBSEITE",
        "Nº 11 · AFFIRMATIONS & GOALS": "Nº 11 · ZIELE & AFFIRMATIONEN",
        "Rituals.": "Rituale.",
        "health & wellness": "Gesundheit & Wohlbefinden",
        "The intentions to carry into the next month — said quietly, said clearly.": "Die Absichten für den nächsten Monat – leise gesagt, klar gemeint.",
        "A WORD FOR NEXT MONTH": "EIN WORT FÜR DEN NÄCHSTEN MONAT",
        "Affirmations & Goals.": "Ziele & Affirmationen.",
        "OUTLOOK": "AUSBLICK",
        "Vision": "Vision",
        "Board.": "Board.",
        "FINAL THOUGHTS": "ABSCHLIESSENDE GEDANKEN",
        "— and let it lead the month.": "— und lass es den Monat leiten.",
        "make": "machen",
        "do": "erleben",
        "become": "werden",
        "dream": "träumen",
        "read": "lesen",
        "wear": "tragen",
        "▢  make": "▢  machen",
        "▢  do": "▢  erleben",
        "▢  become": "▢  werden",
        "▢  dream": "▢  träumen",
        "▢  read": "▢  lesen",
        "▢  wear": "▢  tragen",
        "▢  a moment": "▢  ein Moment",
        "▢  a small joy": "▢  eine kleine Freude",
        "▢  photo · banner": "▢  Foto hinzufügen · Banner",
        "▢  photo · large": "▢  Foto hinzufügen · groß",
        "▢  photo · wide": "▢  Foto hinzufügen · breit",
        "▢  self portrait": "▢  Selbstporträt",
        "▢  the date": "▢  das Date",
        "▢  the feeling": "▢  fühlen",
        "▢  the meal": "▢  das Essen",
        "▢  the meal of the month": "▢  das Essen des Monats",
        "▢  the practice": "▢  der Versuch",
        "▢  the scene of the win": "▢  die Szene des Sieges",
        "▢  the view": "▢  die Aussicht",
        "▢  place": "▢  reisen",
        "▢  poster": "▢  Poster",
        "▢  product": "▢  Produkt",
        "▢  scene 01": "▢  Szene 01",
        "▢  scene 02": "▢  Szene 02",
        "▢  scene 03": "▢  Szene 03",
        "▢  scene 04": "▢  Szene 04",
        "Tiny Wins.": "Kleine Siege.",
        "Hobbies.": "Hobbys.",
        "Relationships.": "Beziehungen.",
        "Playlist & Music.": "Playlist & Musik.",
        "PenPalooza": "PenPalooza",
        "APPRECIATION": "WERTSCHÄTZUNG",
        "TOP STORY": "TOP-STORY",
        "FEATURE 1": "FILM 1",
        "FEATURE 2": "FILM 2",
        "A week,": "Eine Woche,",
        "AFTERNOON": "NACHMITTAG",
        "MORNING": "MORGEN",
        "NIGHT": "NACHT",
        "MON": "MO",
        "TUE": "DI",
        "WED": "MI",
        "THU": "DO",
        "FRI": "FR",
        "SAT": "SA",
        "SUN": "SO",
        "M": "M",
        "T": "D",
        "W": "M",
        "F": "F",
        "S": "S",
        "DAY": "TAG",
        "This Month": "Dieser Monat",
        "The Monthly": "Die Geschichten",
        "The": "Das",
        "Story.": "dieses Monats.",
        "VOL. I": "BD. I",
        "One month older and wiser.": "",
        "WHAT I WILL REMEMBER ABOUT IT": "WORAN ICH MICH ERINNERN WERDE",
        "WHAT STAYED WITH ME": "WAS BEI MIR HÄNGEN GEBLIEBEN IST",
        "a note →": "eine Notiz →",
        "with love,": "mit Liebe,",
        "sign here": "hier unterschreiben",
        "body": "Körper",
        "mind": "Geist",
        "love": "Liebe",
        "rest": "Ruhe",
        "feeling": "Gefühl",
        "the feeling": "fühlen",
        "characters": "Figuren",
        "plot": "Handlung",
        "writing": "Schreibstil",
        "title": "Titel",
        "name": "Name",
        "place": "reisen",
        "a place": "ein Ort",
        "seen.": "gesehen.",
        "Places": "Orte",
        "My culinary": "Meine kulinarischen",
        "creations.": "Kreationen.",
        "on a plate.": "auf dem Teller.",
        "CAFÉ / BAR": "CAFÉ / BAR",
        "week one": "Woche eins",
        "week two": "Woche zwei",
        "week three": "Woche drei",
        "week four": "Woche vier",
        "— THE EDITORS": "— DIE REDAKTION",
        "— sunrise —": "— Sonnenaufgang —",
        "— midday —": "— Mittag —",
        "— sundown —": "— Sonnenuntergang —"
    ]
}
